### ISSUE TITLE
Analytics tab colliding with results

### ISSUE THREAD

**Issue by ValentinBercaru** [fossasia/susper.com#1013]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

When the results are displayed, the analytics tab is colliding with the results.

**Expected behavior:**

The analytics tab should not overlap with the results.

**Screenshots of the issue:**

![susper_problem](https://user-images.githubusercontent.com/33882273/40874144-48da9eb0-6674-11e8-9a12-7ea3a5585b0c.gif)

**Comment by praveenojha33** [comment]
@ValentinBercaru Please close this, It has been fixed.

**Comment by ValentinBercaru** [comment]
@praveenojha33 yes, I see :)
