### ISSUE TITLE
Wikipedia tab collide with page content on different screen dimensions

### ISSUE THREAD

**Issue by ValentinBercaru** [fossasia/susper.com#1014]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

Wikipedia tab is colliding with page content on different screen dimensions.

**Expected behavior:**

The Wikipedia tab should disappear on a window size smaller than x pixels (width) or should behave like a show-hide effect.

**Screenshots of the issue:**

![susper](https://user-images.githubusercontent.com/33882273/40874344-ceb18164-6676-11e8-9835-638274e37161.gif)

**Comment by praveenojha33** [comment]
@ValentinBercaru Please close this, It has been fixed.

**Comment by ValentinBercaru** [comment]
@praveenojha33 done.
