### ISSUE TITLE
Menu requires improvements and alignment

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#105]
The menu bar needs some improvements. 

The desired look is:

![screenshot from 2017-03-06 08-58-58](https://cloud.githubusercontent.com/assets/1583873/23593545/3830e71a-024b-11e7-8861-2272e45dbe2b.png)

* [ ] Align menu bar with search bar
* [ ] Keep background of menu extended from above area (gray)
* [ ] Implement underline, bold style
* [ ] Use dark gray for font and on scroll over make it black
* [ ] Move "Tools" to the top right below the search box's right

**Comment by mariobehling** [comment]
Great. Please go ahead.

**Comment by sandeepm96** [comment]
Thank you sir. :)
