### ISSUE TITLE
Size of pictures on contact and about page changed

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#1061]
After a recent update the height of pics on contact and about page has changed. Please re-instate the previous way.

* https://susper.com/about
* https://susper.com/contact

**Comment by khyatidoshi** [comment]
I am a new contributor and an open source enthusiast, and want to work on this issue.

**Comment by praveenojha33** [comment]
@khyatidoshi Please go ahead.
Feel free to ask for any help here https://gitter.im/fossasia/susper.com
Cheers :sparkler:
