### ISSUE TITLE
Missing Tools Tab on screen width less than 496

### ISSUE THREAD

**Issue by simsausaurabh** [fossasia/susper.com#1091]
**I'm submitting a ...**
- [X] bug report
- [ ] feature request

**Current behavior:**

Even though there is enough space to show Tools Tab below screen width less than 496px, it is still not present.

**Expected behavior:**

It should be present with proper spacing.

**Screenshots of the issue:**

![screenshot from 2018-07-10 23-57-02](https://user-images.githubusercontent.com/16608864/42529788-05f33f98-849d-11e8-958a-24bd709e17f9.png)

**Comment by praveenojha33** [comment]
@simsausaurabh Please see how many tabs google show in mobile view.
