### ISSUE TITLE
Highlight the current page on pagination bar.

### ISSUE THREAD

**Issue by khyatidoshi** [fossasia/susper.com#1104]
I'm submitting a ...
- [x] bug report
- [ ] feature request

Current behavior:
The page which is currently being used is not highlighted in the pagination bar at the bottom. 

Expected behavior:
the current page should be highlighted.

Screenshots of the issue:
![pagination_bar](https://user-images.githubusercontent.com/30694154/42755004-53b6f5e6-8914-11e8-99f9-866e488dbc08.PNG)
![pagination_bar2](https://user-images.githubusercontent.com/30694154/42755005-53e46ae4-8914-11e8-9c66-e3a448d6d4f5.PNG)

**Comment by praveenojha33** [comment]
@khyatidoshi Do you want to solve it ?

**Comment by khyatidoshi** [comment]
Working on it...

**Comment by khyatidoshi** [comment]
@praveenojha33 will be providing a PR by today.

**Comment by praveenojha33** [comment]
@khyatidoshi Please see my comment on your PR.
