### ISSUE TITLE
Previous and Next are not working

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#1122]
Previous and Next link have issues. Please fix it:
* The links don't always work
* The area is moving on different pages. It should not move and always be in the same location

![screenshot from 2018-07-24 16-34-58](https://user-images.githubusercontent.com/1583873/43145427-a3e32872-8f5f-11e8-93e4-f64545183f6c.png)
![screenshot from 2018-07-24 17-02-57](https://user-images.githubusercontent.com/1583873/43147513-7f7bbcd4-8f63-11e8-8412-80e9255229b4.png)

**Comment by khyatidoshi** [comment]
Can I work on this issue @mariobehling

**Comment by praveenojha33** [comment]
@khyatidoshi What is status of this issue?
