### ISSUE TITLE
Run Susper without Yacy-Grid

### ISSUE THREAD

**Issue by ZeroCool940711** [fossasia/susper.com#1166]
Hi there, I would like to know if its possible to use Susper without yacy-grid, Im unable to successfully install yacy-grid, no matter what I try and how many guides I find I cant seem to run yacy-grid as some of its components never work, but I do have a working installation of normal Yacy, I just want to use susper as a front-end as the result page is way better than the normal front-end that Yacy has by default. Thanks for the time and hope someone can help me with this.

**Comment by praveenojha33** [comment]
@ZeroCool940711 Currently Susper can run independently (without YaCy or YaCy Grid running locally) as it uses the API of YaCy. If you have any problem installing YaCy Grid locally then you can check out this issue https://github.com/fossasia/susper.com/issues/999 and this blog https://blog.fossasia.org/setting-up-yacy-grid-locally where I have described about local installation of YaCy Grid . If you have any further issue you can ask it here or on chat channel of Susper . Thank You

**Comment by praveenojha33** [comment]
I am closing this issue, if you have any problem ask it here https://gitter.im/fossasia/susper.com

**Comment by ZeroCool940711** [comment]
Hi there, sorry for the delayed response, I already tried multiple times those things on issue #999 and on the other post and still cant make susper run with yacy grid, it always gives me the same error, yacy_grid_mcp is the only thing that never run no matter what I try, I know Susper can run without a local installation of yacy but I would like to use my own index and not the one on the yacy grid site that susper uses by default, I have a pretty big index with 8 billion links and 5 million documents that I would like to use and the only thing I dont like about yacy is the ugly frontend it has which is why I want to use susper as a frontend for it, is there any way to run susper with legacy yacy so I can connect it with my own index and use it from susper?, thanks for the time.

**Comment by praveenojha33** [comment]
Can you please post the problems which you are facing while running yacy_grid_mcp on chat channel. Also if you want to use your local legacy yacy instance you should be able to do that by replacing the hardcoded API with your local API. Please ask your queries here https://gitter.im/fossasia/susper.com or https://gitter.im/yacy/yacy_grid
