### ISSUE TITLE
Display Loader while search result is being fetched.

### ISSUE THREAD

**Issue by rishav-pandey** [fossasia/susper.com#1173]
**I'm submitting a ...**
- [x] feature request

**Current behavior:**
There is not any loader or such kind of notification, which tells the user that website is running and there search result is in progress

**Expected behavior:**
A loader should be displayed to user end, which notifies that there search is being processed, also this increases User Experience.

**Screenshots of the issue:**

**Comment by praveenojha33** [comment]
@simsausaurabh Please suggest your view on it.

**Comment by rishav-pandey** [comment]
@simsausaurabh Yeah, we can use this for better user experience.

**Comment by meetcric** [comment]
is this issue still open?

**Comment by praveenojha33** [comment]
@meetcric Yes the issue is open.

**Comment by meetcric** [comment]
@praveenojha33 is it okay to use Angular spinner for display loading until result being fetched?

**Comment by AakashMallik** [comment]
@meetcric are you working on this?

**Comment by praveenojha33** [comment]
@AakashMallik It is pending from 23 days. If you want you can work on it :+1:

**Comment by AakashMallik** [comment]
@praveenojha33 Alright...

**Comment by sk9331657** [comment]
@AakashMallik  I am claiming this .

**Comment by AakashMallik** [comment]
> @AakashMallik I am claiming this .

There is a PR open for this, I am already working on it. We are waiting for further discussion. If you want to give in some input in the discussion, feel free to do so.

**Comment by praveenojha33** [comment]
@sk9331657 We already have a PR for this.
