### ISSUE TITLE
Security Vulnerability in Gemfile.lock and package-lock.json

### ISSUE THREAD

**Issue by praveenojha33** [fossasia/susper.com#1176]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

There are some securities vulnerabilities in project in Gemfile.lock and package-lock.json. 
**Expected behavior:**

Please fix vulnerable dependencies.
**Screenshots of the issue:**

![image](https://user-images.githubusercontent.com/25537606/46659358-6e5d9e80-cbd2-11e8-92fc-e507bd42a433.png)

**Comment by sk9331657** [comment]
@praveenojha33  I am claiming it.
