### ISSUE TITLE
Add SUSI.AI for Magic Mirror, Yaydoc, Meilix and Phimp.me in Projects section under the menus icon in the navbar

### ISSUE THREAD

**Issue by sarnava1** [fossasia/susper.com#1179]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

Presently we have only badgeyay,eventyay,loklak,susi,fossasia and pslab which appears on clicking on menus icon on the navbar. We should include Phimp.me, Meilix, Yaydoc and SUSI.AI for Magic Mirror also as they are important FOSSASIA projects. The meilix project already includes them.

**Screenshots of the issue:**

Meilix navbar:
![aspectratioprb](https://user-images.githubusercontent.com/25319565/46952728-55a92900-d0a9-11e8-9536-799b041e29e3.png)
SUSPER navbar:
![contactinsusper](https://user-images.githubusercontent.com/25319565/46952814-9bfe8800-d0a9-11e8-8190-6e6034387481.png)

**Comment by sarnava1** [comment]
@simsausaurabh I want ot work on this issue. Please assign me this issue.

**Comment by sk9331657** [comment]
@simsausaurabh  I am claiming this since it has been 21 days and there is no update on the pr.

**Comment by sarnava1** [comment]
@sk9331657 please look into this PR https://github.com/fossasia/susper.com/pull/1194 where @simsausaurabh suggested some changes.
