### ISSUE TITLE
(UI) Google Search Engine Copy

### ISSUE THREAD

**Issue by niteshkumarniranjan** [fossasia/susper.com#1195]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**
UI is duplicate of Google

**Expected behavior:**
It Should have its unique UI

**Would You like to work on it**
Yes

**Comment by sk9331657** [comment]
@niteshkumarniranjan  Issue is irrelevant. Susper needs to have similar UI as of Google.

**Comment by niteshkumarniranjan** [comment]
@sk9331657 I have no Idea why we need to have a copy of Google's UI.
BTW. I'm closing as you said it's irrelevant for the project.
