### ISSUE TITLE
Progress bar for search

### ISSUE THREAD

**Issue by yasirunilan** [fossasia/susper.com#12]
Isn't it good to have a progress bar to show while doing a search.

**Comment by nikhilrayaprolu** [comment]
@yasirunilan right now we have a prgressbar which shows "loading" on search. how do you want to change the progressbar?

**Comment by yasirunilan** [comment]
some thing like a circular, rotating progress bar

**Comment by mariobehling** [comment]
It might be useful, but we should first implement the basic app to understand where this could go to. In some areas search will be fast and then we don't need such an info item there. 

Closing it there fore. Open when the time has come.
