### ISSUE TITLE
Headings on Contact and About Page are too close to the picture

### ISSUE THREAD

**Issue by saarthakchats** [fossasia/susper.com#1206]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
Text is too close, it looks bad

**Expected behavior:**
Add some space

**Screenshots of the issue:**
<img width="1346" alt="screenshot 2018-11-09 at 5 34 50 am" src="https://user-images.githubusercontent.com/24372680/48234820-3c15ab80-e3e1-11e8-8a6f-1de18f5aaff9.png">
![screenshot 2018-11-09 at 5 34 30 am](https://user-images.githubusercontent.com/24372680/48234892-8e56cc80-e3e1-11e8-9ccc-44d5a81f65ab.png)

**Comment by saarthakchats** [comment]
I'm working on this

**Comment by praveenojha33** [comment]
@saarthakchats This issue has already been fixed. Soon we will be merging development and master branch than it will be fixed on susper.com also. Please see this PR https://github.com/fossasia/susper.com/pull/1183
