### ISSUE TITLE
Open Source Map Link to be added to the Address 

### ISSUE THREAD

**Issue by saarthakchats** [fossasia/susper.com#1207]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**
No link

**Expected behavior:**
Should be there

**Screenshots of the issue:**
<img width="362" alt="screenshot 2018-11-14 at 9 26 34 pm" src="https://user-images.githubusercontent.com/24372680/48494485-fbd88200-e853-11e8-91e9-90c2f318a2d8.png">
We can add a link to this address

**Comment by saarthakchats** [comment]
I'm working on this

**Comment by praveenojha33** [comment]
@saarthakchats Please give more details about this issue.

**Comment by saarthakchats** [comment]
@praveenojha33 
I added the related screenshot
