### ISSUE TITLE
Implementing auto-search suggestion feature in susper search

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#121]
Currently, susper does not have auto search suggestion feature - 

![selection_018](https://cloud.githubusercontent.com/assets/22245418/23996508/a750b5d2-0a73-11e7-895c-645eab456d29.png)

We should implement the auto-search suggestion feature similar to Google. 

![google-chabad3](https://cloud.githubusercontent.com/assets/22245418/23996553/d0862ed2-0a73-11e7-8730-48015f954dbd.jpg)

I would like to work on this, but need some time.

**Comment by harshit98** [comment]
@nikhilrayaprolu To implement this feature, should I make a new file `autocomplete.service.ts` in app folder? and import the `AutoService` in `app.module.ts` ?

**Comment by nikhilrayaprolu** [comment]
I don't find these features in susper.com so reopening this issue.

**Comment by harshit98** [comment]
@nikhilrayaprolu I have added the configuration files for autocomplete feature but feature has not been implemented yet. I was not able to figure it, how should it work because it may clash with `index.ts` file in which `auto-search feature` has been implemented.

**Comment by harshit98** [comment]
@Orbiter @nikhilrayaprolu I need some guidance here to implement autocomplete feature. : )

**Comment by nikhilrayaprolu** [comment]
@harshit98 are you able to get suggestions from yacy on http://yacy.searchlab.eu/suggest.json?q=how
I get an empty array on that call

**Comment by harshit98** [comment]
@nikhilrayaprolu No I'm not able to get suggestions from yacy.

**Comment by harshit98** [comment]
@nikhilrayaprolu http://yacy.searchlab.eu/suggest.json?q=how
The query is now returning suggestions. 

![image](https://cloud.githubusercontent.com/assets/22245418/25925731/1ece63e2-3608-11e7-8ce1-466224b5d2d2.png)

**Comment by nikhilrayaprolu** [comment]
good to know this @harshit98 now we could implement suggestions.

**Comment by nikhilrayaprolu** [comment]
@Orbiter I don't find suggest.json a good point to use for suggestion. most of the suggestions aren't perfectly working. Can you suggest us some other way possible?

**Comment by Orbiter** [comment]
that suggest api is all we have right now, if you find a better solution, go for it

**Comment by harshit98** [comment]
working on this issue. :+1:
