### ISSUE TITLE
Footer is hiding some of the content of terms and privacy page.

### ISSUE THREAD

**Issue by rajvaibhavdubey** [fossasia/susper.com#1220]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

Footer is hiding some of the content of terms and privacy pages respectively.

**Screenshots of the issue:**

![screenshot from 2018-11-17 03-09-50](https://user-images.githubusercontent.com/33062425/48648681-49045180-ea16-11e8-951c-2f8bfb699542.png)

![screenshot from 2018-11-17 03-13-43](https://user-images.githubusercontent.com/33062425/48648856-d0ea5b80-ea16-11e8-88ac-83ef8b81c976.png)

**Comment by Ryan10145** [comment]
@rajvaibhavdubey This is a dupliate of #1216
