### ISSUE TITLE
Change the layout of About and Contact pages. 

### ISSUE THREAD

**Issue by rajvaibhavdubey** [fossasia/susper.com#1221]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

The images of About and contact us pages occupy the whole page instead we could have 1/4th or half page image.
On About page the image occupies more than the full page we have to scroll 1 and a half pages to get to the actual information.

**Screenshots of the issue:**

![screenshot from 2018-11-17 03-19-02](https://user-images.githubusercontent.com/33062425/48649117-98974d00-ea17-11e8-8a6c-7f7870f98cdc.png)

![screenshot from 2018-11-17 03-19-18](https://user-images.githubusercontent.com/33062425/48649123-9df49780-ea17-11e8-9990-b6d8784f3bed.png)

**Are you working on this**
Yes

**Comment by rajvaibhavdubey** [comment]
@simsausaurabh @praveenojha33 Please give your reviews, so that I can work on this.
ThankYou :smile:

**Comment by shreyanshdwivedi** [comment]
@rajvaibhavdubey why is there **Contact** at bottom of `about` page?
![screenshot_2018-12-13 susper - decentral search engine](https://user-images.githubusercontent.com/25428397/49945268-7ad3df80-ff12-11e8-93ae-5db93535549a.png)
