### ISSUE TITLE
Items in Settings and Tools Menu are not Centered

### ISSUE THREAD

**Issue by Ryan10145** [fossasia/susper.com#1222]
**I'm submitting a ...**
- [X] bug report
- [ ] feature request

**Current behavior:**

In the search results section, the text in the Settings and Tools menu is not centered.

**Expected behavior:**

The text should be centered within the gray area.

**Screenshots of the issue:**

![image](https://user-images.githubusercontent.com/8119928/48656522-dc785b00-e9f3-11e8-93c3-79adffd988b1.png)

**I am working on this**

**Comment by mariobehling** [comment]
They should not be centered. They should be aligned as it is in the Google.com search results page.
