### ISSUE TITLE
Clear search bar input on component load

### ISSUE THREAD

**Issue by rohitrajhans** [fossasia/susper.com#1230]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

When the brand logo is clicked to go back to homepage, the search input is not cleared. It displays the previous search string

**Expected behavior:**

On loading search bar component, the search input is cleared.

**Screenshots of the issue:**

Results page: 
![screenshot from 2018-11-20 01-04-18](https://user-images.githubusercontent.com/31156637/48730643-04202b00-ec61-11e8-9f43-32ba527d885e.png)

After selecting Susper logo:
![screenshot from 2018-11-20 01-04-25](https://user-images.githubusercontent.com/31156637/48730655-097d7580-ec61-11e8-9f77-8b5290cd58e5.png)

**Comment by rohitrajhans** [comment]
I'm currently working on it

**Comment by shreyanshdwivedi** [comment]
This issue is not being worked upon since last 18 days. I'm taking this up

**Comment by plxity** [comment]
@shreyanshdwivedi  any progress on this?

**Comment by shreyanshdwivedi** [comment]
@plxity I've been busy with other issues. You can take this up if you want :)

**Comment by plxity** [comment]
@shreyanshdwivedi Okay sure.

**Comment by reeversedev** [comment]
@plxity Can I take this issue because I think I've figured out the way to do it.

**Comment by plxity** [comment]
@reeversedev  Okay sure. No problem 👍
