### ISSUE TITLE
Convert Bootstrap to Angular Material framework. 

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#124]
The overall design of susper is pretty much going towards material design. So why not to implement an actual Material design using Angular Material instead of using Bootstrap ?

**Comment by isuruAb** [comment]
this is good suggestion. since they are providing good set of angular material components, these tasks will be easy to do with angular material

**Comment by harshit98** [comment]
@isuruAb I agree with you. The Angular Material design contains lots of directives that you won't have to write. So yes, I think there is a big difference but angular-material doesn't support old browsers.

**Comment by harshit98** [comment]
Wokring on this issue. :+1:

**Comment by mariobehling** [comment]
How much is Google following its Material guidelines on its own services? Is the Google Search service using material? Will this allow us themability? That would be great.

**Comment by nikhilrayaprolu** [comment]
does themability mean giving user the choice of extensions to the themes?
secondly, there are a lot of things that need to be done in the functionality susper.So it's better we concentrate on functionality first and then focus on converting the themes in the last milestones?

**Comment by mariobehling** [comment]
> does themability mean giving user the choice of extensions to the themes?
no extensions, just other themes. We can do this later.

**Comment by nikhilrayaprolu** [comment]
since we had a discussion on continuing with bootstrap, I am closing this issue. If any one wants to discuss again on this please kindly feel free to reopen this issue.
