### ISSUE TITLE
Footer link should open in new tab

### ISSUE THREAD

**Issue by saarthakchats** [fossasia/susper.com#1245]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
Links open on the same page

**Expected behavior:**
Should open on new tab(target= "_blank")

**Screenshots of the issue:**

**Will work on the issue:**
Yes

**Comment by parammittal16** [comment]
@saarthakchats can i work on this ?

**Comment by mariobehling** [comment]
No need.
