### ISSUE TITLE
addition of preview feature as it was in google

### ISSUE THREAD

**Issue by nikhilrayaprolu** [fossasia/susper.com#125]
![image](https://cloud.githubusercontent.com/assets/15216503/24161598/dd42a964-0e8a-11e7-9af4-2b3645b59e77.png)

previewing the documents in susper would help users to identify their documents and verify them without opening.

**Comment by harshit98** [comment]
I liked this idea very much!

**Comment by harshit98** [comment]
@nikhilrayaprolu Can we use http://qtip2.com/ qtip2 jQuery API to implement this feature?

**Comment by nikhilrayaprolu** [comment]
nope qtip2 is not required we can implement this feature using iframe

**Comment by harshit98** [comment]
@nikhilrayaprolu I implemented this feature using iframe previously. I got struck here - http://stackoverflow.com/questions/42946184/angular2-how-should-i-implement-google-instant-preview-using-angular2

**Comment by nikhilrayaprolu** [comment]
@harshit98  looks like you got a reply there in stackoverflow community.

**Comment by mariobehling** [comment]
I think we lacked a good discussion about this. Google removed this feature as well. It is hard to get this working reliably. Please see the issue here https://github.com/fossasia/susper.com/issues/169 and remove this feature for now. Cheers.
