### ISSUE TITLE
Problems in the Privacy page

### ISSUE THREAD

**Issue by saarthakchats** [fossasia/susper.com#1261]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
- Incorrect CSS makes text look like a link unnecessarily
- Hidden text - text and link not visible, footer is covering it
- Wrong class -- issues with CSS

**Expected behavior:**
- Fix CSS
- Add padding and margin
- Make all required things visible

**Screenshots of the issue:**
## This text is incorrectly styled
<img width="357" alt="screenshot 2018-12-06 at 3 42 12 pm" src="https://user-images.githubusercontent.com/24372680/49577493-88ff8a00-f96d-11e8-9fe7-e760e5d06986.png">

## Hidden text in the contact section
<img width="1427" alt="screenshot 2018-12-06 at 3 42 20 pm" src="https://user-images.githubusercontent.com/24372680/49577505-8b61e400-f96d-11e8-963d-769cd159151d.png">

**Will work on the issue:**
Yes

**Comment by praveenojha33** [comment]
Please open a detailed issue with screenshots. You have mentioned bugged linking, where it is? Weird Style ? which styles are you talking about. Hidden Text ? which please show us which text is hidden. Please provide screenshots.

**Comment by AakashMallik** [comment]
Expected behavior: Perfection ? :joy:

**Comment by saarthakchats** [comment]
Done @praveenojha33

**Comment by rajvaibhavdubey** [comment]
@saarthakchats The footer issue has already been solved in https://github.com/fossasia/susper.com/pull/1265 
ThankYou :smile:

**Comment by saarthakchats** [comment]
I'm not changing the stuff with the footer, I'm simply making the text visible on the *Privacy Page* by moving it upwards
