### ISSUE TITLE
Redundant wiki search

### ISSUE THREAD

**Issue by rajvaibhavdubey** [fossasia/susper.com#1275]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Screenshots of the issue:**

![screenshot from 2018-12-09 10-54-34](https://user-images.githubusercontent.com/33062425/49693727-e891ab80-fba0-11e8-9a44-ed6e372f0b18.png)

The short description before the first result has the same content and purpose as the wiki search on right
@praveenojha33 Is it really required?
**Will work on the issue:**
Yes

**Comment by shreyanshdwivedi** [comment]
@rajvaibhavdubey In some cases they maybe redudant but in some cases they are different too.
![screenshot_2018-12-10 susper - decentral search engine](https://user-images.githubusercontent.com/25428397/49701478-dbada000-fc12-11e8-8617-480735091e1c.png)

**Comment by praveenojha33** [comment]
@rajvaibhavdubey Some content can be same. We use the content for intelligence is fetched from susi whereas the description in infobox is fetched using `wikidata`
