### ISSUE TITLE
Spell Check similar to google like “Do you Mean that?”

### ISSUE THREAD

**Issue by nikhilrayaprolu** [fossasia/susper.com#128]
spell checking similar to google search could be incorporated
![image](https://cloud.githubusercontent.com/assets/15216503/24162386/58370f46-0e8d-11e7-846d-8c029dc201de.png)

**Comment by isuruAb** [comment]
is there any recommended API or library to use  ?

**Comment by nikhilrayaprolu** [comment]
Did you find any APIs or libraries to use for this.I found this which is used in most popular programs http://hunspell.github.io/
@Orbiter are there any good Machine Learning libraries that provide this functionality? or I think we could build one on the back end side (http://stackoverflow.com/questions/307291/how-does-the-google-did-you-mean-algorithm-work ) .

**Comment by mariobehling** [comment]
@nikhilrayaprolu We can come back to features like that once the basics of the services are running. Right now there are too many small things not working.

**Comment by Marauderer97** [comment]
Working on this, will try and implement using wordsapi

**Comment by nikhilrayaprolu** [comment]
@Marauderer97 there are many APIs which implements this, I have referenced hunspell which is used in LibreOffice, macOS, Firefox.You can use any one you prefer, but check that they have a good community behind them and also efficient in giving better results.
