### ISSUE TITLE
addition of authentication and authorisation into susper.com

### ISSUE THREAD

**Issue by nikhilrayaprolu** [fossasia/susper.com#130]
this would allow us to give user-specific results, and also help him maintain history of individual users, also will be useful later for learning to implement machine learning algorithms for user specific results.

**Comment by sandeepm96** [comment]
We need to maintain a database for this. @nikhilrayaprolu how do you think we should start on this?

**Comment by nikhilrayaprolu** [comment]
look at yacy-grid backend for susper, it has an authentication module getting implemented in coming days (an authentication module from susi_server will be used) , we will use it here.

**Comment by nikhilrayaprolu** [comment]
@Orbiter  any suggestion on this?

**Comment by mariobehling** [comment]
We would need to maintain our own Yacy-Grid instance. As this system is still under heavy development this feature needs to be postponed.

**Comment by Orbiter** [comment]
yes
