### ISSUE TITLE
Create accounts on susper.com

### ISSUE THREAD

**Issue by rajvaibhavdubey** [fossasia/susper.com#1303]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Expected behavior:**

@mariobehling @praveenojha33 @simsausaurabh I think that it is the right time that we should include the accounts feature on susper.com(local sign-up and login only, not through google or facebook) just like google. Then only can we provide personalized features like `safe search`, `intelligence search`, `store the location of user`, `search recommendation` , `store search history` etc. because all these are user-specific features. At a later phase maybe we can link all the services of fossasia through susper. 

**Will work on the issue:**
Yes

**Comment by mariobehling** [comment]
This feature is out of scope currently. We rather need to improve the Yacy Grid automatic deployment.
