### ISSUE TITLE
Fix Travis

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#1310]
Travis is currently not working. Please help to fix it.

**Comment by pythongiant** [comment]
@mariobehling seems like it does https://travis-ci.org/fossasia/susper.com/builds/467164997?utm_source=github_status&utm_medium=notification
am I missing something here?

**Comment by AakashMallik** [comment]
@subhahu123 @pythongiant I am taking it up, that PR was waiting for discussion and probably was accidentally merged. I'll fix it.

**Comment by AakashMallik** [comment]
@subhahu123 PR 1308? How did you come to that conclusion?

**Comment by subhahu123** [comment]
@AakashMallik 
![screenshot from 2018-12-19 13-46-47](https://user-images.githubusercontent.com/34541684/50207501-a9c7d680-0394-11e9-8e0b-e25df5da9948.png)
it was working before the merging of this pull request .
And if u see timing they are both same. means just after merginig this error problem start

**Comment by AakashMallik** [comment]
> @AakashMallik
> ![screenshot from 2018-12-19 13-46-47](https://user-images.githubusercontent.com/34541684/50207501-a9c7d680-0394-11e9-8e0b-e25df5da9948.png)
> it was working before the merging of this pull request .
> And if u see timing they are both same. means just after merginig this error problem start


I hope you know that travis check starts late after the push, so timing is not really a piece of good evidence and travis tests passed for that PR FYI so it was not that merge that broke travis. Cheers.

**Comment by AakashMallik** [comment]
@simsausaurabh I have already dropped a PR fixing the issue. Please read the message thread completely. Cheers. :+1:
