### ISSUE TITLE
add codecoverage tools

### ISSUE THREAD

**Issue by nikhilrayaprolu** [fossasia/susper.com#132]
since we are in a stage of incorporating tests to susper, it is better we start adding a codecoverage tool and then know how much code is covered by the tests we write. this would also allow write efficient quality tests.

**Comment by harshit98** [comment]
@nikhilrayaprolu Already we have a file `codecov.yml`. Looks like, it has no use. I have done some work on this. Please review my commit.

**Comment by harshit98** [comment]
@nikhilrayaprolu Previously, I did some work on this but the code coverage was not being generated using karma. What should we do?

**Comment by nikhilrayaprolu** [comment]
@harshit98  Okay I will go through this and fix it.

**Comment by harshit98** [comment]
@nikhilrayaprolu reports which are generated are being stored inside docker. We have to pass them through, docker. I'll make a PR today of it. You can go through it.

**Comment by harshit98** [comment]
@mariobehling Please reopen this issue. Some more work is left that has to be completed. : )

**Comment by nikhilrayaprolu** [comment]
@harshit98 can you please tell me what work is left on this issue, so that I could look into it.

**Comment by harshit98** [comment]
@nikhilrayaprolu The reports which are being generated should be passed through docker container. I have created a docker file and a shared folder where all the coverage reports will be stored. You can read the whole travis report <a href="https://travis-ci.org/fossasia/susper.com/builds/221944119">here</a>.

**Comment by nikhilrayaprolu** [comment]
ok sounds good.

**Comment by nikhilrayaprolu** [comment]
@harshit98 are you able to produce the code coverage reports atleast in html or on command line?

**Comment by harshit98** [comment]
@nikhilrayaprolu I have not tried this method. I was not knowing about it. :sweat_smile:
