### ISSUE TITLE
Refactor and Cleanup Help Component

### ISSUE THREAD

**Issue by shreyanshdwivedi** [fossasia/susper.com#1336]
**I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [x] refactoring

**Current behavior:**

The following issues persist in the Help component.
    - Standard coding practice is not followed.
    - Remove redundant css classes
    - Increase coverage

**Expected behavior:**

To solve above mentioned issues

**Will work on the issue:**
Yes

**Comment by rajvaibhavdubey** [comment]
@shreyanshdwivedi Are you working on this? I would like to work on this.
Thankyou :smile:

**Comment by shreyanshdwivedi** [comment]
@rajvaibhavdubey yeah I'm working on this. Will be pushing my first commit soon 😅
