### ISSUE TITLE
The box is incomplete at the bottom of the dropdown menu

### ISSUE THREAD

**Issue by AnishRaj2000** [fossasia/susper.com#1344]
**I'm submitting a ...**
- [x] bug report

**Current behavior:**
border is incomplete at the bottom elements of the dropdown menu in the homepage of search engine.

**Expected behavior:**
 Complete borders of bottom elements in the dropdown menu in the homepage..eg.eventyay logo.

**Screenshots of the issue:**
 
![screenshot from 2018-12-24 22-59-19](https://user-images.githubusercontent.com/18510825/50404605-da15d780-07cf-11e9-84d6-02f43c39f021.png)

**Will work on the issue:**
Yes

**Comment by shreyanshdwivedi** [comment]
@AnishRaj2000 always provide sufficient info about the error alongwith screenshot (if applicable). This will give others proper understanding of the issue. Please edit it :)

**Comment by AnishRaj2000** [comment]
sir i am unable to upload the photo. it only shows a link.

**Comment by subhahu123** [comment]
![peek 2018-12-24 23-07](https://user-images.githubusercontent.com/34541684/50404694-c74fd280-07d0-11e9-8ebb-2a61cf2784c6.gif)

**Comment by subhahu123** [comment]
border is complete

**Comment by AnishRaj2000** [comment]
but its not showing for me..

**Comment by subhahu123** [comment]
u r using chrome or firefox or what

**Comment by AnishRaj2000** [comment]
chrome

**Comment by shreyanshdwivedi** [comment]
@AnishRaj2000 the link is automatically shown as image once you comment it. Please comment down screenshot of your issue
And u need not call anyone sir here. :)

**Comment by subhahu123** [comment]
> @shreyanshdwivedi sir i am unable to upload the photo. it only shows a link.

add [ at begining of screenshot from 2018-12-24 22-59-19](https://user-images.githubusercontent.com/18510825/50404605-da15d780-07cf-11e9-84d6-02f43c39f021.png)

**Comment by AnishRaj2000** [comment]
@subhahu123 how is it coming for you??..

**Comment by subhahu123** [comment]
> chrome

i have checked in chrome also it's working fine

**Comment by AnishRaj2000** [comment]
even the set susper your default is not shown for me

**Comment by subhahu123** [comment]
> even the set susper your default is not shown for me

it has been for removed for chrome users

**Comment by AnishRaj2000** [comment]
how are u running ur project @subhahu123

**Comment by subhahu123** [comment]
directly
using susper.com

**Comment by subhahu123** [comment]
> how are u running ur project @subhahu123

i have not deployed it

**Comment by AnishRaj2000** [comment]
can u try running it in your local host

**Comment by AnishRaj2000** [comment]
> directly
> using susper.com

yes i saw just now its running perfectly

**Comment by subhahu123** [comment]
> can u try running it in your local host

are using local host server trying directly or opening index.html

**Comment by AnishRaj2000** [comment]
i am using local host server

**Comment by subhahu123** [comment]
> i am using local host server

then it should work

**Comment by AnishRaj2000** [comment]
@subhahu123 i just observed... its running perfectly in firefox but not on chrome

**Comment by AnishRaj2000** [comment]
but what's the issue for chrome??

**Comment by AnishRaj2000** [comment]
@subhahu123 the scrolls are not appearing in chrome i have observed just now... i am sorry it is my mistake...

**Comment by AnishRaj2000** [comment]
i will close this issue.

**Comment by subhahu123** [comment]
> @subhahu123 the scrolls are not appearing in chrome i have observed just now... i am sorry it is my mistake...

try to delete cache and cookies 
and update ur browser

**Comment by AnishRaj2000** [comment]
@subhahu123  ok thanks :)
