### ISSUE TITLE
Tutorial on using Susper

### ISSUE THREAD

**Issue by Marauderer97** [fossasia/susper.com#136]
Once we add sophisticated search mechanisms to Susper, it will be really useful to have a full-fledged guide on using Susper. We can also have forums where people can pose queries, just like google does.
![image](https://cloud.githubusercontent.com/assets/20185076/24304775/a07ce0c8-10e0-11e7-8610-7b376dddc3a4.png)

**Comment by nikhilrayaprolu** [comment]
@Marauderer97  there are a lot features which we need to implement (or) port from yacy . look at http://yacy.searchlab.eu/ you will find a lot features which are required to be implemented.there is this complete video series on how to use Yacy https://www.youtube.com/user/YaCyTutorials/videos ,which could be documented and ported to susper

**Comment by harshit98** [comment]
I would like to work on this. :+1:

**Comment by 94151** [comment]
I would like to contribute to documentation for using super.
