### ISSUE TITLE
Bottom - margin is not working in #pagbar ( But it is working in surge link )

### ISSUE THREAD

**Issue by subhahu123** [fossasia/susper.com#1362]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
-  margin-bottom attibute is not working properly
while checking on console , it hides that property (not present in console but present in result.component.css file)
- according to the console some attributes are overridening the margin attribute but some not 
- For example . .pagination margin top and left is overriden but margin-bottom is not shown in #page bar
and .pagination margin-bottom is working but others not
- In surge link they are working properly but not on the main website

**Screenshots of the issue:**

![screenshot from 2018-12-29 02-26-52](https://user-images.githubusercontent.com/34541684/50527895-47e43b00-0b11-11e9-8652-05225c922f38.png)

![screenshot from 2018-12-29 02-30-26](https://user-images.githubusercontent.com/34541684/50528002-c5a84680-0b11-11e9-9ea8-e43a7233318a.png)

***Will work on the issue:***
Yes

**Comment by subhahu123** [comment]
why margin-bottom is not shown in console #pag-bar id
and not overridening the .pagination class margin-bottom attribute while others are working fine
@shreyanshdwivedi

**Comment by shreyanshdwivedi** [comment]
I think the reason is because main website is not on development branch and we work on dev branch. There are many changes that are yet not pushed to main website. @subhahu123

**Comment by subhahu123** [comment]
@shreyanshdwivedi #1360

**Comment by subhahu123** [comment]
@shreyanshdwivedi  can we squash commits without downloading whole repo
just by editting the file on which github stores commit report or data

**Comment by shreyanshdwivedi** [comment]
I haven't tried it. But squashing commits hardly 2 minutes
1. `git rebase -i HEAD~n`
Where n is number of commits to be squashed

2. Change `pick` to `squash` for the commit to be squashed leaving 1st one

3. `git push origin branch_name --force`

**Comment by subhahu123** [comment]
> I haven't tried it. But squashing commits hardly 2 minutes
> 
>     1. `git rebase -i HEAD~n`
>        Where n is number of commits to be squashed
> 
>     2. Change `pick` to `squash` for the commit to be squashed leaving 1st one
> 
>     3. `git push origin branch_name --force`

but it require local copy of repo

**Comment by subhahu123** [comment]
> @subhahu123 You need to have a local copy of repo to squash the commits.

i know ...
was tryin to know if there is an another way to do that without making local copy of whole repo  i.e. like by just eddtiting the commit history files
