### ISSUE TITLE
Decrease the height of dropdown menu

### ISSUE THREAD

**Issue by samagragupta** [fossasia/susper.com#1364]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**
![drop](https://user-images.githubusercontent.com/32234926/50536864-0db18280-0b7f-11e9-9cca-f888524f1f44.PNG)

**Expected behavior:**
Decreasing the height of the drop-down menu. Just like in google. This will also remove the problem of overlapping of dropdown with search bar.

**Screenshots of the issue:**
![dropdown](https://user-images.githubusercontent.com/32234926/50536880-4d786a00-0b7f-11e9-83d9-23b23958f501.PNG)

**Will work on the issue:**
Yes

**Comment by mariobehling** [comment]
This is not needed. Please take Google.com as an example.
