### ISSUE TITLE
Maintain user search history

### ISSUE THREAD

**Issue by Marauderer97** [fossasia/susper.com#137]
This is quite an ambitious goal, but if we are able to implement user accounts as mentioned in #130 we can add user search history too, perhaps upto the last 50 searches

**Comment by nikhilrayaprolu** [comment]
@Orbiter does Yacy-Grid has authentication and authorization. It would be good to have token - based authentication in it .as per the discussion on gitter we thought of taking the authentication module from susi_server . so I will look into susi_server authentication and plan on how to integrate it with a frontend.

**Comment by nikhilrayaprolu** [comment]
@Orbiter  any suggestion upon this?
