### ISSUE TITLE
Mobile compatibility for susper

### ISSUE THREAD

**Issue by Marauderer97** [fossasia/susper.com#138]
There are minor glitches in the website when we open susper on a mobile phone. The top bar gets hidden on being zoomed. 
![image](https://cloud.githubusercontent.com/assets/20185076/24319920/2d116f58-1150-11e7-84be-6cbbdedc45fd.png) 
Also the images button does not work easily.

**Comment by harshit98** [comment]
@Marauderer97 I didn't found any issue regarding this while running susper on mobile.

**Comment by harshit98** [comment]
**UPDATE**  : Currently at present it looks like this - 

![selection_019](https://cloud.githubusercontent.com/assets/22245418/25873114/cdf6b25e-352a-11e7-8b41-60186958f1a9.png)

**Comment by harshit98** [comment]
Please close this issue as it has been solved in PR #262

**Comment by harshit98** [comment]
This issue can be closed now. Susper is now compatible for all screen size.
