### ISSUE TITLE
Create Smail service for susper like gmail

### ISSUE THREAD

**Issue by subhahu123** [fossasia/susper.com#1385]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Screenshots of the issue:**

![screenshot from 2019-01-06 23-19-37](https://user-images.githubusercontent.com/34541684/50739675-924c7280-1209-11e9-962d-711dc3ba0164.png)

**Will work on the issue:**
yes
I have already started work on this

**Comment by subhahu123** [comment]
@shreyanshdwivedi @rajvaibhavdubey 
 can u create backend for our smail service

**Comment by rajvaibhavdubey** [comment]
@subhahu123 Would love to contribute, but to make an email service we need to have a dedicated mail server, we have open source mail servers available like iRedmail and zimbra ,Let's take reviews of mentor's first before proceeding.
@praveenojha33 @simsausaurabh

**Comment by subhahu123** [comment]
Ok

**Comment by subhahu123** [comment]
@rajvaibhavdubey i have these open source mail server they also provide front-end or back defaultly
 how we are going to deal with that

**Comment by subhahu123** [comment]
@rajvaibhavdubey  ok........
i just got this
![screenshot from 2019-01-08 01-53-09](https://user-images.githubusercontent.com/34541684/50791596-550ae200-12e8-11e9-91dc-86531b0fa835.png)

**Comment by subhahu123** [comment]
but there  is nothing to send mails

**Comment by subhahu123** [comment]
@rajvaibhavdubey we can use this
https://github.com/nodemailer/wildduck
https://api.wildduck.email/

**Comment by shreyanshdwivedi** [comment]
@subhahu123 I think we should wait till the maintainers decide if we should proceed on this or not.

**Comment by Aakash-DD** [comment]
yeah this mail system can be applied (may be Smail )

**Comment by Aakash-DD** [comment]
@mentors waiting just only for mentors to confirm.... @praveenojha33 @simsausaurabh
