### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#139]
There are some minor errors in README.md file. 

This should not be showing `build : error`. Travis is working fine. Also, **Communication** heading should look like a heading.
![selection_029](https://cloud.githubusercontent.com/assets/22245418/24359000/917abe78-1320-11e7-807d-6dd8e60f3eb5.png)

Spelling mistakes. It should be 'angular'.
![selection_030](https://cloud.githubusercontent.com/assets/22245418/24359042/c08c9bfa-1320-11e7-81af-cf2f83fc2eb2.png)

Add this - if someone wants to update the Angular-CLI as it is very much helpful to overcome the problems while setting up it on local environment.
![selection_034](https://cloud.githubusercontent.com/assets/22245418/24359143/144df176-1321-11e7-9be4-02b685367344.png)

There is no branch with name 'development'.
![selection_033](https://cloud.githubusercontent.com/assets/22245418/24359214/4b4537ac-1321-11e7-9358-d3f9aa40bac1.png)

**Comment by bharadwajturlapati** [comment]
Hi @harshit98 /Team ,
I am new to susper. Just want to get started.
I can take up fixing the communication heading thing.
Coming to builderror gh-pages build is failing from a long time.
https://travis-ci.org/fossasia/susper.com/branches

**Comment by harshit98** [comment]
@bharadwajturlapati Hi. You can go ahead and solve this issue :) 
Regarding to build error - @nikhilrayaprolu any suggestions? - https://travis-ci.org/fossasia/susper.com/branches

**Comment by nikhilrayaprolu** [comment]
@bharadwajturlapati @harshit98 there is no trouble with build regarding the gh-pages, we don't need to run travis for gh-pages. That's a build error which was raised about a month ago.

**Comment by bharadwajturlapati** [comment]
@nikhilrayaprolu  okay :) then is the url wrong in readme.md  file ?
If so can we change the build url tag in the readme to angular branch instead of gh-pages ?
