### ISSUE TITLE
Overflow along x-axis in menu of apps

### ISSUE THREAD

**Issue by roninx991** [fossasia/susper.com#1390]
**I'm submitting a ...**
- [x] bug report

**Current behavior:**

When we click on top right corner to view other apps/products, we get a dropdown where there is overflow along x axis.

**Expected behavior:**

There shouldn't be any overflow along x-axis if we're trying to have a UI similar to that of Google Search.
![screenshot from 2019-01-07 22-19-15](https://user-images.githubusercontent.com/20491970/50781121-97bdc180-12ca-11e9-80a6-aac8bcc665e1.jpg)

**Screenshots of the issue:**

![screenshot from 2019-01-07 20-23-14](https://user-images.githubusercontent.com/20491970/50780935-3564c100-12ca-11e9-837d-12b86289b80a.jpg)

**Will work on the issue:**
Yes, I will work on this issue.

**Comment by Amanchouhan192** [comment]
@Sangatdas hey can i take this issue ..

**Comment by roninx991** [comment]
@Amanchouhan192 I'm working on this

**Comment by roninx991** [comment]
@Amanchouhan192 will be fixed by PR #1451 
You can review my PR if you want. :)
