### ISSUE TITLE
Susper logo button on homepage wrong redirect

### ISSUE THREAD

**Issue by rajvaibhavdubey** [fossasia/susper.com#1397]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

It redirects to https://https//github.com/fossasia/susper.com

**Expected behavior:**

Should redirect to https://github.com/fossasia/susper.com

**Will work on the issue:**
Yes

**Comment by subhahu123** [comment]
@rajvaibhavdubey  please close this issue
