### ISSUE TITLE
Fixes in infobox

### ISSUE THREAD

**Issue by rajvaibhavdubey** [fossasia/susper.com#1399]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

There are a number of bugs in infobox
- The links should initially have a blue color and underline upon hover similar to google
- Include twitter and google icons near share to,  similar to google.

**Screenshots of the issue:**

![screenshot from 2019-01-10 00-08-25](https://user-images.githubusercontent.com/33062425/50920754-3d5c6680-146c-11e9-94df-dec37558fdac.png)

**Will work on the issue:**
Yes

**Comment by rajvaibhavdubey** [comment]
@subhahu123 I'm already working on this, and would like to submit a PR. You should ask before claiming an issue. :smile:

**Comment by subhahu123** [comment]
I will close this after knowing the error
