### ISSUE TITLE
Implement "Add Susper" to browser as search provider

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#14]
Implement support for browsers to add susper as the standard search engine as outlined here for example: https://support.mozilla.org/en-US/kb/add-or-remove-search-engine-firefox
- [ ] Create an OpenSearch XML file as specified on http://www.opensearch.org and http://mycroftproject.com/submitos.html
- [ ] Add a base 64 image encoding to xml
- [ ] Ensure implementation shows up as option to add search engine to browser

**Comment by nikhilrayaprolu** [comment]
Is it solved? @mariobehling

**Comment by mariobehling** [comment]
@nikhilrayaprolu Does not seem to work on Firefox.

![screenshot from 2016-12-12 09-51-20](https://cloud.githubusercontent.com/assets/1583873/21086606/9ece10a2-c050-11e6-8dcc-97b4dad3318a.png)

**Comment by adarsh-ideal** [comment]
@mariobehling Implement "Add Susper" to browser as search provider.

**Comment by mariobehling** [comment]
@adarsh-ideal Very good. 

Please use a logo that is closer to Susper.com instead of Yacy. Thank you.

**Comment by adarsh-ideal** [comment]
@mariobehling Changed the logo. Please check the preview.
And review the Pull request.

**Comment by adarsh-ideal** [comment]
@mariobehling Is this working, if not I may need to change path for xml a little bit to work on domain registered for susper.

**Comment by adarsh-ideal** [comment]
@mariobehling Done sir! Now this will work. Please merge the review and merge the PR.
Also check the preview at: https://adarsh-ideal.github.io/susper.com/
