### ISSUE TITLE
Match the search box position, design, width, height, font and submenu to the search box of market leader

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#142]
Let's make the design around the search pages closer to the market leader.

![screenshot from 2017-03-30 19-50-58](https://cloud.githubusercontent.com/assets/1583873/24529585/dddf2772-1582-11e7-8207-ce6f56e324c0.png)

![screenshot from 2017-03-30 19-54-11](https://cloud.githubusercontent.com/assets/1583873/24529592/e25491c0-1582-11e7-9058-b51da09aa133.png)

Please adapt the following:
* [ ] search box position
* [ ] search button
* [ ] design
* [ ] width
* [ ] height
* [ ] font and font size in search box
* [ ] sub menu
* [ ] adjust the position "Tools" to match the sample service

**Comment by harshit98** [comment]
@mariobehling What changes we have to do in sub-menu? Do we have to add other headings too like `News`, `Maps` other than adjusting position of "Tools" ?

**Comment by mariobehling** [comment]
> What changes we have to do in sub-menu? 

Check distance to box and alignment.

> Do we have to add other headings too like News, Maps other than adjusting position of "Tools" ?

Please stick to the issue. It is important, but not part of the issue.

**Comment by harshit98** [comment]
Working on this issue! :+1:
