### ISSUE TITLE
Match the design of the bottom page number menu closer to the market leader and avoid borders

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#143]
Please make the design to match the market leader

* Ensure font, color and size are same
* Ensure distance between number is the same
* Ensure position is the same

![screenshot from 2017-03-30 20-16-51](https://cloud.githubusercontent.com/assets/1583873/24530073/f3f98388-1585-11e7-90cf-4c8be3871e1a.png)

**Comment by 13nehu** [comment]
![demo](https://cloud.githubusercontent.com/assets/17461330/24916384/98fbc538-1ef7-11e7-9642-000785d30e19.jpg)

**Comment by 13nehu** [comment]
#156

**Comment by harshit98** [comment]
We can close this issue, it has been fixed.

**Comment by nikhilrayaprolu** [comment]
closing this issue as it is already solved at https://github.com/fossasia/susper.com/pull/156
