### ISSUE TITLE
Create a bottom bar in gray same as loklak.net

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#144]
Example bar of loklak.net
![screenshot from 2017-03-30 20-19-04](https://cloud.githubusercontent.com/assets/1583873/24530114/3014dca0-1586-11e7-8bde-97bbc1947b20.png)

Left side links:
* About -> `/about`
* Blog -> `blog.fossasia.org`
* Code -> `https://github.com/fossasia/susper.com`

Right side links
* Terms -> `/terms`
* Contact -> /`contact`

**Comment by harshit98** [comment]
@mariobehling The float box will overlap the contents on the right-side bottom. (right side links)

![selection_049](https://cloud.githubusercontent.com/assets/22245418/24596711/a5264f9e-185e-11e7-8eb3-a764cd3791b5.png)

**Comment by mariobehling** [comment]
> float box will overlap

Please ensure it does not.

**Comment by mariobehling** [comment]
Please match height of bottom bar and font to loklak.net. Only show "About" instead of "About Susper".

**Comment by mariobehling** [comment]
Also ensure bottom bar shows up on all pages.

**Comment by mariobehling** [comment]
Please ensure all menu items of the bottom bar have the same font and size.

**Comment by 13nehu** [comment]
#160
