### ISSUE TITLE
Remove unused  imports from components and services

### ISSUE THREAD

**Issue by subhahu123** [fossasia/susper.com#1465]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

Currently , In some components and services , there are some unusable imports which is not used anywhere in those files. we should remove them they are not useful .

**Will work on the issue:**
yes

**Comment by praveenojha33** [comment]
Please write a proper issue message so that everyone can understand about the issue.

**Comment by subhahu123** [comment]
@praveenojha33  please review https://github.com/fossasia/susper.com/pull/1472
