### ISSUE TITLE
Unable to open service box on top right on development branch.

### ISSUE THREAD

**Issue by praveenojha33** [fossasia/susper.com#1473]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
Service box do not open on susper-dev.herokuapp.com .
**Expected behavior:**
It should open.

**Comment by subhahu123** [comment]
@praveenojha33  everything is fine expect click event on service box is not working properly 
clicking is not toggling the display :   values liKe ( none to grd or etc )

**Comment by subhahu123** [comment]
@praveenojha33  also the setting on the bottom its dropdown is also not working same problem 
please update your issue with settings link also

**Comment by subhahu123** [comment]
@praveenojha33  got the fix
