### ISSUE TITLE
UPDATE ngrx to latest version compatible with angular  ( GSOC )

### ISSUE THREAD

**Issue by subhahu123** [fossasia/susper.com#1478]
**I'm submitting a ...**
- [ ] bug report
- [ ] feature request

**Current behavior:**

**Expected behavior:**

**Screenshots of the issue:**

**Will work on the issue:**

**Comment by simsausaurabh** [comment]
Gets covered in the parent issue inferring the upgradation of Angular dependencies for SUSPER.
