### ISSUE TITLE
design change of susper

### ISSUE THREAD

**Issue by nikhilrayaprolu** [fossasia/susper.com#15]
implement susper ,similar to google. 

- [ ]     Implement a menu with tabs "All", "Images", "Videos" and "Search Tools"

   

- [ ]  On clicking "Search Tools" show submenus

        

- [ ] Below menu "All" show options

-  Sort by date

 

- All Results, File Types, Provider, Authors - with a dropdown menu that opens on scroll over and shows tick boxes

        

- [ ] Below Images show options

-             All Images, File Types (only show image file types here), Provider, Authors - with a dropdown menu that opens on scroll over and shows tick boxes

- [ ]         Below Videos show options

-             All Videos, File Types (only show video file types here), Provider, Authors - with a dropdown menu that opens on scroll over and shows tick boxes

![image](https://cloud.githubusercontent.com/assets/15216503/22293894/564d9c80-e337-11e6-913b-294be439acfe.png)

The goal would be to implement a design closer to google than to the old susper design with the sidebar.
more details can be found at 
https://github.com/fossasia/susper-backbone/issues/5

**Comment by nikhilrayaprolu** [comment]
@mariobehling can you add more details for this issue.

**Comment by Marauderer97** [comment]
@nikhilrayaprolu @mariobehling I would like to help with this

**Comment by mariobehling** [comment]
@nikhilrayaprolu Please follow the design of google.

**Comment by harshit98** [comment]
@nikhilrayaprolu close this too. : )
