### ISSUE TITLE
make a contact us page

### ISSUE THREAD

**Issue by isuruAb** [fossasia/susper.com#157]
i have added contact section in about page.there is a link to localhost:4200/contact . do we need another page for show contact details ?

**Comment by harshit98** [comment]
Regarding this feature, let's have @mariobehling opinion.

**Comment by mariobehling** [comment]
Please simply follow loklak.net for now. Cheers.

**Comment by isuruAb** [comment]
working on this 👍

**Comment by isuruAb** [comment]
#162  fixes this issue 👍
