### ISSUE TITLE
Start page blank

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#158]
After the last commits start page is blank.

**Comment by harshit98** [comment]
@mariobehling Can you provide a screenshot please? I'm not getting a blank page when I go to <a href="http://susper.com/">Susper</a>. Here is the latest screenshot -

![screenshot from 2017-04-14 14-24-44](https://cloud.githubusercontent.com/assets/22245418/25038810/2c150834-211e-11e7-9f1e-bb2b0969964a.png)

**Comment by mariobehling** [comment]
It is back. Not sure, what happened.
