### ISSUE TITLE
Update codecov.yml

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#161]
I was checking `codecov.yml` and found that it is invalid. Please update it. 

References -
- <a href="https://docs.codecov.io/v4.3.0/docs/codecov-yaml#section-validate-your-repository-yaml">About Codecov yaml</a>
- <a href="https://docs.codecov.io/v4.3.0/docs/coverage-configuration">Coverage configuration</a>

See also : #133 and #151 
This issue can also be referenced with #132 

NOTE - Almost majority of the work has been completed on codecov. Only 'generating coverage reports in comments' feature is left.

**Comment by daminisatya** [comment]
@harshit98  are you working on it?

**Comment by harshit98** [comment]
@daminisatya No, I'm not working on it. It would be great if you're interested to help. :smile:

**Comment by daminisatya** [comment]
@harshit98 Definitely. But first what do you intent to tell from this sentence? 

```I was checking codecov.yml and found that it is invalid```

**Comment by harshit98** [comment]
@daminisatya I meant that it needs to be configured. It has not been configured properly at present. :sweat_smile:

**Comment by sudheesh001** [comment]
We have a truckload of issues. It'd be more helpful to take ownership of something and fix it. The core team is busy with the gsoc deadlines and finalizing the students. 

@harshit98 thanks anyway for pointing it out, but please can you fix it? There are already too many notifications to deal with

**Comment by sudheesh001** [comment]
Also please tell what exactly is mis configured

**Comment by nikhilrayaprolu** [comment]
@sudheesh001 I will try looking into it and fix it.
