### ISSUE TITLE
More Info on "Terms"

### ISSUE THREAD

**Issue by daminisatya** [fossasia/susper.com#167]
Issue: Empty button with no action when clicked. Discussion required on what to add. 

![image](https://cloud.githubusercontent.com/assets/6227784/25266126/aab72ee6-268d-11e7-942f-4435fc419435.png)

@sudheesh001 Please help with the content.

**Comment by mariobehling** [comment]
Please re-use the terms from http://loklak.net/terms and substitute "loklak" with Susper. 

For the first line, please use:

"Thanks for using our products and services (“Services”). The Services are provided by the FOSSASIA community, mail address at 93 Mau Than, Can Tho City, Viet Nam."

**Comment by isuruAb** [comment]
may i build the terms page ?

**Comment by nikhilrayaprolu** [comment]
@isuruAb ok proceed to work on this.

**Comment by mariobehling** [comment]
@isuruAb Please match the location of the logo and the distance to left ride side same as loklak.net.

**Comment by mariobehling** [comment]
Also avoid reloading the whole service. Page loads very slowly. Please compare to loklak as well.
