### ISSUE TITLE
Rename angular branch to master

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#179]
The branch name angular is not according to best practices in the org. Please rename it to master.

Also change it in documentation.

**Comment by isuruAb** [comment]
working on this

**Comment by nikhilrayaprolu** [comment]
I will look through this.

**Comment by mariobehling** [comment]
@nikhilrayaprolu Thanks. Let's proceed.

**Comment by nikhilrayaprolu** [comment]
@mariobehling I have created a branch 'master', but I think we have to rename the branch 'angular' to 'development' instead of master, since all checks will be done on development branch rather than on a master branch.

**Comment by mariobehling** [comment]
At the beginning of projects master is sufficient. We will add dev branch later. 

Please fix documentation and help to get this project back on track. Lots of changes where not necessary recently, e.g. the splitting of the top bar and an unnecessary page preview.

If we want to make a simple and quick Open Source alternative to Google, Bing, Duckduckgo we need to follow market leaders first before we iterate. Please help to do this and strictly follow this goal and get back to only doing what is written in issues. Please help everyone to follow our best practices.

The other part is to improve the search results of Yacy. Michael is working on this as well.

**Comment by mariobehling** [comment]
And I don't have a clue why our master branch was named to angular in the first place and who did it. We are spending times on things that are not necessary. Please help to fix the split search result page as well and get all items on the page, that help users. Thanks.

**Comment by isuruAb** [comment]
@mariobehling  this issue should be closed
