### ISSUE TITLE
ngrx implementation for redux based architecture

### ISSUE THREAD

**Issue by nikhilrayaprolu** [fossasia/susper.com#18]
currently we have only one component for results page, but it is a bad practice to have a whole page as one component .subdividing the results component to subcomponents will lead to cross component communication, and extending susper in future would lead to many more cross component state dependencies.
so a solution to this is to implement redux based architecture for search results and any other cross dependencies in future.

**Comment by nikhilrayaprolu** [comment]
@hemantjadon what do you feel about storing search data in a store , since we would have a cross state dependencies on implementing subcomponents for sidebar and search results. Is it worth using a store for it . or input/output is enough?

**Comment by Marauderer97** [comment]
@nikhilrayaprolu There is another concern with regard to the component structure. As we extend susper and add an image view, video view etc, each view comes with its own sub-components such as pagination bar, or other search tools. We need to find a  maintainable and  extendable way of implementing this.

**Comment by nikhilrayaprolu** [comment]
@Marauderer97 I have implemented advanced tools using ngrx architecture,where I have created a store for search results you could look at the pull https://github.com/fossasia/susper.com/pull/52 and use it where ever you feel it can be incorporated.
