### ISSUE TITLE
Match bottom bar design and functionality to loklak.net

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#180]
* match height
* match design in small screens
* delete menu functionality in small screens and follow loklaks approach
* match font size to 13px

**Comment by Marauderer97** [comment]
![image](https://cloud.githubusercontent.com/assets/20185076/25754579/68698952-31dd-11e7-820f-3c95e9e25028.png)
@mariobehling Is this satisfactory. I had to do away with all the bootstrap classes and take the exact specifications from loklak's source code, to get the same design though..

**Comment by nikhilrayaprolu** [comment]
@Marauderer97 make a pull and discuss regarding your changes there. It gives everyone a choice to review your changes. :smile:
