### ISSUE TITLE
How can we get an info box on the right

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#181]
Duckduckgo and Google often show a sidebox with additional results mainly from Wikipedia. How can we get the same?

**Comment by isuruAb** [comment]
In google they show the  wikipedia answer when they got wikipedia as the top result like this.
<img width="1185" alt="screen shot 2017-04-26 at 5 39 52 pm" src="https://cloud.githubusercontent.com/assets/7692626/25433830/7d9b2fc0-2aa7-11e7-9466-4c989b68016a.png">

They show ticker details when they got yahoo finance as the top most result. like this.
<img width="1133" alt="screen shot 2017-04-26 at 5 39 23 pm" src="https://cloud.githubusercontent.com/assets/7692626/25433847/90a8bfce-2aa7-11e7-9df0-067e8f68c1dc.png">

**Comment by harshit98** [comment]
@isuruAb @mariobehling This feature is also called as - <a href="https://en.wikipedia.org/wiki/Knowledge_Graph">Knowledge Graph</a>. It will require some back-end work on YaCy too. It works with semantic search.

**Comment by nikhilrayaprolu** [comment]
@Orbiter  Can you help us on how we could bring this feature to live.

**Comment by Orbiter** [comment]
In case that the info is taken from the wikipedia, we can get structured data for wikipedia information from a dbpedia API:
https://github.com/dbpedia/lookup

for example: http://lookup.dbpedia.org/api/search/KeywordSearch?QueryClass=place&QueryString=berlin

We can try this API for the query string and if it returns any result, we render that at the right column.

**Comment by harshit98** [comment]
@Orbiter I'll go through the dbpedia API and try to implement the feature. It looks great!

**Comment by nikhilrayaprolu** [comment]
@Orbiter  but that's not the case we need. Google renders the information from various sources.It renders flight details from travel agency websites, It renders movie results from movie review sites and many more. this looks like a good NLP, ML stuff we could add as an extension into Yacy and could be a good interesting project under FOSSASIA.

**Comment by nikhilrayaprolu** [comment]
working on this issue.

**Comment by mariobehling** [comment]
Need to iterate more to add images and enhance design.
