### ISSUE TITLE
Ensure Logo and Search Bar are centered

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#182]
The start page shows a logo/bar that is not centered.

Expected: Elements should be centered.

**Comment by nikhilrayaprolu** [comment]
![image](https://cloud.githubusercontent.com/assets/15216503/25756675/4326a992-31e5-11e7-91be-3f41ae00750c.png)

looks like this problem exists on different screen sizes, may be a problem with responsive design.

**Comment by Marauderer97** [comment]
Yes, perhaps using percentages instead of pixels while positioning will solve this.

**Comment by harshit98** [comment]
Has someone started working on this issue?

**Comment by Marauderer97** [comment]
I will work on this :+1:

**Comment by mariobehling** [comment]
Issue still not solved.

**Comment by mariobehling** [comment]
See below.

![screenshot from 2017-05-09 18-30-21](https://cloud.githubusercontent.com/assets/1583873/25861669/b3a048f6-34e5-11e7-885f-8dcaa5a47b79.png)
