### ISSUE TITLE
Add feature "Make Standard Search Engine" to Front page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#183]
We already have a way to add susper as standard search engine to Firefox. Please implement the same for Chrome/Chromium.

![screenshot from 2017-04-28 04-56-22](https://cloud.githubusercontent.com/assets/1583873/25512622/6dbb5f0c-2bcf-11e7-8e90-38d5f2b00ab1.png)

**Comment by harshit98** [comment]
I would like to work on this feature. :+1:

**Comment by harshit98** [comment]
@nikhilrayaprolu How you have implemented the feature for Firefox?
