### ISSUE TITLE
Match Search site closer to market leader

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#184]
Let's work a bit on the side design.

* The logo width on the top of the page is slightly wider than at Google resulting in a larger empty left bar. Please match the logo width and decrease the side to match Google.
* The height of the gray top bar is bigger. Please make it smaller. Simply follow Google.
* The active submenu e.g. All, Images, Videos should be bold

![screenshot from 2017-04-28 05-11-35](https://cloud.githubusercontent.com/assets/1583873/25512864/2cfcece0-2bd1-11e7-8d25-5c6f4c11af9b.png)

**Comment by harshit98** [comment]
Working on this :+1:

**Comment by Marauderer97** [comment]
@harshit98 Can I know your progress? I am working on #232 which is very similar to this issue, and will cause us to over ride each other's work, let us coordinate to avoid that?

**Comment by harshit98** [comment]
@Marauderer97 Yes, I was thinking the same. Both are similar. You can proceed, I'll pick up another issue. :smile:
