### ISSUE TITLE
Make results more compact and match them with market leader

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#185]
Our current display of results looks as follows:
![screenshot from 2017-04-28 05-09-29](https://cloud.githubusercontent.com/assets/1583873/25512896/61c6ebf6-2bd1-11e7-803c-173ffbec5fac.png)

Please make it more compact and change as follows to match market leader:
* Use same font, color and font size
  * title
  * green link
  * description
* Reduce height after lines and match line spacing
* Move date to beginning of description followed by a dash "-*
* Show page titles only in the max width of the search bar and after that "..."
* Break description line automatically and use the width of the search bar

![screenshot from 2017-04-28 05-21-05](https://cloud.githubusercontent.com/assets/1583873/25513045/8111ee38-2bd2-11e7-90e9-8d642788c0e5.png)

**Comment by harshit98** [comment]
I would like to work on this. :+1:

**Comment by mariobehling** [comment]
Please match the line spacing and space after lines as well.

**Comment by harshit98** [comment]
@mariobehling done! We can close this issue now.
