### ISSUE TITLE
Bottom bar missing on search pages

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#187]
The bottom bar does not show up on search pages.

![screenshot from 2017-04-28 05-30-35](https://cloud.githubusercontent.com/assets/1583873/25513213/e7abe6d4-2bd3-11e7-9a33-fcd5bc502be3.png)

**Comment by isuruAb** [comment]
working on this

**Comment by mariobehling** [comment]
I made a mistake here. I should not have merged this. This is not the intended way. The bottom bar should show up on the bottom of pages. Please compare to other search engines. Keep the bar itself on the page, please.
