### ISSUE TITLE
Add bottom bar "related searches"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#188]
Google shows related searches on the bottom of the page. Please implement the same using Yacy. 

![screenshot from 2017-04-28 05-32-05](https://cloud.githubusercontent.com/assets/1583873/25513249/32ada62c-2bd4-11e7-9261-125c046da9a8.png)

@Orbiter Which API is required for that?

**Comment by nikhilrayaprolu** [comment]
@Orbiter  any suggestions for the API we could use or can this feature be added in backend if possible?

**Comment by Marauderer97** [comment]
Now that Related Searches has already been implemented in the Infobox, we can proceed on adding this feature just like the market leader, I would like to work on this.
