### ISSUE TITLE
Fix dialog to install susper.com as standard search

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#195]
![screenshot from 2017-05-01 16-39-58](https://cloud.githubusercontent.com/assets/1583873/25582321/ea48e552-2e8c-11e7-9fe3-e99c8828fe6b.png)

Instead of dialog "Make this the current search engine." use "Make Susper the standard search engine."

**Comment by harshit98** [comment]
@mariobehling I think it's a browser related issue. We can't do anything in this. It is being automatically generated by the browser.

**Comment by nikhilrayaprolu** [comment]
@mariobehling  yes, ItsI have checked with the susper.xml for instructing the browser, we don't have an option to edit It's directly generated by the browser.

**Comment by nikhilrayaprolu** [comment]
closing this issue since this is practically not possible to change a browser generated lines.
