### ISSUE TITLE
Search Page: Tools are showing off-screen

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#197]
Tools are showing off-screen.

Expected: Please compare to market leader and keep them in correct position.

![screenshot from 2017-05-01 16-48-24](https://cloud.githubusercontent.com/assets/1583873/25582573/4ab4bdde-2e8e-11e7-8ce5-de2a28f0b694.png)

**Comment by harshit98** [comment]
@mariobehling Tools is working fine.

![screenshot from 2017-05-01 21-20-40](https://cloud.githubusercontent.com/assets/22245418/25584565/31f0770e-2eb4-11e7-892c-0c7812a9229b.png)

**Comment by isuruAb** [comment]
@harshit98  It has that issue check susper.com

**Comment by harshit98** [comment]
@isuruAb Yes it is there. :+1:

**Comment by isuruAb** [comment]
@harshit98  are you working on this?

**Comment by nikhilrayaprolu** [comment]
any update upon this?

**Comment by harshit98** [comment]
@nikhilrayaprolu No work has been started on it.

**Comment by Marauderer97** [comment]
@nikhilrayaprolu @harshit98 Shall I go ahead and fix this? Or has someone started work?

**Comment by nikhilrayaprolu** [comment]
Ok go ahead @Marauderer97

**Comment by harshit98** [comment]
@Marauderer97 Yes, you can start with it.
