### ISSUE TITLE
Improve top menu on pages and add links

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#205]
Please match the design of pages like http://susper.com/about to http://loklak.net/about and:
* add top menu links (Home, About, Contact) to the following pages: Terms, About, Contact
* Align logo and text on these pages same as loklak.net
* Ensure you keep same distance to left and right as loklak.net

**Comment by harshit98** [comment]
I would like to work on this issue. :+1:

**Comment by mariobehling** [comment]
Top menu links on right still missing on contact and terms page.

**Comment by harshit98** [comment]
@mariobehling ok. Working on it. :+1:
