### ISSUE TITLE
Footer-navbar should be shown below while web search query.

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#206]
At present, while performing a web search query the footer navbar should be at bottom of the page just like loklak-search.

![screenshot from 2017-05-04 00-27-56](https://cloud.githubusercontent.com/assets/22245418/25676763/e0e1535c-3060-11e7-8c95-8b159111b52a.png)

comparison with loklak search -

![screenshot from 2017-05-04 00-28-18](https://cloud.githubusercontent.com/assets/22245418/25676766/e2068dce-3060-11e7-8fa7-11d5ea1046db.png)

**Comment by nikhilrayaprolu** [comment]
Okay, I am working on this.

**Comment by mariobehling** [comment]
There is a line in the middle of the bar after the last commit. Please take out any lines and ensure you match the height to the market leader (Google).

**Comment by Marauderer97** [comment]
@nikhilrayaprolu Also please check the position of the bar on the index page.

**Comment by nikhilrayaprolu** [comment]
that was due to a recent pull you made with the design changes which caused the issue. I have reverted them back, review the pull :smile:

**Comment by nikhilrayaprolu** [comment]
issue is solved in #229
