### ISSUE TITLE
Under 'images' section, pagination bar is not appearing.

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#207]
Due to some recent fix of issue regarding the footer-navbar, in the images section pagination bar is not appearing. 

![selection_004](https://cloud.githubusercontent.com/assets/22245418/25677148/7c2934dc-3062-11e7-9d46-9f97fa85a077.png)

It appears somewhere in the middle of the images -

![selection_005](https://cloud.githubusercontent.com/assets/22245418/25677241/d386870c-3062-11e7-983f-5370f634dfee.png)

**Comment by isuruAb** [comment]
working on this

**Comment by harshit98** [comment]
@isuruAb Your status? Have you started working on this?
