### ISSUE TITLE
Search bar and default box overlaps each other. 

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#214]
Here is the screenshot of it - 

![a5db9208-3246-11e7-8088-d9717301493b](https://cloud.githubusercontent.com/assets/22245418/25770755/a1fc4938-325b-11e7-8062-0b8722b77a08.png)

**Comment by harshit98** [comment]
@Marauderer97 I think this issue has been solved in the another pull request. Am I right? :smile:

**Comment by Marauderer97** [comment]
@harshit98 are you sure? I still the problem persists on small screen sizes?

**Comment by harshit98** [comment]
@Marauderer97 I commented on this issue before you open PR #236 . Looks like it is not solved yet.

**Comment by Marauderer97** [comment]
@harshit98 I will work on this
