### ISSUE TITLE
Match the design and functionality of the top bar of market leader

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#232]
* match design and height
* match size and position of logo
* match size and position of search bar
* match secondary menu
* match all other elements

![screenshot from 2017-05-07 20-22-51](https://cloud.githubusercontent.com/assets/1583873/25783841/2a72a304-3363-11e7-9f3e-d614c526ad4d.png)

**Comment by Marauderer97** [comment]
Working on this :+1:

**Comment by Marauderer97** [comment]
@mariobehling Would you prefer having the menus and submenus match google exactly? In that case, we will have a lot of dead links, say for News, or Settings, Shopping and so on. @nikhilrayaprolu @harshit98 @isuruAb What do you think?

**Comment by harshit98** [comment]
@Marauderer97 I think we should focus on the features and current issue. There is no need to add news, settings, shopping and so on. Currently, we have a 'All', 'Images' and 'Videos' section. We should keep working with them only. :+1: :smile:

**Comment by harshit98** [comment]
We can close this issue now, as it has been solved as mentioned above.
