### ISSUE TITLE
z-index should be changed in footer navigation bar on home page

### ISSUE THREAD

**Issue by isuruAb** [fossasia/susper.com#239]
<img width="1280" alt="screen shot 2017-05-09 at 12 02 52 pm" src="https://cloud.githubusercontent.com/assets/7692626/25838322/2a5ce5b6-34b0-11e7-961e-3efd67da1517.png">

**Comment by harshit98** [comment]
Working on this. :+1:

**Comment by Marauderer97** [comment]
@harshit98 Please find another way of fixing this, and also provide a test link

**Comment by harshit98** [comment]
@Marauderer97 Okay, working on this. It will be deployed when I'll open a PR.
