### ISSUE TITLE
Fix the footer-navbar for the results section.

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#244]
Whenever the results are less in number, the footer moves away from its position and leaves the space at bottom of the page. Here is the screenshot of the following bug, which seems to happen under videos section - 

![selection_012](https://cloud.githubusercontent.com/assets/22245418/25856638/3bb14052-34f4-11e7-807e-012396fdb019.png)

**Comment by harshit98** [comment]
Please reopen this issue. Due to recent merge of #255 , this problem is again occurring.

**Comment by nikhilrayaprolu** [comment]
The position attributes should be independent of the child component I inherit, they should depend only on parent component. when I use the same component in other parent components, I should not have any internal css factors of the child component affecting the position in the parent component, there should be independency to apply my own css  in each parent component I inherit this. so where ever you want to fix the component as fixed , write this css only in the parent component but not in the child component, such that we could have other positions defined in other parent components.

**Comment by nikhilrayaprolu** [comment]
I am reopening this issue but implement CSS for external behaviour outside the child component (here fixing for "results" section, so make it fixed in "results component" but not in child component.
