### ISSUE TITLE
Images in Susper not clickable

### ISSUE THREAD

**Issue by Marauderer97** [fossasia/susper.com#252]
![image](https://cloud.githubusercontent.com/assets/20185076/25897593/28db78e6-35a6-11e7-9fbb-7016b4df52ca.png)
Clicking on an image in Google, opens the image link, but in susper, we can only view the images and not click on them.

**Comment by mariobehling** [comment]
I know there are different Google Search versions deployed in different countries, but usually I see first an expansion and then when I click the image open in a new tab.

So before the complete idea gets implemented, I suggest that you start with that feature and implement opening in a new tab.

See screenshot below.
![screenshot from 2017-05-10 15-01-23](https://cloud.githubusercontent.com/assets/1583873/25899808/8f87046c-3591-11e7-9fcd-bf3cc22ef018.png)
