### ISSUE TITLE
Results of actual search term are not shown, temporary results persist

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#256]
When a user types search, there is a search performed while typing. The search results that are often shown do not always reflect the final search term, they show a result that appeared while the user was typing it in.

Expected: Please make this feature closer to Google. There is a dropdown auto-completion. Enhance the way the outcome is displayed to match that of Google.

![screenshot from 2017-05-10 16-32-29](https://cloud.githubusercontent.com/assets/1583873/25904178/c377c114-359e-11e7-8bf9-d30f55e942bf.png)
This screenshot shows results for the letter "S" even though the search term was "Susper". It is also shown in the URL, however, it did not result in the search term results that are expected.

**Comment by nikhilrayaprolu** [comment]
working on this issue
