### ISSUE TITLE
Search bar overlaps logo at certain sizes

### ISSUE THREAD

**Issue by Marauderer97** [fossasia/susper.com#258]
The search bar and logo overlap need to be prevented, at certain screen sizes as shown
![image](https://cloud.githubusercontent.com/assets/20185076/25908592/31f13a48-35c8-11e7-815b-65c7c2872cbc.png)

**Comment by daminisatya** [comment]
What screen size did you observe this?

**Comment by harshit98** [comment]
@daminisatya This issue is with screen size `900x600`
