### ISSUE TITLE
Align the rendered images under 'images section' following the market leader

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#261]
Image search in susper - 

![selection_036](https://cloud.githubusercontent.com/assets/22245418/25911061/1f8b5c82-35d0-11e7-93ff-8fb6ec212618.png)

Image search in Google - 

![selection_037](https://cloud.githubusercontent.com/assets/22245418/25911079/2d02c224-35d0-11e7-89fb-90553cd034e4.png)

**Comment by Marauderer97** [comment]
@harshit98 Are you working on this? Have you already made some progress considering you have been working on #147 for the past few days?

**Comment by harshit98** [comment]
@Marauderer97 I'm working on this. :+1:
