### ISSUE TITLE
Render images covering up the empty spaces, following the market leader.

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#268]
Current condition of Susper after fix of alignment of images : 

![selection_023](https://cloud.githubusercontent.com/assets/22245418/25948308/82084500-3670-11e7-8136-b0bd50018243.png)
 Rendered images should fill up the white spaces on left and right side as shown in screenshot. Follow the market leader design.

This is how Google looks : 

![selection_024](https://cloud.githubusercontent.com/assets/22245418/25948318/8f4c2e0c-3670-11e7-9965-053f56ea07e7.png)

**Comment by nikhilrayaprolu** [comment]
there is no fixed rule such on google.it depends on image sizes
![image](https://cloud.githubusercontent.com/assets/15216503/25954324/900542da-3683-11e7-8703-3f757582b973.png)

**Comment by harshit98** [comment]
@nikhilrayaprolu But, what I'm trying to say is to cover up the empty spaces. : )

**Comment by nikhilrayaprolu** [comment]
change the title it is confusing others.
