### ISSUE TITLE
Discuss themability implementation in susper

### ISSUE THREAD

**Issue by nikhilrayaprolu** [fossasia/susper.com#269]
On gitter, we had a discussion on implementation of themability. thereby we could give users an option to choose a theme from.
So whatever discussion regarding it, let us have it here.
- how we could implement themability?
- which themes shall we implement?
- does google has themability?If so what themes is it using?

**Comment by Marauderer97** [comment]
@nikhilrayaprolu This seems like a very exciting feature. A few points,

- Many websites implement themes in the form of colors alone, changing the core color of the website (for example currently Susper's is blue, loklak's is pink)

- I have been looking at how Google does this, well it does not simply implement different colors, it implements an entire theme, say sunset or iceberg [Check this link out](https://chrome.google.com/webstore/category/themes) , and then allows the user to buy/ obtain for free these themes from its store.

- What themes do we implement? The most popular choices seem to be sunrise/sunset, nightsky, moon, galaxy etc. We will need to change the background image and the font-colors mainly

**Comment by harshit98** [comment]
Some few points from my side : 

- Well the idea is great! Let's keep it a bit simple. We can also implement the themes in the form of colors alone like Dark theme and Light theme.

- Check https://duckduckgo.com/ . They have kept it so simple by allowing users to choose between Dark theme and Light theme providing different fonts.

**Comment by nikhilrayaprolu** [comment]
@mariobehling what do  you expect from us? a complete image based themes google gives in chrome (or) a simple white/dark theme as in duckduckgo?
According to me, I think it's better to build a framework that supports all features and then extend it with the addition of new themes.

**Comment by nikhilrayaprolu** [comment]
On a research online on how to implement the themability I came across the following links (sharing these  so that others could have a look through it)
http://stackoverflow.com/questions/8796107/how-to-make-changeable-themes-using-css-and-javascript
https://www.thesitewizard.com/css/switch-alternate-css-styles.shtml
which requires us to remove the inline css we have till now
and then modify them with different combinations of css settings.


or since we had a discussion on using angular material far before that could make us easier to use multiple themes since angular material has support to multiple themes.(but this is a huge step to transport a project from one framework to the other)
https://github.com/angular/material2/blob/master/guides/theming.md

which one do you prefer?

**Comment by harshit98** [comment]
@nikhilrayaprolu Seems to be interesting. We should proceed with the first solution. Yes, I agree with you if we move to angular material it will be a huge step. Already we have worked a lot on front-end and finished the front-end small issues without using angular material.

**Comment by harshit98** [comment]
@nikhilrayaprolu @Marauderer97 I'll create a PR for this issue today. From there, we can start adding different kind of themes to susper.

**Comment by harshit98** [comment]
We can add more themes by adding them in `customize.component.ts` following the pattern. I have also found another idea of adding themes - https://embed.plnkr.co/PX1kcJAbNmBxTZmAzsiS/

**Comment by Marauderer97** [comment]
Duckduck go implements the following themes, we can follow lead
![image](https://cloud.githubusercontent.com/assets/20185076/26824123/b9bd3d40-4acd-11e7-9e6f-5ac396846fc8.png)

**Comment by harshit98** [comment]
Yes, @Marauderer97 but the issue is :
- We'll be changing the whole theme of results component. This can only be done with the help of css. How should be dynamically load it ? Previously, I did some work on it #333 Is there any other idea how we are going to work on this ?
- The theme feature should only be for applicable for results page ? Or other pages as well like, Advanced search, Crawl page (which is being implemented at present)

**Comment by Marauderer97** [comment]
@harshit98 Perhaps we can begin with results component as of now, and then extend it as required?

**Comment by praveenojha33** [comment]
Themes have been implemented.
