### ISSUE TITLE
implement search settings similar to google

### ISSUE THREAD

**Issue by nikhilrayaprolu** [fossasia/susper.com#270]
![image](https://cloud.githubusercontent.com/assets/15216503/25955927/184b3a7e-3688-11e7-8222-7435fb80838c.png)

we could increase the number of results and also restrict our instant view of results.

**Comment by harshit98** [comment]
@nikhilrayaprolu How should we start working on this step-by-step ?

**Comment by nikhilrayaprolu** [comment]
I am presently making a component for this page.once that is done we will get a clear idea on how to move forward.
1.create a separate component for this page
2.implement each feature depending on its functionality.

**Comment by harshit98** [comment]
I think we can close this issue now. @nikhilrayaprolu
