### ISSUE TITLE
Searching for a keyword shows - 'loading'

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#279]
![selection_028](https://cloud.githubusercontent.com/assets/22245418/26024324/cae2307e-37ec-11e7-8d5d-0ee3c5cd9e43.png)

`loading...` should not be there whenever a search action is implemented.

**Comment by Marauderer97** [comment]
@harshit98 Can you be more specific about the query please? I don't understand the issue, to be honest. The progress bar initially shows loading, and once the results are available, they are displayed
![image](https://cloud.githubusercontent.com/assets/20185076/26033126/0d11202e-38c2-11e7-9080-0a0f9d350774.png)
The `loading...` message was kept in accordance to the original design of susper.com(when it was written in javascript)

**Comment by harshit98** [comment]
@Marauderer97 Yes, that is the issue the progress bar initially shows `loading...`.

**Comment by Marauderer97** [comment]
@mariobehling What do you suggest? Should we remove the `loading...` message

**Comment by harshit98** [comment]
@Marauderer97 It is the same issue which we solved earlier. Here #48 
I'm working on this. :+1: : )
