### ISSUE TITLE
Links in menu redundant

### ISSUE THREAD

**Issue by Marauderer97** [fossasia/susper.com#284]
The links on clicking the burger icon, seem to be redundant and duplicate
![image](https://cloud.githubusercontent.com/assets/20185076/26033137/72d94d82-38c2-11e7-98ee-03e5ab22157c.png)
Both code and github lead to the same page. At the same time links like about, or advanced search are missing from it. 

@nikhilrayaprolu @harshit98 If you agree, I can start working on this

**Comment by nikhilrayaprolu** [comment]
ok. you can work on this pull. @Marauderer97
