### ISSUE TITLE
SUSPER symbol is overlapped by "About This Search Portal"

### ISSUE THREAD

**Issue by ragnerok** [fossasia/susper.com#29]
When the '?' icon is clicked About this Search Portal overlaps SUSPER symbol   
here - http://susper.com/yacysearch/about.html   
  
This seems like a design error to me so I reported it

**Comment by ragnerok** [comment]
So what should I do to tackle this ? 
Should I shift "About this search portal" to the centre or should I shift it downwards ?

**Comment by mariobehling** [comment]
Please follow the design of Google and adapt sizes to Google search theme.

**Comment by ragnerok** [comment]
I think someone has already made a PR with this issue #33
