### ISSUE TITLE
Initial gap in every image search

### ISSUE THREAD

**Issue by nikhilrayaprolu** [fossasia/susper.com#291]
![image](https://cloud.githubusercontent.com/assets/15216503/26120189/80ffaa42-3a8d-11e7-94dc-e8a361aa5063.png)

![image](https://cloud.githubusercontent.com/assets/15216503/26120228/a658cb5c-3a8d-11e7-8302-2ed8dc23ffb5.png)

![image](https://cloud.githubusercontent.com/assets/15216503/26120249/b14d474a-3a8d-11e7-9e24-f7cb7c03c9f5.png)

there is some fixed length of gap for each image search, which needs to be removed

**Comment by Marauderer97** [comment]
@nikhilrayaprolu Yes, PR #273 Must have caused this, since this problem arose only now, look:
![image](https://cloud.githubusercontent.com/assets/20185076/26124812/74b18232-3a9d-11e7-84be-0c0275e1b1ba.png)
Looking into it
