### ISSUE TITLE
Add more tests

### ISSUE THREAD

**Issue by nikhilrayaprolu** [fossasia/susper.com#3]
this is an evolutionary issue. and one could start by contributing the tests to those functions not covered in the test suite .
addition of the code coverage tools could also be done.

**Comment by yasirunilan** [comment]
Can I work on this one?

**Comment by nikhilrayaprolu** [comment]
@yasirunilan you can proceed.

**Comment by nikhilrayaprolu** [comment]
@yasirunilan any updates regarding this?

**Comment by yasirunilan** [comment]
@nikhilrayaprolu not yet started

**Comment by harshit98** [comment]
@nikhilrayaprolu Not able to understand. We have added Travis CI to test the code quality. Should we have to add codecov also?

**Comment by nikhilrayaprolu** [comment]
@harshit98 here you have to write unittests covering  the functions or views of each component, (as many as you can)  . so that we wont be breaking the code in future .
every component has a separate <component-name>.spec.ts which could be updated with new test cases.
secondly end to end tests can be added in this folder https://github.com/fossasia/susper.com/tree/angular/e2e
you could start picking up component by component and add unittests covering major parts of the component.

**Comment by harshit98** [comment]
@nikhilrayaprolu I would like to take some time on this. First I have to read docs. :p Can you refer me some links or solved issues related to it? Your suggestions are welcomed :)

**Comment by nikhilrayaprolu** [comment]
@harshit98 you could learn it from https://angular.io/docs/ts/latest/guide/testing.html offficial docs of angular , also there are some articles on medium and range.io , which are good to read.

**Comment by harshit98** [comment]
@nikhilrayaprolu I would like to do this.

**Comment by nikhilrayaprolu** [comment]
ok you could start working on this @harshit98 .

**Comment by nikhilrayaprolu** [comment]
need to add more tests.

**Comment by harshit98** [comment]
@nikhilrayaprolu Tests has to be re-written. Right now, to pass tests we are like adding each and every module in every `.spec.ts` file. This should not be happening.

**Comment by nikhilrayaprolu** [comment]
we don't need to add each and every module in every spec file. just the dependencies of the tests will be imported.

**Comment by harshit98** [comment]
Tests for following components and services needs to be added : 
- [ ] About Component
- [ ] Advanced search component 
- [ ] Auto complete component 
- [ ] Contact component
- [ ] Footer-navbar component
- [ ] Index component
- [ ] Infobox component
- [ ] Navbar component 
- [ ] New advanced search component
- [ ] Not found component 
- [ ] Related search component 
- [ ] Results component
- [ ] Search bar component 
- [ ] Terms component 
- [ ] Theme component

Services : 
- [ ] Search service
- [ ] Theme service
- [ ] Knowledge service
- [ ] Autocomplete service 

If test suites for reducers and effects has to be written kindly mention them in this issue. :)

**Comment by nikhilrayaprolu** [comment]
@harshit98  There is no use in writing tests which don't fail. write test cases which fail mostly when something wrong is done.
for instance: - we see these errors images not showing up, videos not showing the correct results type of errors regularly on susper. why not write test cases for such type of use cases?
For now write a test case that takes care of errors related to https://github.com/fossasia/susper.com/issues/464 , https://github.com/fossasia/susper.com/issues/460 and https://github.com/fossasia/susper.com/issues/459 https://github.com/fossasia/susper.com/issues/449 so that we don't get these errors in susper again and we could catch this type of errors on before hand.

**Comment by harshit98** [comment]
@nikhilrayaprolu Okay I got it. :+1: I was going to add them in results component spec file. But I thought, to write component wise tests.

**Comment by nikhilrayaprolu** [comment]
listing down extra issues which are found repetitive, been fixed several times but raised again and need a permanent fix by writing tests.

- [ ] #464 

- [ ] #460 

- [ ] #459 

- [ ] #449 

- [ ] #490 

- [ ] #491 

let us write these tests so that these issues doesn't get raised again.

**Comment by harshit98** [comment]
@nikhilrayaprolu @Marauderer97 

I have found a solution to solve CSS issues. This is called visual regression. 
https://css-tricks.com/automating-css-regression-testing/
