### ISSUE TITLE
Links in Info-box 

### ISSUE THREAD

**Issue by Marauderer97** [fossasia/susper.com#305]
The links in the info box on being clicked give a 404 error.
This has also been mentioned in PR #298 
![image](https://cloud.githubusercontent.com/assets/20185076/26276115/98242262-3d8e-11e7-8227-5cda9e52c5d6.png)
![image](https://cloud.githubusercontent.com/assets/20185076/26276118/a1ddad0a-3d8e-11e7-9039-7d7dbc27dc12.png)

**Comment by nikhilrayaprolu** [comment]
Making a pr on this
