### ISSUE TITLE
infobox not getting displayed

### ISSUE THREAD

**Issue by nikhilrayaprolu** [fossasia/susper.com#308]
![image](https://cloud.githubusercontent.com/assets/15216503/26283634/cf0d52ec-3e49-11e7-940d-f3325afaf48c.png)

infobox isn't displaying.

**Comment by nikhilrayaprolu** [comment]
this is because there is some problem from the dbpedia side 
![image](https://cloud.githubusercontent.com/assets/15216503/26283737/38aaaa78-3e4b-11e7-9104-5b31bf65b0ac.png)

if this problem persists even tomorrow ,I think we have to reach out dbpedia.

**Comment by harshit98** [comment]
Yes, @nikhilrayaprolu I was thinking the same. Must be an issue with an API. : )

**Comment by harshit98** [comment]
@nikhilrayaprolu It's working now. It was problem from dbpedia side. We can close this issue now.
