### ISSUE TITLE
Search type buttons not aligned with searchbar

### ISSUE THREAD

**Issue by AnshulMalik** [fossasia/susper.com#319]
The `All`, `Images`, `Video` button container should be aligned with searchbar.

Current:
![a](https://cloud.githubusercontent.com/assets/7821757/26286471/0677f914-3e84-11e7-9236-e55674da801e.png)

Expected:
![b](https://cloud.githubusercontent.com/assets/7821757/26286483/66b88fbe-3e84-11e7-9a57-f2aac362db32.png)

**Comment by harshit98** [comment]
Working on this.
