### ISSUE TITLE
Gap between search option buttons and container bottom

### ISSUE THREAD

**Issue by AnshulMalik** [fossasia/susper.com#320]
It'll look better if there is no gap, the blue bottom border touches the bottom.

Current:
![b](https://cloud.githubusercontent.com/assets/7821757/26286498/cca0399e-3e84-11e7-9465-fcf361568a15.png)

Expected:
![c](https://cloud.githubusercontent.com/assets/7821757/26286509/eb16e184-3e84-11e7-9bcc-5e90a4829c6b.png)

**Comment by harshit98** [comment]
Working on this.
