### ISSUE TITLE
Fix required to align the text properly

### ISSUE THREAD

**Issue by daminisatya** [fossasia/susper.com#321]
Either we can think of increasing the width of the drop down box and making the text sit in a single line. 

![image](https://cloud.githubusercontent.com/assets/6227784/26292173/5b898a7e-3ed1-11e7-8ede-a0b55ba59873.png)

**Comment by Marauderer97** [comment]
@daminisatya I think increasing the width will be a good idea. Can I work on this?

**Comment by daminisatya** [comment]
@Marauderer97 Sure!
