### ISSUE TITLE
Hide search box in title bar in index page

### ISSUE THREAD

**Issue by Marauderer97** [fossasia/susper.com#33]
The index page having two search bars is redundant. The search bar in the title bar needs to be hidden in the index page and displayed only in the search page.
![image](https://cloud.githubusercontent.com/assets/20185076/22467023/ef637e70-e7e8-11e6-8736-5ad4ddbeef35.png)

**Comment by mariobehling** [comment]
Please implement same as in Google.com. Also ensure search bar etc. look similar.

**Comment by BhaveshSGupta** [comment]
this seems done but I guess we should hide the logo at top left corner there is no meaning of having two logo's.

**Comment by harshit98** [comment]
@BhaveshSGupta I agree with you. Is anyone assigned for this issue?

**Comment by BhaveshSGupta** [comment]
I can try this out tomorrow..

**Comment by Marauderer97** [comment]
@BhaveshSGupta This issue has already been fixed. :smile: 
This is how Susper looks currently:
![image](https://cloud.githubusercontent.com/assets/20185076/22825680/b91ba012-efb4-11e6-9763-71271b1df8b8.png)
