### ISSUE TITLE
Obsolete Installation guide

### ISSUE THREAD

**Issue by sharang108** [fossasia/susper.com#330]
A problem with Installation guide in readme, the angular-cli installation package is updated for more details please read  [npm-angular](https://www.npmjs.com/package/@angular/cli), and [StackOverflow](https://stackoverflow.com/a/42452061).

Related [PR](https://github.com/fossasia/susper.com/pull/329#issuecomment-303280445)

**Comment by harshit98** [comment]
This issue can be closed now.
