### ISSUE TITLE
Add "About" page

### ISSUE THREAD

**Issue by Marauderer97** [fossasia/susper.com#34]
Clicking on About this page under the help icon gives a 404 error.
![image](https://cloud.githubusercontent.com/assets/20185076/22467198/aacc17e4-e7e9-11e6-90e2-9e34e66b5e4f.png)

**Comment by mariobehling** [comment]
Yes, we need an about page, but rather follow the google.com design not the old susper site.

**Comment by Marauderer97** [comment]
This is a sub-issue of #45, where all the links will be updated(not just the about page). Hence closing the issue.
