### ISSUE TITLE
removing the search text entered makes the results empty but not the info box

### ISSUE THREAD

**Issue by nikhilrayaprolu** [fossasia/susper.com#342]
![image](https://cloud.githubusercontent.com/assets/15216503/26440310/54581476-4149-11e7-9087-2b91d5635c7f.png)

when we search something and remove the search text from the search bar, info box doesn't get disappeared.

**Comment by Marauderer97** [comment]
@nikhilrayaprolu  Let us just add related searches here, since both use a very similar mechanism?
