### ISSUE TITLE
removing the search text entered makes the results empty but not the related searches

### ISSUE THREAD

**Issue by nikhilrayaprolu** [fossasia/susper.com#343]
![image](https://cloud.githubusercontent.com/assets/15216503/26440430/e3fa8f96-4149-11e7-8085-314305d95056.png)

when we search something and remove the search text from the search bar, related searches doesn't get disappeared.

**Comment by Marauderer97** [comment]
Duplicate issue #342

**Comment by nikhilrayaprolu** [comment]
this is related to related searches and not the info box, since infobox and the related searches are different components.
