### ISSUE TITLE
Problem in search results, no hyperlinks displayed. 

### ISSUE THREAD

**Issue by troublemagnet** [fossasia/susper.com#348]
For certain search queries, the results displayed contain no hyperlink to click on but read only links.
![issue](https://cloud.githubusercontent.com/assets/28952053/26450312/7b3a2266-4174-11e7-9a75-eeb8a4afd7fc.png)

**Comment by harshit98** [comment]
@troublemagnet This is maybe due to server. Also, the links you're saying are of format `.jpg`. So they are being displayed in images section.

**Comment by troublemagnet** [comment]
@harshit98 Yes, that's true. But shouldn't they only be displayed in images section? That's what should ideally happen, don't you think so?

**Comment by harshit98** [comment]
Working on this issue.

**Comment by harshit98** [comment]
@nikhilrayaprolu In results-component file, there is already code filtering out png files and avi files. But if I try to filter png with jpg too, the issue seems to be remain there.

**Comment by nikhilrayaprolu** [comment]
@harshit98  could you reference the line where you found filtering of png and  avi.
and secondly can I have an example query that would reproduce this error.

**Comment by harshit98** [comment]
Error was reproduced by entering query `hello` . But looks like server update has solved the issue.

**Comment by harshit98** [comment]
@nikhilrayaprolu Line 120 in `results.component.ts` there I tried to filter out file formats for images.

**Comment by nikhilrayaprolu** [comment]
that line actually gets called only when images tab is active, so we don't have any such lines which actually excludes images in "all" tab. to solve this issue, we actually have to remove images and videos from getting displayed on the tab.

**Comment by harshit98** [comment]
>  we actually have to remove images and videos from getting displayed on the tab.

Do you mean to create separate component for them ? Or just filter the `png` and `jpg` format from 'all' tabs?

**Comment by nikhilrayaprolu** [comment]
I mean we should remove them from all tab.
that is just filter png and jpg format from "all" tabs.

**Comment by harshit98** [comment]
This issue can be closed, since it was a server issue. Now it looks to be solved. :+1:
