### ISSUE TITLE
Problems with the pagination bar

### ISSUE THREAD

**Issue by Marauderer97** [fossasia/susper.com#35]
The pagination bar has the following two problems

1. The next and previous only update the pagination bar, not the entire page
2. Its functionality for images is unclear, as it tries to display images from the same page where documents were last viewed.
@mariobehling @nikhilrayaprolu  What do you suggest? How should images be displayed? Should there be paging for them at all? Google doesnot display images in pages, it displays all of them at once. Should we implement something like that?
If images and videos have the paging system too, then where should it start from, from page 1 or the page the user is currently viewing in say documents?

**Comment by nikhilrayaprolu** [comment]
@Marauderer97 when user clicks on images reset the page to first page. Secondly Google doesn't load all images at once, it loads sufficient number of images initially and then starts adding extra images on scroll , it's a type of pagination involving automated Ajax calls based on scroll length. Implementation of image page similar to Google is highly appreciated.
