### ISSUE TITLE
Chrome blocked api call, mixed content

### ISSUE THREAD

**Issue by AnshulMalik** [fossasia/susper.com#353]
Using Chrome Version 56.0.2924.87 (64-bit)

Throws mixed content warning and blocked the api call.

![s](https://cloud.githubusercontent.com/assets/7821757/26484533/4ad448a8-4210-11e7-8917-97615dcd1ea1.png)

**Comment by nikhilrayaprolu** [comment]
susper is being developed on http port and not on https. please access susper at http://susper.com
