### ISSUE TITLE
Add a page 'how to add Susper as search provider in Chrome browser' in tutorials

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#365]
## Problem
We will be adding up ' how to add susper as search provider in chrome' in tutorials section following to DuckDuckGo - https://duckduckgo.com/install?t=hc because Chrome has some different feature to add search provider. Catch up more discussion here - #314 

## Solution
One can start working on this once, **search-settings** page component has been created in #270

**Comment by mariobehling** [comment]
Please add this in the docs folder. Don't add this on the main site. Thanks.
