### ISSUE TITLE
Implement design of google.com and loklak.net and avoid old susper.com style

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#37]
The basis of the service was the old susper.com website. The goal of the new development would be to get a service that has a more modern design similar to google and loklak.

**Comment by harshit98** [comment]
I would like to work on this issue #92 . I'll start this work soon.

**Comment by designcrumble** [comment]
I would definitely like to help out on this issue.

**Comment by nikhilrayaprolu** [comment]
@designcrumble ok go ahead, find something which could be designed well (or) if you find something not responsive , make it responsive.
also if you could find some bugs around , raise issues and you could start working on them.
