### ISSUE TITLE
Update package.json

### ISSUE THREAD

**Issue by Marauderer97** [fossasia/susper.com#379]
Since we are updating our code, and making it cleaner, let us also update package.json, add the line to deploy in it? 
This was discussed in [#198](https://github.com/fossasia/susper.com/pull/198) and [#210](https://github.com/fossasia/susper.com/pull/210)

**Comment by harshit98** [comment]
Yes, do it. Are you working on it ? I have previously added script but it was removed later when heroku was set up.

**Comment by nikhilrayaprolu** [comment]
@Marauderer97 did you mean updating only the deploy line or updating all packages to the latest version?

**Comment by Marauderer97** [comment]
@nikhilrayaprolu I meant a total update, updating all packages included.
