### ISSUE TITLE
Ensure all searches on specific tab e.g. images, videos are showing results on this tab again

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#383]
A new search performed on the image tab leads to the "All" tab instead of image tab again. Expected: A search on a specific tab should lead to results on this tab again.
![screenshot from 2017-05-30 20-05-17](https://cloud.githubusercontent.com/assets/1583873/26597809/883b3cea-4573-11e7-8224-eefd10eb3687.png)

**Comment by Marauderer97** [comment]
This issue was referred to by mistake, since it was confused with the title of another issue. Reopened since it hasn't been solved yet. Sorry for the misunderstanding.

**Comment by harshit98** [comment]
@mariobehling @Marauderer97 According to issue, it looks to be solved. I didn't find any problem while searching as mentioned in this issue.

**Comment by Marauderer97** [comment]
@harshit98 I agree
