### ISSUE TITLE
Set a reasonable maximum width for images and ensure scalings are in correct ratio/proportion

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#384]
The image search shows at times images that are larger than the page width. Please set a reasonable maximum width.
![screenshot from 2017-05-30 20-08-05](https://cloud.githubusercontent.com/assets/1583873/26597908/db53208c-4573-11e7-9279-3c1bd6d23934.png)

**Comment by harshit98** [comment]
Fixed in #687.This issue can be closed now.

**Comment by bhaveshAn** [comment]
Is this issue still active ?
