### ISSUE TITLE
implement the add susper is default toast

### ISSUE THREAD

**Issue by nikhilrayaprolu** [fossasia/susper.com#4]
once the initial project is setup one could start working on this.
![screenshot from 2017-01-17 23-02-53](https://cloud.githubusercontent.com/assets/15216503/22032128/25eb485a-dd09-11e6-99e4-a6189973c609.png)

**Comment by yasirunilan** [comment]
Can I work on this issue?

**Comment by nikhilrayaprolu** [comment]
@yasirunilan you can proceed

**Comment by yasirunilan** [comment]
@nikhilrayaprolu can you please explain on this more. It would be really helpful

**Comment by nikhilrayaprolu** [comment]
@yasirunilan 
https://github.com/fossasia/susper-backbone/issues/14
https://github.com/fossasia/susper-backbone/pull/46

look at the above issues and pulls ,those were about the implementation of this issue in susper-bacbone repository which is being moved to angular here

**Comment by yasirunilan** [comment]
@nikhilrayaprolu  not stated yet,

**Comment by nikhilrayaprolu** [comment]
#62 resolved this issue.
