### ISSUE TITLE
Change Autocomplete's API to Yacy

### ISSUE THREAD

**Issue by Marauderer97** [fossasia/susper.com#410]
**Actual Behaviour**

The current autocomplete feature depends on the dbpedia prefix API.

**Expected Behaviour**

We wish for it to be independent of external APIs. So we need to use Yacy's API instead. This link can be used
[HERE](http://www.yacy-websuche.de/wiki/index.php/Dev:APIsuggest)

**Comment by harshit98** [comment]
@Marauderer97 Are you working on this ?

**Comment by harshit98** [comment]
Are you getting any suggestions from the API @Marauderer97  ? Check here - http://yacy.searchlab.eu/suggest.json?q=how . What I'm getting is an empty array. But for queries like `su`, `so`, `in` we're getting suggestions. Try those query to fix this issue. : )

**Comment by Marauderer97** [comment]
@harshit98 Yes. 
@nikhilrayaprolu @harshit98  could you please review the above commit and tell me if you have any suggestions or advice as to why the results for auto complete are not being displayed? Thanks in advance ! :smile:

**Comment by harshit98** [comment]
@Marauderer97 I saw your commit. Remove console logs. They will generate console errors. Refer #168
