### ISSUE TITLE
Getting search results very slow

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#411]
Any idea why search results are very slowly displayed? Is it a server or front-end issue?

**Comment by harshit98** [comment]
@mariobehling It must be a server issue. Although, now it's showing search results fast.

**Comment by nikhilrayaprolu** [comment]
as the server issue of sending the results slowly is solved and now susper is showing results in much better speed, closing this issue. kindly please reopen this if there is some error again in susper like this.
