### ISSUE TITLE
Crawl Start User Interface

### ISSUE THREAD

**Issue by Orbiter** [fossasia/susper.com#413]
susper.com right now depends on YaCy. The YaCy project currently creating a re-design of the crawler in the YaCy Grid project. We want a crawl start user interface for susper, so the susper.com interface gets a user interface which is able to place a crawl start into the YaCy grid.

Some background information: a web index is created by loading a lot of web pages first, then parsing the content and placing the result into a search index. The question is: how to get a large list of urls? This is solved by a crawler: we start with a single web page, extract all links, then load these links and go on. The root of such a process is the 'Crawl Start'.

What we need is a clone of the following page from YaCy: http://yacy.searchlab.eu/CrawlStartExpert.html

There are a lot of attributes in that page. **All of them** are required in the new crawl start page. To solve this issue, we need a page within susper.com which has the same fields as the mentioned Web Crawl start http://yacy.searchlab.eu/CrawlStartExpert.html

To simplify this task, you can use the original code of that web page which is here:
https://github.com/yacy/yacy_search_server/blob/master/htroot/CrawlStartExpert.html

When a user has entered the crawl start entries and pushes the button "Start New Crawl Job" the web pages must send all fields as a JSON object to the back-end server. This back-end server is currently created but not finished. Please make the endpoint url for the start configurable.

**Comment by Orbiter** [comment]
Here is a documentation of all fields that the original Crawl Start API uses:
http://www.yacy-websearch.net/wiki/index.php/Dev:APICrawler
For this task we do not send single attributes to the back-end, but a single JSON which has all these attributes in one JSON object.

**Comment by Orbiter** [comment]
To show default values in the crawl start page, use values from this endpoint:
http://yacygrid.com:8300/yacy/grid/crawler/defaultValues.json

This servlet also shows how the JSON object should look like that the web pages pushes to the endpoint.

**Comment by Orbiter** [comment]
please OMIT the following fields, they are not needed here:
* crawlOrder
* intention
* xsstopw

**Comment by nikhilrayaprolu** [comment]
@Orbiter I am facing CORS error while getting defaults and posting the crawl start values. Can CORS be enabled on server side for these.

**Comment by Orbiter** [comment]
yes you can cirumvent the CORS problem using a JSONP call, like:
http://yacygrid.com:8300/yacy/grid/crawler/defaultValues.json?callback=p

**Comment by nikhilrayaprolu** [comment]
@Orbiter on posting data to the server I am receiving unauthorised 401 Status. what could be a fault with this?
![image](https://user-images.githubusercontent.com/15216503/26918393-6cad300e-4c4f-11e7-9723-e2138ae3cd03.png)

**Comment by Orbiter** [comment]
Well that is correct because your are actually unauthorized :)
The server requires an log-in. When the endpoint is called from a browser, this should cause that the browser shows a pop-up and asks the user for authentication (aka "HTTP Basic Authentication", https://tools.ietf.org/html/rfc7235#section-3.1). In YaCy this works without handling any 401 code, the handling is built-in in all browsers. See also https://en.wikipedia.org/wiki/Basic_access_authentication

To make this possible in YaCy, one need to do *nothing*, the browser is doing that process. But YaCy does not use angularjs.

I don't know how angularjs deals with this issue. Maybe the same (do nothing) or with an explicit handler. I found this: http://jasonwatmore.com/post/2014/05/26/angularjs-basic-http-authentication-example but it looks a bit complex. Maybe it can be more simple. Here is another example: https://stackoverflow.com/questions/17959563/how-do-i-get-basic-auth-working-in-angularjs

**Comment by Orbiter** [comment]
To test this, you can also set up a local YaCy instance (download from yacy.net) and access the crawl endpoint at localhost:8090. Then you have control over the account/password

**Comment by nikhilrayaprolu** [comment]
ok, sure @Orbiter I will look through this.

**Comment by nikhilrayaprolu** [comment]
crawl start page is implemented in #415 ,hence closing this issue.
