### ISSUE TITLE
Errors in console when Knowledge API results unavailable

### ISSUE THREAD

**Issue by Marauderer97** [fossasia/susper.com#422]
**Actual Behaviour**

Multiple errors show up on  my console each time a query is made, when there are no related searches from Knowledge API

**Expected Behaviour**

These errors need to be removed both for infobox and related searches

**Screenshots of the issue**

![image](https://cloud.githubusercontent.com/assets/20185076/26818787/b350a14a-4ab9-11e7-95b1-b6e0a74d6137.png)

**Comment by nikhilrayaprolu** [comment]
due to recent pull in the modification of knowledge service, this error is raised again.
![image](https://user-images.githubusercontent.com/15216503/26876870-aa178854-4ba5-11e7-8ea5-4afe75369cf2.png)
