### ISSUE TITLE
cannot connect to yacy backend

### ISSUE THREAD

**Issue by nikhilrayaprolu** [fossasia/susper.com#44]
![screenshot from 2016-12-28 20-22-25](https://cloud.githubusercontent.com/assets/15216503/21524444/1d6d4ce6-cd3c-11e6-935f-d22a16079285.png)

@Orbiter @mariobehling

**Comment by nikhilrayaprolu** [comment]
@mariobehling the yacy backend is up. so we could resume converting this to angular2. can you please make a separate branch for angular2 project , so that we can commit angular2 related stuff to that branch.

**Comment by mariobehling** [comment]
> make a separate branch for angular2

Done. Thank you!
