### ISSUE TITLE
Create a list of news organizations with URLs and show results from this list in a tab "News" limited to the last 30 days

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#448]
We would like to have a tab "News". Search results of news organizations actually constitute simply of a filter that is set and results are displayed according to this filter.

In order to achieve this, please do the following:
* Create a list of news organizations and their URLs as csv (small list is ok. it can be extended later).
* Some news organizations can have more than one URL
* Create a tab "News" in the UI
* in the tab "News" limit searches to results of the last 30 days
* Show recent results on top

**Comment by harshit98** [comment]
Kindly review the commit @nikhilrayaprolu @Marauderer97 I'm getting this error when I load RSS feed : 

![screenshot from 2017-06-13 14-59-35](https://user-images.githubusercontent.com/22245418/27075965-67b147fe-5049-11e7-83db-aa5a07583a7b.png)

**Comment by nikhilrayaprolu** [comment]
@harshit98 jsonp expects jsonp response but what you are receiving might be json or html. so use http intead of jsonp

**Comment by harshit98** [comment]
@nikhilrayaprolu Using http gives CORS error. Look : 

![screenshot from 2017-06-13 16-12-32](https://user-images.githubusercontent.com/22245418/27078980-8669feb6-5053-11e7-9457-9496c3176c47.png)

**Comment by harshit98** [comment]
> - Create a list of news organizations and their URLs as csv
> - Create a tab "News" in the UI

I have updated my PR. Kindly preview @Marauderer97 @nikhilrayaprolu 

These two things have been done. Now how should we filter news ? 
- I'm still not able to figure out why we have created a csv file ? Are we going to take urls from csv file ?
- Second option : We can filter out the news urls in `News` tab. Advanced search shows urls of some news organizations. We can take urls from here. If yes then how ?

![screenshot from 2017-06-17 17-06-36](https://user-images.githubusercontent.com/22245418/27252571-6fb191dc-537f-11e7-9c71-0c93314b6db2.png)

![screenshot from 2017-06-17 17-03-48](https://user-images.githubusercontent.com/22245418/27252572-732cb6f2-537f-11e7-8981-245b8e488dd6.png)

**Comment by mariobehling** [comment]
> I'm still not able to figure out why we have created a csv file ? Are we going to take urls from csv file ?

Yes. It can also be a JSON file, but CSV would allow non coders to easily edit that file.

**Comment by nikhilrayaprolu** [comment]
we can take all top sites on the basis of Alexa ranking on News category http://www.alexa.com/topsites/category/News

**Comment by nikhilrayaprolu** [comment]
@Orbiter presently for retrieving results from a specific site in Yacy we can add a modifier `site="bbc.com"` but what if we want results from two or more sites simultaneously? do we have any modifier for the query facet that could accept multiple sites?

**Comment by praveenojha33** [comment]
@mariobehling @harshit98 @nikhilrayaprolu I have decided to fetch news from [NewsApi.org](newsapi.org) or should we retrieve results from YaCy only. Please guide me about this.

**Comment by praveenojha33** [comment]
I and @ValentinBercaru are working on this feature but we were unable to find any modifier for query facet that can use multiple sites to filter the results retrieved from YaCy. Currently we can only use a single site to filter the results and show it under News tab. @Orbiter we have researched a lot but we have not found any modifier that accepts multiple sites. @Orbiter can you tell what we are missing or we do not have such modifier. 
A possible solution is that to filter the results using `*ngIf` and display results only from the news sites by using an OR( || ) operator while displaying the results.This method seems logical but it also does not give the results and is a bit slower.
Another solution is to display results from a single site only using modifier `site="dailymail.co.uk"` .
We are currently searching a way to resolve the problem. Thanks in advance for your help.

**Comment by praveenojha33** [comment]
![result](https://user-images.githubusercontent.com/25537606/37013769-df237966-2121-11e8-9869-a52e71e57558.jpg)
Above result we got by filtering results by `*ngIf` and below is the result that we get by using a modifier to the search query.
![help2](https://user-images.githubusercontent.com/25537606/37013904-eacc6498-2122-11e8-8084-679d8ddb067d.png)
