### ISSUE TITLE
Not all related searches are being displayed

### ISSUE THREAD

**Issue by Marauderer97** [fossasia/susper.com#449]
**Actual Behaviour**

The related searches are displayed only when the infobox is valid, hence for many queries which previously had related searches, there are no related links displayed anymore

**Expected Behaviour**

Seperate infobox function from related searches, infobox for a query say "go" may not be valid, but the related searches should still be displayed

**Screenshots of the issue**
Before ![image](https://cloud.githubusercontent.com/assets/20185076/26447988/b55e5590-4168-11e7-9ec9-27a037a5f05b.png)

Now 
![image](https://user-images.githubusercontent.com/20185076/26922263-3bf87920-4c5c-11e7-889e-2c1460e398b0.png)

**Comment by Marauderer97** [comment]
@harshit98 are you working on this? (as mentioned on gitter)

**Comment by harshit98** [comment]
Yes, I would like to try this issue. :+1:

**Comment by harshit98** [comment]
@nikhilrayaprolu How should I proceed with this issue ? When a search is done, dbpedia API does not responds which hence results in infobox and related searches not appearing. Opened up issue #466

**Comment by harshit98** [comment]
I have solved this issue. Will make the PR today :)

**Comment by Marauderer97** [comment]
@harshit98 As requested by you on gitter, since you are focussing on adding news currently, I am unassigning you from the issue.
