### ISSUE TITLE
Help icon to be modified

### ISSUE THREAD

**Issue by Marauderer97** [fossasia/susper.com#45]
The links under the help icon are redundant as they all point to yacysearch(as it was in susper-backbone), they require to be updated, and restyled. @mariobehling  Any ideas on how to go about this? Especially since google has no feature like this.
Susper: 
![image](https://cloud.githubusercontent.com/assets/20185076/22825536/e2cb8284-efb3-11e6-9c58-d25e3f180136.png)

Google:
![image](https://cloud.githubusercontent.com/assets/20185076/22825574/07f67fd2-efb4-11e6-9715-c959b5db3106.png)

**Comment by Marauderer97** [comment]
In continuation to the discussion on PR #47, 
We can add a well styled button, with a menu of icons. We need to finalise the menu for this though.
What links should the menu contain? 
Apart from the About page and a page to the github link of susper.com, can we add other items to our menu?
@nikhilrayaprolu @mariobehling What do you recommend?

**Comment by nikhilrayaprolu** [comment]
as in the discussion on #47 ,You can make separate icons for each subtopic in help page and make the help icons look like google apps . for now you could use matching material icons ( https://material.io/icons/ ) for the help pages.
and comming to the links you have to make only the about page in susper , all others links are regarding the yacy backend and yacy tutorials which can be redirected as it is
