### ISSUE TITLE
Error: status of 500 Java heap space

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#454]
susper.com is currently not providing any search results. 

![screenshot from 2017-06-09 01-11-53](https://user-images.githubusercontent.com/22245418/26948423-f522ae8c-4cb3-11e7-88e0-626271962faf.png)

@Orbiter kindly look into this issue :)

**Comment by Orbiter** [comment]
restarted two redundant peers, each has 4GB of memory. strange that it has a heap space error.
Running now again after restart.
