### ISSUE TITLE
Don't show a blinking cursor in search box after user hits enter

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#457]
In the search box a blinking cursor shows up even after the user hits enter.

Please compare to market leader and don't show blinking cursor after user hit enter.
![screenshot from 2017-06-08 22-29-18](https://user-images.githubusercontent.com/1583873/26949451-41af5daa-4c9a-11e7-8884-0014925d7ed7.png)

**Comment by harshit98** [comment]
I would like to work on this. :+1:

**Comment by Marauderer97** [comment]
@harshit98 I am sorry, I didnot see your message. I mentioned working on this on my scrum, but forgot to assign myself to it. Sorry about that. Let us start a practice of assigning ourselves to issues, once we decide to work on them :+1:
