### ISSUE TITLE
Match bottom bar links to search results pages closer to market leader

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#463]
Please follow the design of the market leader for the search result pages.
![screenshot from 2017-06-09 01-23-24](https://user-images.githubusercontent.com/1583873/26954863-0908293c-4cb3-11e7-9545-fc7abe49c3a8.png)

**Comment by Marauderer97** [comment]
@mariobehling The market leader has "Gooooooogle" to mark the number of pages.. What should we substitute that with? Or should we ignore that part of the pagination bar and only copy the number and text style?

**Comment by mariobehling** [comment]
Please use "Suuuuuuuuuuuuuuuuuuuuusper".

**Comment by Marauderer97** [comment]
@mariobehling 
I have been working on this, wanted your opinion
![image](https://user-images.githubusercontent.com/20185076/26976928-a175bbcc-4d43-11e7-986f-f49755509114.png)
Is this what you intended? Can I make a PR?

**Comment by harshit98** [comment]
Looks great! @Marauderer97 Can you remove the `Previous` from page 1 just like Google ?
