### ISSUE TITLE
Images are not showing up on image search

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#464]
While image search works on the host yacy system (http://yacy.searchlab.eu/yacysearch.html?query=trump&maximumRecords=10&resource=global&verify=ifexist&prefermaskfilter=&cat=href&constraint=&contentdom=image) it does not work on susper.

**Comment by harshit98** [comment]
We're getting error on susper which looks like this- 

![screenshot from 2017-06-09 13-13-25](https://user-images.githubusercontent.com/22245418/26966116-6ec8c2d2-4d16-11e7-8e80-fbd1537e2104.png)
