### ISSUE TITLE
Infoxbox appears when page is refreshed.

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#466]
**Actual Behaviour**

Infobox not coming up when a search is fired. It is not an API issue, as dbpedia is working fine.

**Expected Behaviour**

Infobox should appear with search results.

**Comment by Marauderer97** [comment]
![image](https://user-images.githubusercontent.com/20185076/26978252-7ab15e10-4d48-11e7-9417-b3a0ad816843.png)
But it is appearing :confused:

**Comment by harshit98** [comment]
@Marauderer97 

![screenshot from 2017-06-10 01-22-42](https://user-images.githubusercontent.com/22245418/26992240-5b1a4bec-4d7b-11e7-8da8-fc664bae37f9.png)
