### ISSUE TITLE
When there is no query, no any content should be displayed.

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#480]
**Actual Behaviour**

When there is no query or query is erased, only 'related searches' and 'infobox' is still being showed up.

**Expected Behaviour**

If no query is present, result page should be empty.

**Screenshots of the issue**

![screenshot from 2017-06-14 11-01-40](https://user-images.githubusercontent.com/22245418/27116883-342a33b6-50f1-11e7-8d85-2a2f74f0c2b9.png)

Follow similar implementation to market leader.

**Comment by Marauderer97** [comment]
I would like to work on this issue

**Comment by Marauderer97** [comment]
@harshit98 when I try to replicate the same issue, this is what I get:
![image](https://user-images.githubusercontent.com/20185076/27119692-7003b5d0-50fe-11e7-9b8b-542f81296dca.png)

**Comment by harshit98** [comment]
@Marauderer97 I don't know. But previously it was happening. Should I close it then ?
