### ISSUE TITLE
Wrong position of Settings Tab and absence of drop-down menu

### ISSUE THREAD

**Issue by Marauderer97** [fossasia/susper.com#483]
**Actual Behaviour**
The settings tab is in the footer of Susper.

**Expected Behaviour**
Google has the settings bar on the top, next to Tools.

**Screenshots of the issue**
![image](https://user-images.githubusercontent.com/20185076/27165390-2e822b06-51b1-11e7-9146-902c7498e9ab.png)

![image](https://user-images.githubusercontent.com/20185076/27165357-0b510f94-51b1-11e7-88ad-5fb006de982a.png)

**Comment by nikhilrayaprolu** [comment]
google has it at the bottom of the home page, so it would be better if something similar, at the bottom of the homepage and at the top of the results page is implemented.
![image](https://user-images.githubusercontent.com/15216503/27166045-a685b1a0-51b5-11e7-91ee-45f05065d83d.png)

also, see that it gives us a dropdown in which search settings is shown.please create a drop down similar to Google

**Comment by Marauderer97** [comment]
Working on this

**Comment by Marauderer97** [comment]
@nikhilrayaprolu what happens to the other links in the dropdown(features we haven't implemented)? I will not include them for now.

**Comment by nikhilrayaprolu** [comment]
@Marauderer97 let us add those when implemented.
