### ISSUE TITLE
Search settings Number of Results bar different from market leader

### ISSUE THREAD

**Issue by Marauderer97** [fossasia/susper.com#484]
**Actual Behaviour**

Susper allows 500 results per page

**Expected Behaviour**
Google allows only 0,10,20,30,40,50 or 100

**Screenshots of the issue**
Susper:
![image](https://user-images.githubusercontent.com/20185076/27165425-75fa1e44-51b1-11e7-8696-c9e54fd51a18.png)
Google:
![image](https://user-images.githubusercontent.com/20185076/27165442-9f2139a6-51b1-11e7-94d6-19b02baf4dc9.png)

NOTE: In a way, Susper allows way more flexibility currently(allowing any number of results from 0 to 500), hence this issue is not a bug, it is up for discussion.

**Comment by nikhilrayaprolu** [comment]
This will be automatically fixed when instant results https://github.com/fossasia/susper.com/issues/479 feature is implemented

**Comment by Marauderer97** [comment]
Since instant results have been implemented, this issue is being closed
