### ISSUE TITLE
Configure codecov.yml to avoid failing PRs.

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#487]
**Actual Behaviour**

Currently we are observing problems with failing PRs even Travis CI passes. This is due to even a small drop in code coverage, PR is failed.

**Expected Behaviour**

Configure `codecov.yml` file especially to avoid failing PR, when code coverage drops a little.

References : 
- <a href="https://github.com/codecov/support/issues/135">codecov/support#135</a>
- https://gist.github.com/stevepeak/53bee7b2c326b24a9b4a#file-codecov-yml-L86

**Comment by nikhilrayaprolu** [comment]
reopening this since this isn't yet fixed.
