### ISSUE TITLE
Related Searches too small and not aligned

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#490]
The related changes areas have changed for no apparent reason:
* On the right and bottom they are in a smaller font than before
* On the bottom area they are not aligned anymore
![screenshot from 2017-06-16 06-55-43](https://user-images.githubusercontent.com/1583873/27212577-3e9aac92-5261-11e7-8def-715e1ec7ce56.png)
![screenshot from 2017-06-16 06-55-14](https://user-images.githubusercontent.com/1583873/27212579-41ef4dda-5261-11e7-9fa9-2342044b13a0.png)

**Comment by Marauderer97** [comment]
@mariobehling 
The alignment seems to be fixed now
![image](https://user-images.githubusercontent.com/20185076/27214134-7a259bba-5288-11e7-89bb-ae9b7b94c51e.png)

**Comment by Marauderer97** [comment]
Also, Links on top nav bar,
how they are:
![image](https://user-images.githubusercontent.com/20185076/27214615-014c551e-528b-11e7-9a24-4ed2f6bf9d15.png)
how they should be:
![image](https://user-images.githubusercontent.com/20185076/27214624-1801b164-528b-11e7-9713-a1cafd3bdbf4.png)

**Comment by nikhilrayaprolu** [comment]
![image](https://user-images.githubusercontent.com/15216503/27232602-4641cf0c-52d4-11e7-945b-51ceee64167a.png)
@Marauderer97 this change has caused the small sizes.

**Comment by harshit98** [comment]
Once the PR of news feature gets merged, we can start working on this. Since, there is addition of other 'News' tab also.

**Comment by harshit98** [comment]
Working on it. :+1:
