### ISSUE TITLE
"Sort by date" not working.

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#500]
**Actual Behaviour**

To reproduce the bug, type query as `mumbai`. You'll observe some results are having old date mixed with latest date. Sorting them by using `Sort by date` is not working. 

**Expected Behaviour**

It should sort the results date wise in descending order. (2017 -> 2016 -> 2015...) 

**Screenshots of the issue**

![screenshot from 2017-06-17 05-00-59](https://user-images.githubusercontent.com/22245418/27247832-0061026e-531a-11e7-85c9-8d95a4d34e87.png)

**Comment by Marauderer97** [comment]
I have been working on this issue, the reason there is no change is, there is no valid response in return to the query. When @nikhilrayaprolu and I first implemented this feature, it was working perfectly, and hence, I was wondering if perhaps the update to the latest version of solr caused this. 
![image](https://user-images.githubusercontent.com/20185076/27259623-95651330-5434-11e7-8428-f2b1e76035b3.png)
This is the error I get, stackoverflow says it might be a parsing error, but I am not sure, besides there isn't a lot of input on how to fix it.
@harshit98 Please comment if you have any inputs

**Comment by Marauderer97** [comment]
[This link ](https://issues.apache.org/jira/browse/SOLR-2606) describes how in some versions of Solr, sort does not work on field parameters with punctuation in them
In last_modified, we have an underscore, this might be causing the problem.
However, as an experiment, I tried sorting on the field name: title, but that gives me the same error.

**Comment by harshit98** [comment]
@nikhilrayaprolu As per discussion on Gitter, you asked case. See here the screenshot in this issue. The error message literally is `'start' parameter can't be negative`. So apparently we're sending a negative value for start somewhere. 

This maybe had occurred while you solved the issue regarding cleaning URL.

**Comment by nikhilrayaprolu** [comment]
the request we are sending to the background is having start=0,
![image](https://user-images.githubusercontent.com/15216503/27545445-78fea560-5aad-11e7-93b7-87564395dabe.png)
and the error I receive on clicking the sort by date is
![image](https://user-images.githubusercontent.com/15216503/27545512-991e7bae-5aad-11e7-8625-533254ad9acf.png)

so, for now, I will try reverting back the present repo in my local repo to some previous state where there is no error and check what are parameters are missing in the request we make to the server.

**Comment by nikhilrayaprolu** [comment]
I have reverted the repository to as old as to Feb 18 and this problem exists. this is for sure a problem from the side of Yacy.No recent commit has created this error.
![image](https://user-images.githubusercontent.com/15216503/27631977-f496f5f4-5c17-11e7-8983-d8afdb9da07b.png)

**Comment by harshit98** [comment]
Closing this issue, solved in #721
