### ISSUE TITLE
Match the width and height of search box of market leader and related areas

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#507]
Please match the width, height and functionality of market leader. The developer console shows 632 x 49 including border. Please use the browser developer console to determine the required sizes.

Also ensure that following content areas match the search box.
![screenshot from 2017-06-17 16-31-38](https://user-images.githubusercontent.com/1583873/27253772-e36d7ab4-537a-11e7-82ee-b3739ac9d552.png)

**Comment by harshit98** [comment]
Working on this. :+1:

**Comment by mariobehling** [comment]
It is still not matching.

**Comment by mariobehling** [comment]
E.g. area of search result is wider than area of search box.

**Comment by harshit98** [comment]
Working on this. :+1:

**Comment by mariobehling** [comment]
Unfortunately this issue was never resolved entirely.

**Comment by mariobehling** [comment]
* Search box and below results are not aligned at the end
* info box now moved further below
![screenshot from 2017-08-02 01-16-46](https://user-images.githubusercontent.com/1583873/28851043-56cfee88-7720-11e7-996d-c7b2c7c56ae0.png)

**Comment by harshit98** [comment]
@Marauderer97 When you were working for responsiveness for the screen size greater than 1920px, has it been fixed?

**Comment by bhaveshAn** [comment]
@harshit98 Is this issue active? I would like to work on...

**Comment by praveenojha33** [comment]
@mariobehling I think this issue is fixed. Please check and let me know.
