### ISSUE TITLE
Implement Voice Search for Chrome

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#508]
Using Google with Google Chrome it is possible to make a voice search. Please implement the same for Susper and automatically show the voice icon with the same functionality.

![screenshot from 2017-06-17 16-43-00](https://user-images.githubusercontent.com/1583873/27253834-409624a6-537c-11e7-8850-3d5beec00e99.png)

**Comment by harshit98** [comment]
Working on it. :+1:
