### ISSUE TITLE
Implement better dropdown menu

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#509]
The dropdown menu has issues. Please improve the following:
* make the distance to the dropdown more natural
* match the size and design of the market leader
* use colorful logo
* Add the following services below a horizontal line after the first section using the logos of the services:
   * FOSSASIA - fossasia.org
   * loklak - loklak.net
   * SUSI.AI - chat.susi.ai
   * eventyay - eventyay.com
* Add a more link on the bottom section to "labs.fossasia.org"

![screenshot from 2017-06-17 16-40-32](https://user-images.githubusercontent.com/1583873/27253912-dc4cd312-537d-11e7-87d1-cdec0202c6c3.png)

**Comment by harshit98** [comment]
@mariobehling Google has dropdown menu at homepage and in results page as well. Susper is currently having it in results section not on homepage. Should we implement the same for Susper ?

**Comment by Marauderer97** [comment]
@harshit98 Are you working on this?

**Comment by harshit98** [comment]
Yes @Marauderer97
