### ISSUE TITLE
SUSPER logo not linked to homepage.

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#51]
Here are the screenshots of the following logo i'm taking about :- 
![11](https://cloud.githubusercontent.com/assets/22245418/22852332/084ec3ac-f060-11e6-990d-c92fbcb5f5ec.PNG)
![11a](https://cloud.githubusercontent.com/assets/22245418/22852334/0dbee2ae-f060-11e6-8965-9472be118858.PNG)

On clicking the SUSPER it should- direct to susper.com just like Google.

**Comment by isuruAb** [comment]
This issue is already fixed in #41 this
