### ISSUE TITLE
Enhance FooterNavbar

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#516]
**Actual Behaviour**

Currently, footer navbar seems to have a lot of options which are making it a bit messy. Like we are having 2 settings tab and a Crawl job option too (which should come under settings tab). **Kindly discuss here, what can be done, then we will proceed.**

**Expected Behaviour**

It should look like a clean UI to encourage more users to use Susper.

**Screenshots of the issue**

![screenshot from 2017-06-19 14-44-34](https://user-images.githubusercontent.com/22245418/27278168-30ebf05c-54fe-11e7-834c-ba24c8c3c652.png)

**Comment by nikhilrayaprolu** [comment]
let us first remove duplicate links and add advanced search into search settings since Google has advanced search inside settings tab

**Comment by Marauderer97** [comment]
I am working on this, will remove duplicate links, and create a drop up similar to Google @nikhilrayaprolu is that alright?

**Comment by Marauderer97** [comment]
I also recommend putting crawl job in Settings, since 
a. it will further declutter the navbar
b. A lot of the content in the crawl job page is related to settings(page depth, or allowed filters etc), so it will be relevant too
Please let me know what you think @nikhilrayaprolu @harshit98
