### ISSUE TITLE
Pagination bar not appearing.

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#523]
**Actual Behaviour**

Pagination bar seems to be not appearing. 

**Expected Behaviour**

It should appear in all in the pages. To avoid this problem : create a `pagination` component instead of combining with results component.

**Screenshots of the issue**

![screenshot from 2017-06-20 07-12-51](https://user-images.githubusercontent.com/22245418/27312741-e960e6e0-5587-11e7-9be9-ca8a2dbdab00.png)

**Comment by Marauderer97** [comment]
@harshit98 While creating a component for pagination might be a good idea, I do not think that is why this is happening, this is a bug, I am working on it, will update soon :+1:

**Comment by harshit98** [comment]
No @Marauderer97 since refactoring results page also an issue we can separate it as a component with some tests so that problem won't occur from next time.
