### ISSUE TITLE
Improve mobile view of Susper.

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#524]
**Actual Behaviour**

This issue was fixed in #138 but now recent changes in Susper like : 
- fixing search bar dimensions
- addition of voice search icon.
- addition of settings tab.

The mobile view issue is with : homepage and result page.

**Expected Behaviour**

It should have clear UI for mobile as well. To avoid this problem occurring again and again : 
- Fix issues like : #507 and #509 (on both issues I'm working at present) , #516 , #523 
- Add tests so that it won't repeat again in future. 
- **Kindly consider this issue and attached issues as high priority issues.** 

**Screenshots of the issue**

(Not appropriate here since they can be observed easily)

**Comment by mariobehling** [comment]
![screenshot_2017-07-09-12-42-51](https://user-images.githubusercontent.com/1583873/27993184-8ef5abce-64a4-11e7-938a-700f1b8da7d0.png)

Still major issues.

**Comment by harshit98** [comment]
Closing this issue, since majority of the work has been done on it and some minor issues are still open as separate issue.
