### ISSUE TITLE
susper has a search icon on home page but google has an empty search bar without search icon on home page

### ISSUE THREAD

**Issue by nikhilrayaprolu** [fossasia/susper.com#527]
google has no search icon on the front page but susper has a search icon remove the search icon.remove the search icon on the home page of susper.
![image](https://user-images.githubusercontent.com/15216503/27318954-9a776854-55ac-11e7-9d50-964f359ac4a2.png)

![image](https://user-images.githubusercontent.com/15216503/27318841-f9009752-55ab-11e7-852d-db2bbce7f48d.png)

**Comment by harshit98** [comment]
@nikhilrayaprolu Kindly make sure, when a search is attempted, search icon appears in Google. 

![screenshot from 2017-06-20 11-44-04](https://user-images.githubusercontent.com/22245418/27319169-cb6d289e-55ad-11e7-8720-1fc8cdada10a.png)

**Comment by nikhilrayaprolu** [comment]
@harshit98 sure.
