### ISSUE TITLE
selecting "never show instant results" not working 

### ISSUE THREAD

**Issue by nikhilrayaprolu** [fossasia/susper.com#528]
**Actual Behaviour**
Once instant results are selected and then we select "never show instant results". this isn't working as required
**Expected Behaviour**
selecting "never show instant results" should stop instant results from working.
![image](https://user-images.githubusercontent.com/15216503/27319088-5d20d520-55ad-11e7-8aa3-503ac4b56dfc.png)

**Comment by harshit98** [comment]
Are you working on this @nikhilrayaprolu ? How we can proceed this issue ?

**Comment by nikhilrayaprolu** [comment]
yes working on this,will be making a pull request now
