### ISSUE TITLE
refactor susper's result page

### ISSUE THREAD

**Issue by nikhilrayaprolu** [fossasia/susper.com#53]
result's page is a single component now . which could be sub divided into many components which makes the code maintainable and understandable.
- [x] Search bar component.
- [x] Autocomplete component.
- [x] Infobox component.
- [x] Related search component.
- [x] Dropdown component.
- [x] Navbar component.
- [x] Footer navbar component.

Left :- 
- [ ] Pagination component.

- [ ] Images component

- [ ] videos component

**Comment by Marauderer97** [comment]
@nikhilrayaprolu i would like to be assigned to this.

**Comment by Marauderer97** [comment]
@nikhilrayaprolu How do you propose we go about this?
Text results, Image results and Video results will be sub-components of the results page, which will only contain the general layout(pagination bar etc)?

**Comment by Marauderer97** [comment]
@nikhilrayaprolu Can you also figure out why issue #87 is occurring? This did not happen before, and persists even when images-page is made a separate component

**Comment by isuruAb** [comment]
I would like to work on this.

**Comment by nikhilrayaprolu** [comment]
@isuruAb refactoring a page requires us to be careful . hence we would like to make sufficient number of tests initially and then proceed with this. so that we could test that nothing goes wrong even in future when we refactor something. 
you can start contributing some tests

**Comment by harshit98** [comment]
@nikhilrayaprolu Now only refactoring of _Pagination bar_ is left. It will solve the issue completely. I'm stating here refactored components on result's page : 
- [ ] Search bar component.
- [ ] Autocomplete component.
- [ ] Infobox component.
- [ ] Related search component.
- [ ] Dropdown component.
- [ ] Navbar component.
- [ ] Footer navbar component.

Left :- 
- [ ] Pagination component.

**Comment by nikhilrayaprolu** [comment]
@harshit98 please separate event the images,videos and normal results into different components

**Comment by nikhilrayaprolu** [comment]
@Marauderer97 do you have any suggestion?

**Comment by harshit98** [comment]
@nikhilrayaprolu @mariobehling This issue can be closed now. We can't separate the images, videos, normal results into different components. They all should load in a single component i.e. `resultscomponent`.
