### ISSUE TITLE
Align logo and search box exactly in the middle of the screen

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#536]
Logo and search box are still not aligned exactly in the middle of the screen.
![screenshot from 2017-06-21 10-46-25](https://user-images.githubusercontent.com/1583873/27375318-0e1c93e8-566f-11e7-9c06-accb45d38ec9.png)

**Comment by harshit98** [comment]
Working on this. :+1:

**Comment by harshit98** [comment]
This issue can be referred here as well : #540

**Comment by harshit98** [comment]
Solved. Can be closed now.
