### ISSUE TITLE
Dbpedia not responding again.

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#539]
**Actual Behaviour**

When query is entered - dbpedia does not responds due to which infobox and related search component does not appear. But when, on pagination bar if user goes to page 2, then it responds.

**Expected Behaviour**

dbpedia should respond when query is fired.

**Screenshots of the issue**
(Not appropriate here)

**Comment by Marauderer97** [comment]
@nikhilrayaprolu This error seems to keep popping up, can you give any suggestions on how we can write tests for this, to prevent it next time?

**Comment by nikhilrayaprolu** [comment]
@Marauderer97 I would suggest you to go through this documentation https://angular.io/guide/testing

**Comment by Marauderer97** [comment]
@nikhilrayaprolu I think this issue can be closed now
