### ISSUE TITLE
Coming back to homepage shows query in search bar

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#554]
**Actual Behaviour**

Clicking on SUSPER logo - redirects to the homepage with a query in the search bar.

**Expected Behaviour**

It should redirects to the homepage, with no query inside search bar.

**Screenshots of the issue**

![giphy](https://user-images.githubusercontent.com/22245418/27512429-da5b338e-595c-11e7-9bc0-23c057393ffa.gif)

**Comment by Marauderer97** [comment]
Working on this

**Comment by harshit98** [comment]
@Marauderer97 Have you checked my scrum report?

**Comment by Marauderer97** [comment]
@harshit98 sorry, I missed the point, didn't realise. I saw no comments for the past 9 hours, so I assumed no one was working on this, I'll be more careful but please also comment on the issue, to prevent confusion

**Comment by harshit98** [comment]
Okay, I will keep that in mind. :+1:
