### ISSUE TITLE
Bring Intelligence to Susper

### ISSUE THREAD

**Issue by nikhilrayaprolu** [fossasia/susper.com#564]
right now google answers to questions people ask. 

![image](https://user-images.githubusercontent.com/15216503/27608944-ccb6187e-5ba6-11e7-9408-27418ec6641d.png)

we could implement the same feature in susper using SUSI AI. this even helps to improve the use cases of SUSI.
![image](https://user-images.githubusercontent.com/15216503/27609081-57e55e0a-5ba7-11e7-89c9-9f7984019096.png)

**Comment by nikhilrayaprolu** [comment]
@isuruAb @rishiraj824 Can you suggest us, which API endpoint to be used for this. how we could bring this feature.

**Comment by rishiraj824** [comment]
Hey @nikhilrayaprolu !
You can go over to api.susi.ai/susi/chat.json?q=YOUR_QUERY to begin getting responses from SUSI.
You can also get various action types in the response. Eg.
for http://api.susi.ai/susi/chat.json?q=hey%20susi
```
actions: [
{
type: "answer",
expression: "Hi, I'm Susi"
}
],
```

**Comment by nikhilrayaprolu** [comment]
@rishiraj824 where can I find documentation regarding this? what are all available actions?

**Comment by rishiraj824** [comment]
https://github.com/fossasia/susi_server/blob/development/docs/skills/susi_chat_api.md Here are all the available action types.
You can explore the other important material from https://github.com/fossasia/susi_server/blob/development/docs/

**Comment by nikhilrayaprolu** [comment]
@rishiraj824 thanks :+1: :smile:

**Comment by mariobehling** [comment]
Does not work for me yet.

**Comment by mariobehling** [comment]
Ok, working now. Good job!
