### ISSUE TITLE
A media search tab could be implemented in Susper

### ISSUE THREAD

**Issue by nikhilrayaprolu** [fossasia/susper.com#565]
A social media search tab could be implemented in susper, which shows results from loklak_server.
![image](https://user-images.githubusercontent.com/15216503/27609506-a2fa6b14-5ba8-11e7-875b-f14db6048c29.png)
presently if someone wants to know about a movie, they use search engines like Google.And to know about people's review on the movie they use search bars on social media sites like Twitter.
![image](https://user-images.githubusercontent.com/15216503/27609864-ea9ee264-5ba9-11e7-9bef-384a0d51948a.png)

we could integrate both onto one platform and be a one stop destination for both of them.

**Comment by nikhilrayaprolu** [comment]
working on this.

**Comment by mariobehling** [comment]
Please see comment here: https://github.com/fossasia/susper.com/pull/580#issuecomment-313853872
