### ISSUE TITLE
Travis is failing for each PR

### ISSUE THREAD

**Issue by nikhilrayaprolu** [fossasia/susper.com#572]
A recent test is broken since there is a structural change in html but the tests are not changed ,due to which travis is failing for all prs.

**Comment by nikhilrayaprolu** [comment]
reopening this, since merging this https://github.com/fossasia/susper.com/pull/569 before this lead to the addition of some more test fails https://github.com/fossasia/susper.com/pull/573.

Please don't merge any pulls until this issue is completely fixed.

**Comment by nikhilrayaprolu** [comment]
reopening as travis is failing for all prs.

**Comment by harshit98** [comment]
This can be closed now.
