### ISSUE TITLE
Make pages responsive

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#584]
The search and result page are not working on all mobile resolutions. Please improve.

**Comment by harshit98** [comment]
This issue can be referred here #524

**Comment by mariobehling** [comment]
Please ensure the search works on start page on all mobile resolutions.

Cannot access search now on start page and result page as button is off screen. See below.

![screenshot_2017-07-09-12-49-52](https://user-images.githubusercontent.com/1583873/27993202-3ff770a6-64a5-11e7-96aa-dd802e6933f9.png)

**Comment by bhaveshAn** [comment]
Is this issue still active ?

**Comment by praveenojha33** [comment]
This issue has been solved. Please reopen it if it persists or due to any changes responsiveness gets disturbed.
