### ISSUE TITLE
Weather Prediction by Susper

### ISSUE THREAD

**Issue by Marauderer97** [fossasia/susper.com#585]
Can we have a weather prediction feature in Susper?
 I have found a [free API](https://market.mashape.com/fyhao/weather-13#) that does this. @nikhilrayaprolu @harshit98 What do you think?

**Comment by nikhilrayaprolu** [comment]
no need to use some external API, susi supports this AFAIK, please look through susi api and its actions

**Comment by Marauderer97** [comment]
Closing this, since Susi already supports this(Intelligence Component)
