### ISSUE TITLE
Improve speech to text on search interface

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#589]
Activating voice results in a continuous activated microphone. Please test the feature on the market leader page and adapt Susper to work in a similar way. First Google shows a screen with "Speak Now" and outputs the first info in voice when there is a sidebar box, e.g. "According to Wikipedia...".

**Comment by nikhilrayaprolu** [comment]
working on this.

**Comment by mariobehling** [comment]
This is still not solved.

**Comment by mariobehling** [comment]
Still have not seen it working.

**Comment by harshit98** [comment]
What issue is happening @mariobehling ? It would be great, if you can provide some details so that we can work on it.

**Comment by nikhilrayaprolu** [comment]
closing this as same issue is referenced at https://github.com/fossasia/susper.com/issues/758 and a solution of migrating to https is proposed there.
