### ISSUE TITLE
More than *one* keyword as query makes susper slower

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#593]
**Actual Behaviour**

If query is typed like this: "Who is the president of USA?", the site hangs up or gets slower.

**Expected Behaviour**

If we type query "India", we quickly fetch the result. If a query like a sentence is typed, while typing the site should not hang up or get slower.

**Screenshots of the issue**

(Not appropriate here)

**Comment by Marauderer97** [comment]
@harshit98 Good point! I noticed this too, but is this to do with Yacy, or Susper? What can we do about this? :worried:

**Comment by harshit98** [comment]
@Marauderer97 actually, the number of frequency response being sent to the susi server are high. 
![screenshot from 2017-07-05 16-26-06](https://user-images.githubusercontent.com/22245418/27873577-38520d3a-61ca-11e7-8ef2-dfc9461087ec.png)

**Comment by harshit98** [comment]
@nikhilrayaprolu Any idea how should we improve it?

**Comment by nikhilrayaprolu** [comment]
presently SUSI is being requested for each character entry. For now, we could do one thing we can call SUSI only after results are displayed.In this way, we could decrease the count of requests to SUSI.

**Comment by nikhilrayaprolu** [comment]
and even the spell check is being called each time, this should not be the case
![image](https://user-images.githubusercontent.com/15216503/28011830-539d9b08-6581-11e7-8e01-b016fd7b7bb4.png)

**Comment by nikhilrayaprolu** [comment]
@Marauderer97 why there are 4 requests for the same query to spellcheck?
![image](https://user-images.githubusercontent.com/15216503/28011946-c73a1172-6581-11e7-918c-b20c3c95c0a1.png)
