### ISSUE TITLE
If query is empty, susper still shows intelligence.

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#594]
**Actual Behaviour**

If the query is erased/empty, the susi API still works.

**Expected Behaviour**

If the query is empty/erased, the intelligence box should not be there.

**Screenshots of the issue**

![screenshot from 2017-07-05 18-30-04](https://user-images.githubusercontent.com/22245418/27865383-0308e38e-61b0-11e7-98d8-93fb846c8e1e.png)

I would like to try out this issue. :+1:

**Comment by Marauderer97** [comment]
@harshit98 Any updates?

**Comment by harshit98** [comment]
@Marauderer97 I'm working on it. The commit which, I have done is not working.
