### ISSUE TITLE
Mobile compatibility:  Dropdown out of place at smaller sizes

### ISSUE THREAD

**Issue by Marauderer97** [fossasia/susper.com#602]
**Actual Behaviour**

Dropdown icon appears out of place in different sizes
**Expected Behaviour**

Dropdown should be placed properly

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/20185076/27914770-cb1ea40e-6281-11e7-9509-048738cc0189.png)

**Comment by Marauderer97** [comment]
Working on this :+1:

**Comment by harshit98** [comment]
@Marauderer97 Change the title of the issue and refer the mobile compatibility issue here. :)

**Comment by harshit98** [comment]
#524 can be referred here.
