### ISSUE TITLE
Mobile compatibility: Align search bar and suggestion box properly 

### ISSUE THREAD

**Issue by Marauderer97** [fossasia/susper.com#604]
**Actual Behaviour**

In Susper the search and suggestion box are not properly aligned they mismatch, and even overlap with the logo.

**Expected Behaviour**

The design should be neat and the boxes should be aligned like in loklak

**Screenshots of the issue**
![image](https://user-images.githubusercontent.com/20185076/27919580-a9e8f2f4-628f-11e7-9703-890876f35699.png)
![image](https://user-images.githubusercontent.com/20185076/27919595-bb323b7e-628f-11e7-90eb-9ec968b7b2db.png)

**Comment by Marauderer97** [comment]
Working on this :+1:

**Comment by Marauderer97** [comment]
Waiting for PR #599 to get merged to start working on this

**Comment by harshit98** [comment]
#524 can be referred here.

**Comment by Marauderer97** [comment]
Waiting for PR #626 to get merged, otherwise the suggestion box will have to be adjusted accordingly again
