### ISSUE TITLE
"No Results" message displayed before actual results are displayed

### ISSUE THREAD

**Issue by Marauderer97** [fossasia/susper.com#605]
**Actual Behaviour**
"No Results" message is first displayed before the actual results are displayed
**Expected Behaviour**
The "No Results" message should not be displayed first

**Screenshots of the issue**
![image](https://user-images.githubusercontent.com/20185076/27927785-81a3544a-62aa-11e7-84ac-3cb6a13c27d9.png)

**Comment by harshit98** [comment]
@Marauderer97 Nothing happens when I tried to reproduce the error.
