### ISSUE TITLE
Improving autocorrect UI

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#609]
**Actual Behaviour**

![screenshot from 2017-07-07 14-33-47](https://user-images.githubusercontent.com/22245418/27951096-5e68cbf0-6321-11e7-9da8-c8a7e9fe67b3.png)

**Expected Behaviour**

It should follow market leader -
![screenshot from 2017-07-07 14-33-40](https://user-images.githubusercontent.com/22245418/27951111-6aba9884-6321-11e7-80ff-e7f6ea93164c.png)

I would like to work on this. :+1:

**Comment by Marauderer97** [comment]
@harshit98 I addressed this in my original PR implementing auto correct, since Susper has an overall blue thing, I thought the colors should be blue and black, instead of red and blue

**Comment by harshit98** [comment]
![screenshot from 2017-07-07 17-04-51](https://user-images.githubusercontent.com/22245418/27956222-6bb8effa-6336-11e7-9951-ce8c8663af84.png)

I was working on it. It looks good.
