### ISSUE TITLE
If query is correct, auto correct still displays.

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#610]
**Actual Behaviour**

If a query is correct, auto correct is still responding. It is happening with `query=india`

![screenshot from 2017-07-07 14-36-01](https://user-images.githubusercontent.com/22245418/27951217-be65f974-6321-11e7-8eb3-61fab6d3cd26.png)

**Expected Behaviour**

It should not display auto correct if the spelling of query is correct.

**Comment by harshit98** [comment]
To reproduce this error : 
1 ) type `belrin` as query and see the autocorrect pops up.
2 ) erase the query and type `india`, it will show auto correct again. 

(if we type query as `india` for first time, this error does not happen)

**Comment by Marauderer97** [comment]
working on this.
