### ISSUE TITLE
Proper alignment in videos section

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#612]
**Actual Behaviour**

![screenshot from 2017-07-07 14-47-57](https://user-images.githubusercontent.com/22245418/27951671-51ed6b9a-6323-11e7-955d-079e24a90740.png)

**Expected Behaviour**

Results should be aligned properly.

I would like to work on this. :+1:

**Comment by Marauderer97** [comment]
The reason this was left like this was so that it is similar to the  alignment of images, once the thumbnail feature was implemented

**Comment by harshit98** [comment]
@Marauderer97 so should we proceed or wait until thumbnail feature has been implemented?
