### ISSUE TITLE
Susper is loading URLs which are dangerous.

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#622]
**Actual Behaviour**

When I try to search for the query as `gif` under images section, the browser blocks the site due to security issues. 

**Expected Behaviour**

Susper should not load URLs which are harmful to users security. 

**Screenshots of the issue**

1) Type query as `gif`.
2) Results under 'All' will be loaded without any error. If user switches on 'images' tab, the Susper gets blocked by the browser. This only happens with query `gif`.

![screenshot from 2017-07-09 03-13-59](https://user-images.githubusercontent.com/22245418/27989405-7297a738-6455-11e7-84a1-f989e732810c.png)

@nikhilrayaprolu  @Marauderer97 I need your inputs here regarding this issue.

**Comment by nikhilrayaprolu** [comment]
@Orbiter any suggestion regarding this? this means that Yacy indexes deceptive sites.

**Comment by harshit98** [comment]
Closing this issue, since it has been solved from the backend side.
