### ISSUE TITLE
Image search shows empty images and structure messed up

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#634]
The image search shows result images that do not exist and therefore have empty/failed image tags.

The next page results are clickable but don't show new results - as there are none.

Expected: A proper image result page with only available images and if there are no more images, there should be no option for previous and next pages.
![screenshot from 2017-07-12 12-47-11](https://user-images.githubusercontent.com/1583873/28114321-a3e10e6c-6700-11e7-96f6-b5fb8216393c.png)

**Comment by harshit98** [comment]
@mariobehling This issue seems to be fixed now. 

![screenshot from 2017-07-27 08-20-36](https://user-images.githubusercontent.com/22245418/28652285-8b2bff58-72a4-11e7-9d8d-e1ef15ea8380.png)

**Comment by harshit98** [comment]
This issue is fixed after implementing infinite scroll feature. Though, images with broken link still persist to load and can be followed here #277

**Comment by ajayns** [comment]
![image](https://user-images.githubusercontent.com/20743219/31004306-77b61914-a511-11e7-98a1-c2d4294a0bb9.png)
The no results block is not positioned correctly. I'd like to help! @harshit98 @mariobehling

**Comment by harshit98** [comment]
Sure @ajayns. Please go ahead. :)

**Comment by praveenojha33** [comment]
Hello @mariobehling This PR https://github.com/fossasia/susper.com/commit/f57a89ff38b247086ccf677900d3a570a2c2029a might fix this issue but actually changes introduced in it is not working due to this issue.

**Comment by praveenojha33** [comment]
![issue](https://user-images.githubusercontent.com/25537606/39797475-ddc4b3ca-5379-11e8-8d96-1c098de73671.png)
This issue appears on susper.com

**Comment by praveenojha33** [comment]
![fixed](https://user-images.githubusercontent.com/25537606/39797506-f54af626-5379-11e8-9939-07fa8a7afa71.png)
It does not appear locally.
