### ISSUE TITLE
Implement statistic info box similar to loklak

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#635]
loklak.net often shows an interesting info box. Yacy also offers additional information for info boxes such as files types, provider and authors. Please implement an infobox with this data similar to loklak. Also show a distribution of search results according to dates - distributed in a column chart.

**Comment by Marauderer97** [comment]
I would like to try this issue

**Comment by nikhilrayaprolu** [comment]
@Marauderer97 :+1:

**Comment by Marauderer97** [comment]
If anyone else is free, please try this issue, right now I am committed to making Susper Mobile friendly

**Comment by nikhilrayaprolu** [comment]
sure I am working on this. :+1:

**Comment by harshit98** [comment]
@nikhilrayaprolu What else features are being left to be implemented regarding this issue?

**Comment by nikhilrayaprolu** [comment]
@harshit98 Date feature which shows graphs in week/month format is required. another issue is raised regarding this at https://github.com/fossasia/susper.com/issues/728

**Comment by nikhilrayaprolu** [comment]
closing this as we can follow #728 for the required change.
