### ISSUE TITLE
At smaller screen size, search button is not working.

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#637]
**Actual Behaviour**

Clicking on the search button icon does not show results.

**Expected Behaviour**

It should show results when search icon has been clicked.

**Screenshots of the issue**

![screenshot from 2017-07-12 18-44-14](https://user-images.githubusercontent.com/22245418/28119411-697c1bea-6732-11e7-9a3b-132c1f109b26.png)

Reference issue: #651

**Comment by Marauderer97** [comment]
@harshit98 Great observation, but please change the title to Search button is not working, it is causing a slight confusion

**Comment by Marauderer97** [comment]
@harshit98 Actually I realised search button is not working at any dimension, correct me if I am wrong, but look at this:
![image](https://user-images.githubusercontent.com/20185076/28229742-9a83148e-6901-11e7-9676-abcd5e452fcb.png)
Working on this :+1:
