### ISSUE TITLE
For query "Hello", intelligence component should not be shown.

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#644]
**Actual Behaviour**

When `query=hello` then -
![screenshot from 2017-07-14 05-42-57](https://user-images.githubusercontent.com/22245418/28192998-70db78d8-6857-11e7-9572-a9f4bb43e54e.png)

If `query=hello susper` then -
![screenshot from 2017-07-14 05-42-12](https://user-images.githubusercontent.com/22245418/28193005-7aa67642-6857-11e7-850e-eac99baf4d7c.png)

**Expected Behaviour**

- for query `hello susper`, intelligence component should be shown.
- for query `hello`, intelligence component should not be shown. (because it displays result as "Hi, I'm Susi")

**Comment by Marauderer97** [comment]
@harshit98 Should we do this by manually accessing susi responses, or is there some better way? @nikhilrayaprolu what do you think? I would like to try working on this

**Comment by harshit98** [comment]
I think if there are responses from SUSI like: 
- Hi, I'm Susi
- Hello!

Then I think it's better we can place if/else condition to avoid this issue. @Marauderer97 @nikhilrayaprolu

**Comment by Marauderer97** [comment]
@harshit98 Can we just remove all instances of susi and replace it with susper?

**Comment by Marauderer97** [comment]
What I mean is, isn't this better?
![image](https://user-images.githubusercontent.com/20185076/28239667-56fd3d5a-698f-11e7-8455-81b686e8af30.png)

**Comment by mariobehling** [comment]
Irrelevant issue.
