### ISSUE TITLE
make speech UI responsive

### ISSUE THREAD

**Issue by nikhilrayaprolu** [fossasia/susper.com#647]
speech UI doens't fit perfectly on mobile devices and small screens.
![image](https://user-images.githubusercontent.com/15216503/28202262-28b75cee-6892-11e7-93e4-f6fd775a360d.png)

**Comment by harshit98** [comment]
@nikhilrayaprolu On smaller screen size, Google does not provide voice search feature when **opened in a Chrome browser for Android or iOS**. 

Note - Although, Google provides voice search feature only in it's **Google Now** built-in app.

**Comment by nikhilrayaprolu** [comment]
closing this as same issue is at https://github.com/fossasia/susper.com/issues/668
