### ISSUE TITLE
Results per page not working

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#661]
Results per page is buggy:
1. The number of results cannot be changed when instant results is set to "always on"
2. When it is set to "Never show instant results" the number of results per page can be changed, but when the user performs a search it is still set to the standard "10 results per page"
![screenshot from 2017-07-17 20-01-58](https://user-images.githubusercontent.com/1583873/28282537-0da32ec4-6b2b-11e7-95a1-8a66324fb62e.png)

**Comment by harshit98** [comment]
- When instant results are ON then it should show results per page 10 similar to market leader.
- Yes, the feature results per page do not work when instant results are turned OFF. 

@nikhilrayaprolu I tried to solve the issue. Maybe the bug has been generated after merge of #624
