### ISSUE TITLE
Related Searches: Issue with distribution of suggestions with longer suggestions

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#664]
The suggestions are not distributed in one line anymore when a suggestion is longer than usual. Please ensure related searches show results in one line.

![screenshot from 2017-07-18 10-34-09](https://user-images.githubusercontent.com/1583873/28307938-eb1b878c-6ba4-11e7-8dea-a8a2a2898940.png)

**Comment by harshit98** [comment]
Working on it. :+1:
