### ISSUE TITLE
Result page not responsive

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#669]
The result page still has issues on mobile screens, e.g. 
* search bar is partly off-screen
* search results should not be indented on left wasting screen space
* the previous/next bar if partly off-screen
* drop-down menu off-screen
* on image page photos are not filling screen

![screenshot_2017-07-18-23-16-49](https://user-images.githubusercontent.com/1583873/28340284-7142a8da-6c0f-11e7-9ce0-c7c290a4d0e3.png)

![screenshot_2017-07-18-23-14-46](https://user-images.githubusercontent.com/1583873/28340292-78d80f0e-6c0f-11e7-9acb-035d69667419.png)

**Comment by Marauderer97** [comment]
Working on this :+1:
