### ISSUE TITLE
"Did you mean..." still responds when clicked on related search.

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#672]
**Actual Behaviour**

For query `India` and if I click on the related search like `Mumbai`, even though the spelling of query is correct- the auto correct still shows up.  

**Expected Behaviour**

If spelling of query is correct, it should not display "Did you mean..."

**Screenshots of the issue**

![screenshot from 2017-07-19 19-08-29](https://user-images.githubusercontent.com/22245418/28370361-bafe8432-6cb7-11e7-8c57-24bb1132797b.png)

**Comment by nikhilrayaprolu** [comment]
working on this.

**Comment by nikhilrayaprolu** [comment]
@Marauderer97 is there any way we could add custom words like this into the API used?

**Comment by Marauderer97** [comment]
@nikhilrayaprolu No, as far as I know, we cannot. If we can find a better API for autocorrect. we can replace the current one pretty easily though

**Comment by harshit98** [comment]
@Marauderer97 @nikhilrayaprolu 

Even if I type a correct query, still autocorrect API responds. It would be better to find other external API for autocorrect.

![screenshot from 2017-07-27 07-40-55](https://user-images.githubusercontent.com/22245418/28651383-2f4ae442-729f-11e7-8437-0d55c0215ca6.png)

**Comment by nikhilrayaprolu** [comment]
I have proposed using http://hunspell.github.io/ for this at that time, since it is widely used by many popular projects.

**Comment by nikhilrayaprolu** [comment]
I have asked the hunspell community regarding this, one can follow the thread at https://github.com/hunspell/hunspell/issues/518

**Comment by harshit98** [comment]
Closing this issue because it is not occurring anymore.
