### ISSUE TITLE
Intelligence component takes time to display answer when voice search is attempted.

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#677]
**Actual Behaviour**

When a voice search is made `height of trump`, the intelligence component displays his height. Again when a voice search is made `who is president of USA` then search results are loaded but intelligence component takes at least 1-2 min to respond.

**Expected Behaviour**

_Intelligence component should not get delayed in displaying the answer._

**Screenshots of the issue**

(Not applicable here)

**Comment by praveenojha33** [comment]
@harshit98 Please close this if it is done.
