### ISSUE TITLE
 Pagination shifts from it's original position.

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#68]
Searching images more than 3 - seems good. Pagination remains in it's position. But, searching images less than 3 - the pagination shifts from it's position upwards. Here are the screenshots - 
![screenshot from 2017-02-15 18-31-16](https://cloud.githubusercontent.com/assets/22245418/22976059/1cd46e38-f3af-11e6-8f35-348be4722fd2.png)
![selection_003](https://cloud.githubusercontent.com/assets/22245418/22976109/5247a15c-f3af-11e6-9c89-190ac32e1154.png)

**Comment by Marauderer97** [comment]
@harshit98 Do you want to work on this?

**Comment by harshit98** [comment]
@Marauderer97 I'll give it a try! :)

**Comment by harshit98** [comment]
@Marauderer97 I tried to fix it, but I'm unable to understand. I think pagination seems to be okay (I have included the screenshot), but the only thing that disturbs it- is maybe the pictures which are being rendered. Also, these pictures are not linked. Clicking on them happens nothing! Suggestions are welcomed :)
![screenshot from 2017-02-19 07-53-18](https://cloud.githubusercontent.com/assets/22245418/23098617/24ddc620-f679-11e6-82ad-2912f30c8f22.png)

**Comment by Abhi2424shek** [comment]
Clicking on them should open a pop-up like the one on Google search imo, with a link to the image, image name and other things :P Well I think you could put the parent div of the images to occupy complete width thereby the pagenation would never overlap.

**Comment by harshit98** [comment]
@Abhi2424shek Oh got it. I tried it. It worked. Will be making new PR soon. :)
