### ISSUE TITLE
Search icon hidden initially

### ISSUE THREAD

**Issue by Marauderer97** [fossasia/susper.com#680]
![image](https://user-images.githubusercontent.com/20185076/28489641-d136055c-6ee4-11e7-8ce2-8b17bb09481f.png)
Search icon is initially hidden when the result page is loaded(in mobiles)
It re-appears on refreshing the page
![image](https://user-images.githubusercontent.com/20185076/28489649-1307edba-6ee5-11e7-8a9a-f4d2317c766a.png)

Working on this :+1:

**Comment by Marauderer97** [comment]
Hitting a road block here. 
![image](https://user-images.githubusercontent.com/20185076/28498331-47e47da4-6fb8-11e7-870a-037492b0b2b1.png)

![image](https://user-images.githubusercontent.com/20185076/28498316-134d3efa-6fb8-11e7-885c-18654c011d9e.png)

Can anybody suggest what is happening here, been stuck on this for a while :worried:

**Comment by nikhilrayaprolu** [comment]
@Marauderer97 can you specify the screen size you are testing at? I am not able to replicate this error

**Comment by hpdang** [comment]
I am also having this issue. It happens on small screens. It is a high priority.

**Comment by Marauderer97** [comment]
@nikhilrayaprolu Try any screen size below 600px width to replicate this

**Comment by harshit98** [comment]
Actually, on smaller screen size the search icon is not hidden.

![screenshot from 2017-08-01 17-16-24](https://user-images.githubusercontent.com/22245418/28826034-2134297c-76e6-11e7-811d-3e6cebca8ce2.png)

The microphone icon is overlapping the search icon.

**Comment by nikhilrayaprolu** [comment]
@Marauderer97 can you please record a screenshot and show how we can replicate this issue.

**Comment by harshit98** [comment]
I am working on this issue. :+1:

**Comment by harshit98** [comment]
@Marauderer97 Why I'm not able to change the width of search bar? It's just, the search icon is getting out of screen size.

![screenshot from 2017-08-02 10-54-11](https://user-images.githubusercontent.com/22245418/28858825-fc623388-7770-11e7-885d-3196b2d6ebbc.png)

Also, you have used: 

`@media screen and (max-width: 764px) {
  #nav-group {
    width: 96vw !important
  }
}`

Can you please fix this? Since you have done most of the work on it.

**Comment by Marauderer97** [comment]
This issue doesn't seem to be occurring anymore, so closing it
