### ISSUE TITLE
Code Maintainability: Arrange the services and components in a separate folder

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#689]
**Actual Behaviour**

There are a lot of services inside `src/app/`

**Expected Behaviour**

Create a separate folder for the services and a separate folder for the components to easily distinguish between them.

**Screenshots of the issue**
(Not applicable here)

**Comment by nikhilrayaprolu** [comment]
@harshit98 I would suggest making similar to loklak_search, https://github.com/fossasia/loklak_search/tree/master/src/app

**Comment by harshit98** [comment]
Working on it. :+1:
