### ISSUE TITLE
Add meta tags for the general purpose information

### ISSUE THREAD

**Issue by nikhilrayaprolu** [fossasia/susper.com#695]
Add additional meta tags for the general information on the browser and devices similar to loklak
https://github.com/fossasia/loklak_search/pull/457
https://github.com/fossasia/loklak_search/issues/455

**Comment by harshit98** [comment]
Working on this.

**Comment by nikhilrayaprolu** [comment]
@harshit98 the main motive of this issue is for SEO.
please follow up with these works on loklak and implement similarly
https://github.com/fossasia/loklak_search/issues/311
https://github.com/fossasia/loklak_search/issues/456
https://github.com/fossasia/loklak_search/issues/452

**Comment by harshit98** [comment]
@nikhilrayaprolu ok. Working on it.

**Comment by harshit98** [comment]
@nikhilrayaprolu Meta tag has been added. But I didn't understood changing titles dynamically. I have done some changes in my PR now. Please review.

**Comment by nikhilrayaprolu** [comment]
@harshit98 when ever we show results , we could change the title of the tab to the query made by the user,  
![image](https://user-images.githubusercontent.com/15216503/28831552-7b669036-76f7-11e7-84b0-440fd88dd4c7.png)

here you could check that the title of the tab is **India- Google Search**
