### ISSUE TITLE
Pagination bar not appearing properly

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#698]
**Actual Behaviour**

Currently pagination bar seems to be not getting displayed properly.

**Expected Behaviour**

Pagination bar should appear on mobile screen size.

**Screenshots of the issue**

![screenshot_20170731-091859](https://user-images.githubusercontent.com/22245418/28805955-ec7f2f8e-768a-11e7-8f76-16f84e180292.png)

**Comment by Marauderer97** [comment]
@harshit98 Can you please specify the dimensions, it is working on my phone
![image](https://user-images.githubusercontent.com/20185076/28821495-42775144-76d3-11e7-9c9d-2a4a5b551556.png)

**Comment by harshit98** [comment]
@Marauderer97 My browser wasn't updated. I have updated it now and Susper is running perfectly. Closing this issue.
