### ISSUE TITLE
implementing 404 page

### ISSUE THREAD

**Issue by nikhilrayaprolu** [fossasia/susper.com#7]
when we type a url which isn't present , the site isn't rendering us anything in router-outlet. a 404 error page implementation would make this fixed

**Comment by Bhargavasomu** [comment]
@nikhilrayaprolu @mariobehling I would like to work on this issue.

**Comment by nikhilrayaprolu** [comment]
@Bhargavasomu you can proceed on this.

**Comment by isuruAb** [comment]
I have #14  this solution.could you please check that

**Comment by nikhilrayaprolu** [comment]
@isuruAb thank you for your pull,can you make the page look good(instead of just "not found works")
![image](https://cloud.githubusercontent.com/assets/15216503/22324783/214255ea-e3d1-11e6-87bb-edb7a3095112.png)

or 
![image](https://cloud.githubusercontent.com/assets/15216503/22324805/39a5374c-e3d1-11e6-8120-d0def74518d2.png)

addition of index route below the 404 image will add the search bar even in the 404 page similar to github.

**Comment by isuruAb** [comment]
@nikhilrayaprolu working on it. will send another pull asap.Is there any recommended UI framework to use ?

**Comment by nikhilrayaprolu** [comment]
For now we are using bootstrap , so  you could continue using it

**Comment by nikhilrayaprolu** [comment]
@isuruAb any updates on this?

**Comment by isuruAb** [comment]
@nikhilrayaprolu I have made a 404 page with simple background pic.but repository is not working now.can you check it

**Comment by nikhilrayaprolu** [comment]
@isuruAb can you point out the errors you are facing

**Comment by isuruAb** [comment]
I just get a new clone of repository and run. this is the result I got.
![screenshot from 2017-01-30 13-25-46](https://cloud.githubusercontent.com/assets/7692626/22415793/08d87738-e6f0-11e6-8d54-d5731bec4272.png)

**Comment by nikhilrayaprolu** [comment]
@isuruAb change the base href tag in index.html from '/susper.com/' to '/'

**Comment by isuruAb** [comment]
@nikhilrayaprolu  I have #30 this solution. can you check that pull.do i need to keep this `/susper.com/` as it is

**Comment by nikhilrayaprolu** [comment]
#30 solved this issue.
