### ISSUE TITLE
Related Searches are shown even if there are no related searches

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#700]
Related Searches are shown even if there are no related searches. Expected: Only show related searches if available.
![screenshot from 2017-08-01 08-13-16](https://user-images.githubusercontent.com/1583873/28811761-7f986d84-7691-11e7-8b00-3942bd58896d.png)

**Comment by Marauderer97** [comment]
Fixing this immediately :+1:

**Comment by harshit98** [comment]
Solved in #701. This can be closed now.
