### ISSUE TITLE
Image overlap with 'did you mean?'

### ISSUE THREAD

**Issue by Marauderer97** [fossasia/susper.com#702]
**Actual Behaviour**

The first row of images overlaps with the 'Did you mean: ' message

**Expected Behaviour**

This should be avoided

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/20185076/28822571-588396a6-76d7-11e7-87d0-9db0e44d7bfe.png)

Working on this :+1:

**Comment by harshit98** [comment]
Better to remove it. Google does not show did you mean feature in the images section.

**Comment by nikhilrayaprolu** [comment]
working on this.
