### ISSUE TITLE
Settings of Susper is not working on mobile phones.

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#709]
**Actual Behaviour**

The settings feature of Susper is not working when touched.

**Expected Behaviour**

On touch, it should work as it works for desktop.

**Screenshots of the issue**

![screenshot_20170803-133514](https://user-images.githubusercontent.com/22245418/28912185-e275c2ce-7850-11e7-9d6e-3b2887678751.png)

**Comment by harshit98** [comment]
@nikhilrayaprolu @Marauderer97 We can install hammer.js dependency to solve this issue. Refer: http://hammerjs.github.io/

**Comment by nikhilrayaprolu** [comment]
![image](https://user-images.githubusercontent.com/15216503/28915988-66b81be2-785e-11e7-962f-7304f7382369.png)

It is working for me.

**Comment by harshit98** [comment]
@nikhilrayaprolu @Marauderer97 Please test this issue. When I check it for all the screen sizes, it is working but when I test it on my smartphone, the settings option does not work.

**Comment by nikhilrayaprolu** [comment]
@harshit98 yes I am facing the same issue on my smart phone.

**Comment by harshit98** [comment]
@Marauderer97 @nikhilrayaprolu I'm not able to understand this issue why this is happening. Everything in the code looks good to me.

**Comment by nikhilrayaprolu** [comment]
@Marauderer97 any idea regarding this, even I am not able to figure this out.
