### ISSUE TITLE
Indentation not proper. 

### ISSUE THREAD

**Issue by troublemagnet** [fossasia/susper.com#710]
**Actual Behaviour**

When I opened susper.com, the susper logo on the top left corner wasn't really visible properly.

**Expected Behaviour**

It should be properly located.

**Screenshots of the issue**

![screenshot from 2017-08-03 18-00-52](https://user-images.githubusercontent.com/28952053/28922040-3274f996-7876-11e7-9668-ad38cf0960a9.png)

**Comment by harshit98** [comment]
@troublemagnet Please provide us the details regarding viewport so that we can work on it.

**Comment by harshit98** [comment]
Working on this issue :+1:

**Comment by harshit98** [comment]
@Marauderer97 Please refer this issue in your PR #720

**Comment by harshit98** [comment]
This issue is solved in #720  and can be closed.
