### ISSUE TITLE
Make footer responsive

### ISSUE THREAD

**Issue by Marauderer97** [fossasia/susper.com#713]
**Actual Behaviour**
Footer in Susper is not responsive at small mobile sizes

**Expected Behaviour**
Footer needs to have properly aligned links in mobile view like in loklak.net

**Screenshots of the issue**
In Susper:
![image](https://user-images.githubusercontent.com/20185076/28992837-ece3c9ca-79c4-11e7-99ab-78b7096a8b5d.png)
![image](https://user-images.githubusercontent.com/20185076/28992845-14af9d6c-79c5-11e7-8db0-3a5370fbcee6.png)

**Comment by harshit98** [comment]
This issue can be closed now.
