### ISSUE TITLE
Result Page: Results are not displayed according Date or Context Rating

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#714]
Changing date or context rating does not change anything. Seems not working.
![screenshot from 2017-08-05 12-47-26](https://user-images.githubusercontent.com/1583873/28994964-5ec2207a-79dc-11e7-8076-b2668193bbf8.png)

**Comment by Marauderer97** [comment]
@mariobehling This issue was raised in #500, where we all had a discussion according to which we felt the error seems to be from Yacy side.

**Comment by harshit98** [comment]
@Marauderer97 Context ranking and sort by date is now working here too: http://search.yacy.net/

**Comment by harshit98** [comment]
@nikhilrayaprolu I tried solving this issue using `urldata.sort = 'published_date desc'` but it seems to be not working. 'last_modified desc' seems to be not working now.

**Comment by nikhilrayaprolu** [comment]
@harshit98 yes, adding a sort attribute is not working, in http://search.yacy.net/, it is implemented by appending a `/date` to the query. so you can proceed by doing something similar.
![image](https://user-images.githubusercontent.com/15216503/29024552-376f51d6-7b90-11e7-88f0-fd7b37938f51.png)
