### ISSUE TITLE
Fix margin for autocorrect and results

### ISSUE THREAD

**Issue by Marauderer97** [fossasia/susper.com#718]
**Actual Behaviour**

Results for videos is skewed. Auto correct alignment is skewed everywhere

**Expected Behaviour**

Correctly align all components

**Screenshots of the issue**
![image](https://user-images.githubusercontent.com/20185076/29003103-1aaa8f74-7ace-11e7-860f-ff7024a9c120.png)

Working on this :+1:

**Comment by harshit98** [comment]
Please refer all new issues regarding mobile compatibility to #524

**Comment by harshit98** [comment]
Please reopen this issue. It is still not solved. 


![screenshot from 2017-08-08 22-02-20](https://user-images.githubusercontent.com/22245418/29083169-62fbb51a-7c85-11e7-80a4-bc48bb004eca.png)

**Comment by nikhilrayaprolu** [comment]
@Marauderer97 please look at this error and fix it early.

**Comment by harshit98** [comment]
I'm working on this. :+1

**Comment by harshit98** [comment]
This issue can be closed now. Fixed in #741
