### ISSUE TITLE
Typing on start page search box does not move search bar anymore

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#722]
Expected just like with loklak and Google search bar should move up.

![screenshot from 2017-08-08 01-47-54](https://user-images.githubusercontent.com/1583873/29050366-bbba5ef4-7bdb-11e7-900c-960b22229649.png)

**Comment by nikhilrayaprolu** [comment]
@mariobehling similar to google we have implemented a customisable option to choose whether the user requires instant results or not. to have instant results please go to search settings. 
![image](https://user-images.githubusercontent.com/15216503/29057544-cd795f4e-7c28-11e7-8a4d-4ba08c02bea2.png)
and select always show instant results.
![image](https://user-images.githubusercontent.com/15216503/29057559-df455336-7c28-11e7-8dcd-3d782eb0c003.png)

**Comment by harshit98** [comment]
@mariobehling Should we then keep instant result feature as default?

**Comment by nikhilrayaprolu** [comment]
@harshit98 what does google has as default, for me, I don't have instant results as default. Is it same with all browsers.

**Comment by nikhilrayaprolu** [comment]
@harshit98 shall we close this issue, since activating instant search moves the search bar to top?
or shall we make instant results as default.

**Comment by harshit98** [comment]
@nikhilrayaprolu We should make instant results as default. I will make it just function like Loklak Search. I'm working on this. 👍
