### ISSUE TITLE
Lot of empty space being left over at the end of results.

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#724]
**Actual Behaviour**

Due to recently implemented statistics box, a lot of space is being left between the last result of the page and pagination bar.

**Expected Behaviour**

There should not be so much empty space. The design should look clean.

**Screenshots of the issue**

![screenshot from 2017-08-09 08-22-25](https://user-images.githubusercontent.com/22245418/29103270-38f07452-7cdc-11e7-8683-e0818c65347c.png)

@mariobehling @nikhilrayaprolu @Marauderer97 Need some discussion here regarding this issue.

**Comment by Marauderer97** [comment]
One solution is to hide the Analytics box, and show it with a toggle button that reads 'Show Analytics'

**Comment by harshit98** [comment]
Closing this issue, it is not occurring anymore.
