### ISSUE TITLE
Match design and width of search areas to market leaders

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#729]
The exact width and design of search results is still different. Please ensure the following is correct:
* Search result link text is matching market leader and never longer than expected
* Search result description text is matching market leader and font size and design is same
(Google)
![screenshot from 2017-08-10 23-03-01](https://user-images.githubusercontent.com/1583873/29192213-e8ee19f0-7e20-11e7-9df7-e36786cdb5f0.png)
(Susper)
![screenshot from 2017-08-10 23-03-47](https://user-images.githubusercontent.com/1583873/29192223-edcd97ca-7e20-11e7-83a3-9e965f154993.png)

* Related searches style and distance matches

(Google)
![screenshot from 2017-08-10 23-08-28](https://user-images.githubusercontent.com/1583873/29192239-fb4d69d4-7e20-11e7-9352-e99e46eb3f36.png)
(Susper)
![screenshot from 2017-08-10 23-08-41](https://user-images.githubusercontent.com/1583873/29192244-fe980b44-7e20-11e7-9091-017b8615d9df.png)

* On large resolution the sidebar boxes are still positioned next to the search results
* The color of the diagrams should be #4285f4

(Google)
![screenshot from 2017-08-10 23-10-13](https://user-images.githubusercontent.com/1583873/29192342-683ef990-7e21-11e7-8c09-59db2a5cb219.png)
(Susper)
![screenshot from 2017-08-10 23-10-56](https://user-images.githubusercontent.com/1583873/29192348-6e4c9040-7e21-11e7-915e-65583fbcbffb.png)

* The dropdown menu has sufficient space to the right side scroll bar
* The expanded menu shows a right side edge

![screenshot from 2017-08-10 23-12-26](https://user-images.githubusercontent.com/1583873/29192397-8eaa2a00-7e21-11e7-8c1b-b1de51af5529.png)
![screenshot from 2017-08-10 23-14-04](https://user-images.githubusercontent.com/1583873/29192413-a2abdda0-7e21-11e7-9f99-b6745ff979ef.png)

**Comment by Marauderer97** [comment]
Working on results feed width, results feed formatting and color of infobox graphs

**Comment by mariobehling** [comment]
After recent commits the info boxes are now in different width.
![screenshot from 2017-08-13 13-07-20](https://user-images.githubusercontent.com/1583873/29249080-a3492d5e-8028-11e7-9cb0-0adddaffad5e.png)

**Comment by nikhilrayaprolu** [comment]
@Marauderer97 @harshit98 what is the status of this? are all subissues solved?

**Comment by dimfried** [comment]
Hi @mariobehling 
is this still a thing? I'd like to help if there's still something left :)

**Comment by harshit98** [comment]
Hi @dimfried 
You can cross-check if something we have missed, you can fix it. Let me know if you face any issue somewhere. :)

**Comment by harshit98** [comment]
@dimfried If you find any issue regarding UI/UX, you can update here. No need of opening it as a separate issue. :)

**Comment by harshit98** [comment]
@mariobehling This issue can be closed now. 👍
