### ISSUE TITLE
Remove coala from gh-pages

### ISSUE THREAD

**Issue by Abhi2424shek** [fossasia/susper.com#73]
Coala should not be on gh-pages but on the angular branch as done by @harshit98 we should remove it. It is also not working there!

**Comment by nikhilrayaprolu** [comment]
@Abhi2424shek susper-backbone https://github.com/fossasia/susper-backbone/ has been hosted on gh-pages , due to which this project has the same files from it as this is a fork of the susper-backbone.

**Comment by Abhi2424shek** [comment]
Well the gh-pages is a generated branch currently. It is unneeded to put linting there!
