### ISSUE TITLE
"Running on Local host" heading is small in README.md 

### ISSUE THREAD

**Issue by ParthS007** [fossasia/susper.com#737]
**Actual Behaviour**
"Running on Local host" heading is small in README.md 

**Expected Behaviour**
It should be large enough so that it is easily visible.

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/24358501/29240148-c97a000e-7f7c-11e7-9404-76fba27b4960.png)

**Comment by ParthS007** [comment]
I am a new contributor and want to work on this issue.

**Comment by harshit98** [comment]
@ParthS007 Hi! Good to see, you're interested in contributing in Susper. You can proceed with the issue. Please add `Step 4: Go to localhost:4200 where the application will be running locally` also after step 3.
