### ISSUE TITLE
Using facettes like "date" does not yield results in image and video tab and no results message misplaced

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#745]
Using facettes like "date" does not yield results in image and video tab. Also "no results message" is not placed in correct location. It should be in the same area as results usally.

![screenshot from 2017-08-13 15-00-08](https://user-images.githubusercontent.com/1583873/29249876-2b742378-8038-11e7-8d26-d522c749550b.png)

**Comment by Marauderer97** [comment]
Working on this :+1:

**Comment by nikhilrayaprolu** [comment]
@Marauderer97 any status regarding, I think this might require working with backend?

**Comment by harshit98** [comment]
@nikhilrayaprolu @Marauderer97 

Susper is currently not showing any images without any use of facets. This is currently happening due to images are being loaded as http. The http requests are getting blocked on Susper and hence they should be loaded in https.

**Comment by praveenojha33** [comment]
It is currently working. 
![image](https://user-images.githubusercontent.com/25537606/44143393-2809e198-a0a1-11e8-8254-ea6dd410f3cd.png)
