### ISSUE TITLE
Google shows next page instead of pagination bar in mobile devices

### ISSUE THREAD

**Issue by nikhilrayaprolu** [fossasia/susper.com#749]
![image](https://user-images.githubusercontent.com/15216503/29272694-cc169888-811e-11e7-970c-7c8de10527e8.png)

google shows next page instead of pagination bar in mobile devices, where as we show a full pagination bar,implement next page similar to google on mobile devices.

**Comment by ParthS007** [comment]
I want to work on this issue.How should I proceed ?

**Comment by nikhilrayaprolu** [comment]
@ParthS007 we have results component at https://github.com/fossasia/susper.com/tree/master/src/app/results which have code related to pagination bar, you can modify that code, to achieve the required enhancement.
Happy Coding.
