### ISSUE TITLE
Design infobox for Mobile Phones

### ISSUE THREAD

**Issue by Marauderer97** [fossasia/susper.com#750]
Currently at around 1100 px Susper hides its Infobox. We can change this by implementing a different version of the infobox for mobiles like Google does here:
![image](https://user-images.githubusercontent.com/20185076/29301647-4de04676-819b-11e7-82af-63972510f223.png)

Refer #743 
I am working on this :+1:

**Comment by Marauderer97** [comment]
![image](https://user-images.githubusercontent.com/20185076/29398569-f8f0c2d6-8342-11e7-846a-2da8c6a8f07c.png)
Currently with the order of the components, the infobox is at the bottom like this. Is this alright? My only other option is to design a new box exclusively for mobiles

**Comment by nikhilrayaprolu** [comment]
Please put it at the top of the results similar to google.
