### ISSUE TITLE
Search results from browser address bar/ search box not following standard

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#759]
If the user has Susper as standard search engine installed and puts in searches into the address bar in Chrome/Fx or search box in Firefox the search performed is "searchterm+searchterm" instead of "searchterm searchterm".

![screenshot from 2017-08-23 10-40-28](https://user-images.githubusercontent.com/1583873/29606870-cb14d01c-87ef-11e7-9ade-0a82400b2faf.png)

**Comment by harshit98** [comment]
I'm not able to reproduce this bug. @collinx Are you able to reproduce this bug?
