### ISSUE TITLE
Make documentation to Susper using Yaydoc

### ISSUE THREAD

**Issue by nikhilrayaprolu** [fossasia/susper.com#760]
Create documentation to Susper using https://github.com/fossasia/yaydoc , 
@Marauderer97 @harshit98 start working on documenting the features you have created. I will document the features I have made in Susper.

**Comment by harshit98** [comment]
@nikhilrayaprolu Sure. Working on it. 👍

**Comment by bhaveshAn** [comment]
@nikhilrayaprolu Is this issue still active. As I would like to work on this. Please tell !!

**Comment by nikhilrayaprolu** [comment]
Yes sure @bhaveshAn this issue will give you an opportunity to get complete understanding the project. please go through blogs on susper at blog.fossasia.org and you can start writing the documentation.
