### ISSUE TITLE
Code improvements and indentation.

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#761]
**Actual Behaviour**

Susper repository code has not been organized perfectly.

**Expected Behaviour**

- Organize the code.
- Indent the code where it is necessary.

**Screenshots of the issue**

(Not applicable here)

This issue is with reference with #760

**Comment by harshit98** [comment]
@Marauderer97 @nikhilrayaprolu Please add here if something else other than these tasks has to be done.

**Comment by Marauderer97** [comment]
Can we update the readme file with screenshots? 
For example:
![image](https://user-images.githubusercontent.com/20185076/29910146-5fe9f9ea-8e46-11e7-9f5c-9cc9fd5c69ee.png)
![image](https://user-images.githubusercontent.com/20185076/29910153-6bf2cbb8-8e46-11e7-8bd0-7cc97a1662fd.png)
![image](https://user-images.githubusercontent.com/20185076/29910177-851c7cc4-8e46-11e7-882e-e54d48eb2440.png)
![image](https://user-images.githubusercontent.com/20185076/29910224-bd104c3c-8e46-11e7-94c0-5095d7bb3c94.png)

**Comment by harshit98** [comment]
No need of screenshots @Marauderer97. Please follow up issue #760. Regarding, updating readme file please see what updated things can be written in it and mention them here before attempting to solve issue.

**Comment by harshit98** [comment]
@nikhilrayaprolu @Marauderer97 I didn't found any changes which has to be done in `README.md` file. So, I'm closing this issue as it has been solved completely.
