### ISSUE TITLE
Speech to text occurs multiple times

### ISSUE THREAD

**Issue by Marauderer97** [fossasia/susper.com#764]
**Actual Behaviour**

If the word is typed too fast, speech to text repeats the first few lines multiple times.

**Expected Behaviour**

This should not happen, the speech should be generated only once

**Screenshots of the issue**

Please see the video [Link](https://www.youtube.com/watch?v=3aFDJ6EDhF4)

**Comment by harshit98** [comment]
@Marauderer97 This issue can be closed. It is not happening anymore.

**Comment by 0x48piraj** [comment]
Please close this @Marauderer97
