### ISSUE TITLE
Speech feature doesnot stop after one query

### ISSUE THREAD

**Issue by Marauderer97** [fossasia/susper.com#767]
**Actual Behaviour**

If I enter a query with speech, the text to speech feature continues for the next query too.

**Expected Behaviour**

It should get activated for the first query only

**Screenshots of the issue**

Not applicable

Working on this :+1:

**Comment by collinx** [comment]
@Marauderer97 Is this issue still occurring?

**Comment by harshit98** [comment]
@collinx Basically, the description of a query which was being rendered in infobox was being uttered whenever search was attempted in voice mode. This was the feature. Since the infobox is not responding (using DBpedia), we can't work on this issue right now.

**Comment by collinx** [comment]
ok 👍 @harshit98
