### ISSUE TITLE
Load scripts via HTTPS

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#768]
**Actual Behaviour**

- There are some scripts which are being loaded as `http://` instead of `https://`.
- Some scripts are not having `http://` and `https://` both.

**Expected Behaviour**

- Change scripts from `http://` to `https://`
- Add `https://` if nothing is defined in scripts.

**Comment by vaibhavsingh97** [comment]
@harshit98 Can i work on this issue?

**Comment by mariobehling** [comment]
@vaibhavsingh97 Please go ahead.

**Comment by harshit98** [comment]
Yes @vaibhavsingh97 :)
Please go ahead.
