### ISSUE TITLE
Design Standards of Crawl Job Page #769

### ISSUE THREAD

**Issue by Hardik113** [fossasia/susper.com#769]
**Actual Behaviour**

The design standards of the crawl job page are not maintained.

**Expected Behaviour**

Please let me know the structure so that I can start working on it

**Screenshots of the issue**

![screen shot 2017-09-10 at 12 49 56 am](https://user-images.githubusercontent.com/18461983/30243188-144334b0-95c2-11e7-9efb-97e5a1e89b74.png)

**Comment by harshit98** [comment]
Hi @Hardik113. Good to see you're interested in contributing in Susper. Please implement the same design as it has been done here: http://yacy.searchlab.eu/CrawlStartExpert.html

**Comment by ajayns** [comment]
Hey! If no one is working on this issue, I'd like to try and help! @Hardik113 @harshit98

**Comment by harshit98** [comment]
@ajayns Yeah sure. Please go ahead. :)

**Comment by Remorax** [comment]
What's the status of this issue? I'd like to take it up, if no one is working on it :) @ajayns @Hardik113 @harshit98

**Comment by harshit98** [comment]
@Remorax Yes you can take this issue. Do the UI improvements similar to here: http://yacy.searchlab.eu/CrawlStartExpert.html

**Comment by Remorax** [comment]
@harshit98 Can I implement it exactly as its' given over there? With the green background color etc?

**Comment by Remorax** [comment]
![screen shot 2017-10-30 at 11 33 20 pm](https://user-images.githubusercontent.com/26062692/32187608-99f9163e-bdcb-11e7-9620-c06b140df05a.png)
![screen shot 2017-10-30 at 11 33 29 pm](https://user-images.githubusercontent.com/26062692/32187610-9a311e4e-bdcb-11e7-9a46-ba6ad7b42c87.png)
![screen shot 2017-10-30 at 11 33 38 pm](https://user-images.githubusercontent.com/26062692/32187611-9a5dd920-bdcb-11e7-99a5-08af5f2daa9e.png)
This is what I've done so far. Is it fine? @harshit98

**Comment by bhaveshAn** [comment]
Is this issue still active ? As I would like to work on this ...

**Comment by ParthS007** [comment]
@bhaveshAn I working on this due to inactivity of PR . I forgot to comment here

**Comment by Remorax** [comment]
@bhaveshAn @ParthS007 Please stop working on this. I've worked a lot for this, but I've been swamped the past few days, so please let me finish this as well.

**Comment by bhaveshAn** [comment]
@Hardik113 Please close this Issue
