### ISSUE TITLE
No search bar - blank page on Chrome

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#77]
The start page of susper is currently blank. It shows an option to add search to Firefox very shortly (on Chrome) and then only a blank white page is shown.

![screenshot from 2017-02-19 06-58-06](https://cloud.githubusercontent.com/assets/1583873/23097521/eb693da0-f670-11e6-9254-79957d92df97.png)

**Comment by BhaveshSGupta** [comment]
There is some problem in last commit, I am yet to find the cause of the problem..

**Comment by vibhcool** [comment]
There is also an error while building the project -> https://dpaste.de/sBZ7 or it is just me?

**Comment by BhaveshSGupta** [comment]
@vibhcool I am finding any error while building

**Comment by harshit98** [comment]
@vibhcool Same here. Removing just </nav> makes the site load again.

**Comment by nikhilrayaprolu** [comment]
#78 solved this
