### ISSUE TITLE
meme is not working

### ISSUE THREAD

**Issue by DeveloperAlfa** [fossasia/susper.com#771]
**Actual Behaviour**

get me a meme request sends [not clickable]path/link of the meme

**Expected Behaviour**

show the meme as an image

**Screenshots of the issue**

https://ibb.co/nrwFw5

I can work on the issue

**Comment by harshit98** [comment]
@DeveloperAlfa May I know the reason why you opened this issue?

**Comment by DeveloperAlfa** [comment]
This was an issue in the susi ai not. I opened it here

**Comment by DeveloperAlfa** [comment]
https://github.com/fossasia/chat.susi.ai/issues/803
