### ISSUE TITLE
Voice input not working since switch to https

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#772]
Voice input not working in https.

![screenshot from 2017-09-23 18-36-44](https://user-images.githubusercontent.com/1583873/30775095-3260f262-a08e-11e7-8cbb-d51cd0cf8db0.png)

**Comment by vaibhavsingh97** [comment]
@mariobehling voice input icon is missing here
![image](https://user-images.githubusercontent.com/8705386/30832543-ec7e0f92-a23a-11e7-9042-f449e09c4f95.png)
I will try to solve the issue 😄

**Comment by harshit98** [comment]
@vaibhavsingh97 In which browser you're running Susper? In Firefox, we have not added the voice feature. So there is no icon of it. The voice feature is only available for Chrome browser.

**Comment by vaibhavsingh97** [comment]
@harshit98 Ohh! I am running Firefox so no issue. 😄 I will try in chrome and try to fix this bug 😁

**Comment by collinx** [comment]
@mariobehling @harshit98 @vaibhavsingh97 I get to know about the Susper project yesterday. I looked into to the code, and have resolved this issue. 
You can view the results [here](https://susperdeploy.firebaseapp.com/)
Let me know what you think. 😄

**Comment by harshit98** [comment]
This issue can be closed now.

**Comment by collinx** [comment]
@mariobehling @harshit98 Is this issue still occurring??

**Comment by harshit98** [comment]
No @collinx. It has been fixed. :)
