### ISSUE TITLE
Firefox could not install the search engine from: https://susper.com/susper.xml

### ISSUE THREAD

**Issue by soumam007** [fossasia/susper.com#776]
**Actual Behaviour**
Firefox could not install the search engine from: https://susper.com/susper.xml

**Expected Behaviour**
Should remove google.com(my default search engine) and replace it with susper.com

**Screenshots of the issue**
[https://pasteboard.co/GMqm9C8.png](url)
![screenshot from 2017-09-28 12-57-25](https://user-images.githubusercontent.com/21683311/30954317-544c1bb4-a44d-11e7-8f7b-ffa0e064a152.png)

**Comment by harshit98** [comment]
Have you checked xml file @soumam007 ? There was a recent update in the xml file by @collinx.

**Comment by soumam007** [comment]
@harshit98 I didnt get you, please rephrase :)

**Comment by smokingwheels** [comment]
I have FireFox ESR Windows VER running in Playonlinux and I got the error.
I have no special hosts file installed.

**Comment by harshit98** [comment]
@soumam007 I will check and see what is happening and why it's not working. 👍
