### ISSUE TITLE
Susper.com not showing microphone.png in mozilla firefox

### ISSUE THREAD

**Issue by soumam007** [fossasia/susper.com#777]
**Actual Behaviour**
Susper.com not showing microphone.png in mozilla firefox

**Expected Behaviour**
microphone.png should be visible in all type of web browsers

**Screenshots of the issue**
![screenshot from 2017-09-28 13-12-56](https://user-images.githubusercontent.com/21683311/30954705-c6a3adde-a44e-11e7-97c2-80eaea1da775.png)

**Comment by mariobehling** [comment]
The reason is, because Firefox does not support TTS and STT.

**Comment by soumam007** [comment]
@mariobehling sorry for my ignorance ,thanks for the information :)
