### ISSUE TITLE
Voice Output not working with Chromium and Chrome

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susper.com#778]
Voice input now works, but output still does not.

**Comment by collinx** [comment]
@harshit98 I am able to get output from voice input, could you explain where the output is not producing?
Also, dbpedia doesn't have https domain so, it is not working.

**Comment by harshit98** [comment]
@collinx I talked to DBpedia devs. They only serve their API in `Http` not in `Https`. We need to find some another solution.

**Comment by collinx** [comment]
@harshit98 I will look into it. Will notify as I get something relevant. 😄

**Comment by praveenojha33** [comment]
@harshit98 Can you please provide details on it. How voice output works?
