### ISSUE TITLE
Navbar code repeated for each component

### ISSUE THREAD

**Issue by ajayns** [fossasia/susper.com#779]
![image](https://user-images.githubusercontent.com/20743219/31003365-f3b3d6d2-a50c-11e7-896b-eebd3698ca96.png)
This navbar, used to navigate the terms, contact and about pages is separate code written for each of the pages. I'd suggest another component be created for this navbar and that to be reused in all of these pages. 

If we're moving forward in solving this issue, I'd like to help.

**Comment by harshit98** [comment]
Hi @ajayns. There is no need of creating a separate component for it. You can close this issue. The terms, about and contact page has already been developed and responsive as well. 

It will better to focus on some other high priority issues which are currently open. They will serve as a good contribution. :)

**Comment by ajayns** [comment]
Okay @harshit98  but it's the same code that's repeated and also different styles used for each one individually, complicating stuff rather than a simple reused component with common styling. That's why I opened this issue. I'm sorry to bother you but do check it out once more but if you are still sticking to leaving this issue, mention and I'll close it. Thanks for the reply!

**Comment by harshit98** [comment]
@ajayns Yes I know the code is being repeated but it would be better to close. Creating a new component for it will require a lot of work again. It is already been developed and responsive as well. So, there is no need of creating a new component. :)

You can close this issue.

**Comment by ajayns** [comment]
Alright, understood. @harshit98

**Comment by ajayns** [comment]
Alright I understand @harshit98
