### ISSUE TITLE
Improve dropdown menu UI

### ISSUE THREAD

**Issue by ajayns** [fossasia/susper.com#781]
**Actual Behaviour**

In the dropdown menu, the logo images are of different sizes, the text links are underlined and on hover the added border causes the dropdown container itself to expand a bit.

**Expected Behaviour**

Logo images should be restricted to same width.
Text links underline should be removed.
Fix the hover issue.
Also, each text element should be centered.

**Screenshots of the issue**
![image](https://user-images.githubusercontent.com/20743219/31004001-1a0fcfe0-a510-11e7-808b-3d56fac5da26.png)

I'd like to help fix these issues.

**Comment by harshit98** [comment]
@ajayns Some few corrections from my side:
- The icons which we have used are each of 48x48 pixels. So the icons which you're referring as 'logo-images' are of same width and height. :)
- The underline action of text should be removed.
- Hover feature should not be removed. We have tried to make it similar to Google. However, I have observed one thing while hovering over `Contact`, the rectangular outline is not proper. It should be fixed and should be equal in height w.r.t other icons.
- Try center alignment of text and fix the position of `eventyay` logo.

**Comment by ajayns** [comment]
@harshit98  

* It's great that the icon dimensions are square but then when displayed they don't seem to be perfect cause of the placement of the eventyay and maybe minor such issues.
* When I mentioned about the bug with the hover issue, my suggestion was not to remove but I meant I'd see why the whole container seems resizing on hover and fix that issue, keeping the hover effect intact as per the google dropdown.

I see someone has made a PR referencing this, and will wait for him to upload screenshot and then see if I can further help.

**Comment by harshit98** [comment]
@ajayns Issue has been solved, you can close this issue.
