### ISSUE TITLE
Current webpage is not redirecting to previous page.

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#786]
**To reproduce the bug**
- Search a keyword, for e.g. `india`
- From Analytics box, click on any top provider.
- The search box will now display keyword as `india site:link`.
- Going back to previous page action is not occurring.

**Actual Behaviour**

Going back to previous webpage is not working on Susper.

**Expected Behaviour**

The webpage should redirect to previous page even if search is using top-provider link.

**Screenshots of the issue**
![screen shot 2017-10-04 at 5 12 17 am](https://user-images.githubusercontent.com/22245418/31154134-a6afb220-a8c2-11e7-98d1-b4e7873f6f37.png)

**Comment by collinx** [comment]
I would like to work on it

**Comment by collinx** [comment]
@harshit98 I would like to work on it
