### ISSUE TITLE
Removing Link from homepage to homepage

### ISSUE THREAD

**Issue by BhaveshSGupta** [fossasia/susper.com#79]
We should not have link from homepage to homepage again, from accessibility point of you, Sometime this could be confusing..

**Comment by harshit98** [comment]
@BhaveshSGupta Would you like to work on it? If yes, go ahead! :)

**Comment by BhaveshSGupta** [comment]
@haritha28  Yes there are several other changes which could be done would combine all of them together.

**Comment by harshit98** [comment]
@BhaveshSGupta You can open issue regarding to the changes to be done! :) I have fixed the link error.
