### ISSUE TITLE
UI improvements needed in Advanced Search page

### ISSUE THREAD

**Issue by Remorax** [fossasia/susper.com#794]
**Actual Behaviour**

In the advanced search page, there are a few UI-related issues:
1. The labels are not properly aligned with the text fields, its' too near the top of the text field.
2. Its' all in lowercase, which could be changed to uppercase and font size could be increased
3. The submit button is too much to the right, making it look slightly out of place. Also the font size is a bit too small.
4. The labels are in line with the headings, and they could be given a little left margin to separate it from the search headings

**Expected Behaviour**

1. The labels should be given a little top margin, so that it's properly aligned with the text fields.
2. The labels should be changed to uppercase
3. The submit button should go to the center, and the font size should be increased.
4. The labels could be given a little left margin to separate it from the search headings
**Screenshots of the issue**

The current version:
![screen shot 2017-10-26 at 4 21 06 pm](https://user-images.githubusercontent.com/26062692/32049909-8bdb1604-ba6c-11e7-8b6e-74b6fda42b3b.png)

The final output could maybe look something like this:
![screen shot 2017-10-26 at 4 34 39 pm](https://user-images.githubusercontent.com/26062692/32049917-94d77c66-ba6c-11e7-9fe2-7edcd3f74cc5.png)

I would like to work on this issue :)

**Comment by harshit98** [comment]
@Remorax We tried to make it similar to Google's advanced search.

![screen shot 2017-10-26 at 7 18 03 pm](https://user-images.githubusercontent.com/22245418/32056526-81a7967e-ba82-11e7-8457-0dbac2be7bab.png)

That was the reason:
- Advanced search button was aligned towards right.
- Label heading were in lower case.

There is no need to change UI of advanced search. You can check #769 where the crawl job page UI has been disturbed and work on it. Please close this issue. :)

**Comment by Remorax** [comment]
Oh okay :P. But Google's advanced search has the labels centered and aligned with the text field. Is it okay if I undo the aligning of the button and the label heading being in lower case, but let the margin-top remain? I really feel that it's very confusing the way it is right now :)

**Comment by harshit98** [comment]
@Remorax Yes, undo aligning of the button and the label heading being in lower case only.

**Comment by harshit98** [comment]
@Remorax You can close this issue now.
