### ISSUE TITLE
DBpedia request is getting blocked on HTTPS

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#797]
**Actual Behaviour**

The infobox (knowledge graph) in Susper was implemented using DBpedia. The requests are getting blocked on HTTPS due to which infobox seems to be not appearing in the results section. Currently, DBpedia API only works on HTTP and not on HTTPS.

**Expected Behaviour**

The infobox should appear with the fetched results.

**Screenshots of the issue**

(Not applicable here)

**Comment by bhaveshAn** [comment]
@harshit98 Can we use any of these https://alternativeto.net/software/dbpedia/ in place of DBpedia. Please let me know. Thanks !!

**Comment by harshit98** [comment]
@bhaveshAn Looks good to me. Please start a discussion regarding this issue on the gitter channel. :+1

**Comment by nikhilrayaprolu** [comment]
@harshit98 Probably, we can build a proxy to the DBpedia API that takes requests in https and makes a callback to DBpedia.
I would suggest to once get in touch DBpedia community and know if they could provide https route.

**Comment by harshit98** [comment]
@bhaveshAn Would you like to work on this issue?

**Comment by bhaveshAn** [comment]
Sure @harshit98

**Comment by harshit98** [comment]
This may help you regarding Wikidata: https://www.mediawiki.org/wiki/API:Query#Sample_query
