### ISSUE TITLE
Default box does not appears on Chrome.

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#80]
When the site loads on Firefox, it looks like this - 
![screenshot from 2017-02-19 06-13-47](https://cloud.githubusercontent.com/assets/22245418/23098097/0cd371be-f66b-11e6-9587-b79a3ee77437.png)

While on Chrome- it appears just for seconds and get disappear and ends up loading the search bar.

**Comment by nikhilrayaprolu** [comment]
@harshit98 actually this feature is only for firefox so , it dissappears on chrome, one way we could do is to stop even rendering for seconds on chrome

**Comment by sandeepm96** [comment]
Hi! I am new to the community and for getting started I have fixed this issue and created a PR. :)
