### ISSUE TITLE
Automatic Heroku Deployment with each PR

### ISSUE THREAD

**Issue by vaibhavsingh97** [fossasia/susper.com#804]
**Actual Behaviour**
Right now, user have to deploy manually and comment on thier PR

**Expected Behaviour**
Automatic Heroku deployment should be there .

**yes, i am interested to work on this issue**

**Comment by bhaveshAn** [comment]
Can you please share the progress or the idea you have in mind.

**Comment by vaibhavsingh97** [comment]
@bhaveshAn I can send PR only when anyone form maintainer can make me temp owner of heroku to make some config 😅

**Comment by harshit98** [comment]
@vaibhavsingh97 Please close this issue. Already we're deploying PRs using `npm run deploy`.

**Comment by vaibhavsingh97** [comment]
Sure👍
