### ISSUE TITLE
Add LICENSE file for this repository.

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#807]
**Actual Behaviour**

Currently, susper.com repository is not having any license.

**Expected Behaviour**

Add license file to susper.com repository.

**Screenshots of the issue**

(Not applicable here)

**Comment by ParthS007** [comment]
@harshit98  I want to work on this

**Comment by vaibhavsingh97** [comment]
@ParthS007 I think let first commer solves this issue. @harshit98 Can you please add necessary labels 😄

**Comment by harshit98** [comment]
@vaibhavsingh97 Let him try if he wants to! :)

@ParthS007 Please go ahead. You can use any license like GPL 3.0, MIT license or Apache license etc.

**Comment by bhaveshAn** [comment]
I think can be closed in relation to #809
