### ISSUE TITLE
Adding "PRIVACY" Page and linking it in the Footer

### ISSUE THREAD

**Issue by marvin08** [fossasia/susper.com#812]
**Current behavior:**
There is no page for privacy policy in the footer.

**Expected behavior:**
There should be a link to the "PRIVACY" page in the footer on the right hand side.

**Would you like to work on this issue?**
Yes.

**Comment by marvin08** [comment]
Suggestions required @harshit98 @mariobehling

**Comment by harshit98** [comment]
Yes @marvin08 please go ahead. :)

**Comment by marvin08** [comment]
:+1:

**Comment by marvin08** [comment]
@harshit98 Please tell me exactly what should be added in the Privacy Page.

**Comment by harshit98** [comment]
@marvin08 Take help from @ParthS007. He developed the privacy page of loklak_search.

**Comment by marvin08** [comment]
@harshit98 Ok :+1:
