### ISSUE TITLE
The search query is not selectable

### ISSUE THREAD

**Issue by aashutoshrathi** [fossasia/susper.com#814]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
Currently, when we click on suggestions, only the part where the text is placed is selectable and clickable.

**Expected behavior:**
Whole suggestion row should be clickable

**Screenshots**

![screen shot 11-17-17 at 05 47 pm 001](https://user-images.githubusercontent.com/21199234/32946932-8ce9e2e6-cbbf-11e7-8359-d8df5adf34e4.PNG)
![screen shot 11-17-17 at 05 47 pm](https://user-images.githubusercontent.com/21199234/32946933-8d2eac96-cbbf-11e7-8920-e82af3c64186.PNG)

**Comment by harshit98** [comment]
@aashutoshrathi Please provide screenshots and steps to reproduce the bug.

**Comment by aashutoshrathi** [comment]
@harshit98 updated with screenshots.

**Comment by harshit98** [comment]
@aashutoshrathi Would you like to work on this issue?

**Comment by aashutoshrathi** [comment]
Actually I'm still working on how to reproduce this bug, but yeah I want to work on this.

**Comment by harshit98** [comment]
@aashutoshrathi I have figured out the bug. You can start working on its fix. 👍

**Comment by aashutoshrathi** [comment]
Yes 👍

**Comment by aashutoshrathi** [comment]
@harshit98 what exactly is causing it?

**Comment by harshit98** [comment]
Maybe `<a>` tag. It is a one-line fix. :)
