### ISSUE TITLE
[UPDATE]: Angular version bump from v4.1.3 to v5.0.2

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#816]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
The current repo of Susper has Angular version v4.1.3 running.

**Expected behavior:**
Update all the packages and dependencies and upgrade to the latest version of Angular i.e. v5.0.2

**Screenshots of the issue:**
(Not applicable here)

I'm working on this issue. 👍

**Comment by bhaveshAn** [comment]
@harshit98 Is this issue still there, then I would like to work on it.

**Comment by harshit98** [comment]
@bhaveshAn Yes. Please go ahead. 
- Make sure tests should not fail.
- Once you've updated all the dependencies and upgraded to Angular v5.0.2, run tests on your machine to avoid failure of Travis CI.

**Comment by praveenojha33** [comment]
@harshit98 Please close this issue we already have an issue to upgrade the project to latest version created by you here https://github.com/fossasia/susper.com/issues/990
