### ISSUE TITLE
Images appear by clicking 2 times on 'images' tab.

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#82]
Here are the screenshots - 
First click on the image tab shows- link of the images but no images are display.

![screenshot from 2017-02-19 08-03-02](https://cloud.githubusercontent.com/assets/22245418/23098650/102b07e6-f67a-11e6-87c3-091fcb5f1b3c.png)

Second click on the image tab shows- images with no link (from the website they have been rendered).

![screenshot from 2017-02-19 08-03-22](https://cloud.githubusercontent.com/assets/22245418/23098657/4c2e5af4-f67a-11e6-8eb0-7685aff17bf8.png)

It should be similar to Google- on single click images appear with respective links.

**Comment by Marauderer97** [comment]
This is how google displays images:
![image](https://cloud.githubusercontent.com/assets/20185076/23100581/fa563b30-f6aa-11e6-8d77-5e3b4a301b9c.png)
So I am guessing by links, you meant , the link the image redirects to when clicked on?

**Comment by Marauderer97** [comment]
P.S However, the issue has been noted, the images page is being refactored as mentioned in #53, this issue will be addressed there. Thank you for your input :smile:

**Comment by harshit98** [comment]
@Marauderer97 Yes! but also, images only appear when the 'Images' tab on susper.com is clicked 2 times. :sweat_smile:

**Comment by nikhilrayaprolu** [comment]
https://github.com/fossasia/susper.com/commit/8f9ce597912a8021990143e0df7b2971ab0786b1#diff-566a81b45e1d8778f156f29c1bf39732R24
@harshit98 addition of `type="button"` in the above commit has raised this error.
I think time has come to have some tests suite as in #3 or else we will be breaking our code in each commit.

**Comment by harshit98** [comment]
@nikhilrayaprolu I don't think so. I tried removing `type="button"`. It does not solves this issue.

**Comment by harshit98** [comment]
Please close this issue, as it has been solved in PR no #88 :)
