### ISSUE TITLE
Typo in PR Template comments

### ISSUE THREAD

**Issue by aashutoshrathi** [fossasia/susper.com#825]
**I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [x] typo

**Current behavior:**
![image](https://user-images.githubusercontent.com/21199234/32987806-2f1d06a4-cd1b-11e7-8d3c-9ae8a2e932a6.png)

**Expected behavior:**
Highlighted `you` should be `your`

**Comment by harshit98** [comment]
@aashutoshrathi It does not makes any sense. Have you noticed it is just a comment ? Please stop making such issues. There are other major issues as well on which more focus has to be done.
