### ISSUE TITLE
Removing 'github' icon link from the dropdown menu

### ISSUE THREAD

**Issue by marvin08** [fossasia/susper.com#829]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
Both 'code' and 'github' icon links refer to the repository of susper.com on github.

**Expected behavior:**
Only 'code' icon link should be present in the the dropdown menu.

**Screenshots of the issue:**
(Not applicable here)

**Would you like to work on this issue?**
Yes.

**Comment by marvin08** [comment]
@harshit98 Suggestions?

**Comment by harshit98** [comment]
No need of removing it @marvin08. Please close this issue. Before opening a issue, kindly discuss it with the mentors on public channel.

**Comment by marvin08** [comment]
Ok @harshit98 :+1:.
