### ISSUE TITLE
Design Changes

### ISSUE THREAD

**Issue by BhaveshSGupta** [fossasia/susper.com#83]
We could do following do following changes
1) Alignment of the search results page(PS:the red lines), please see the image below
![alignment](https://cloud.githubusercontent.com/assets/4209637/23100408/d9da5f80-f6a5-11e6-92fd-d84cce219e86.jpg)

2) The Menu about right now works on both hover and click, we can keep it just one which would be make it easy even I feel icons are pretty huge may be we could change dropdown menu as next pic
![menu button](https://cloud.githubusercontent.com/assets/4209637/23100409/d9e814d6-f6a5-11e6-8388-579fa3dfe39d.jpg)
![menu-dropdown](https://cloud.githubusercontent.com/assets/4209637/23100413/da07d118-f6a5-11e6-9103-408ad5533a28.jpg)

3) Floater's position could be fix such that when we scroll it stays at bottom instead of moving along the scroll and we could hide the flyer in mobile or make some change such that it doesn't overlaps texts
![flyer s position](https://cloud.githubusercontent.com/assets/4209637/23100410/d9f051c8-f6a5-11e6-98eb-24b05a6c655d.jpg)
![flyerinmobile](https://cloud.githubusercontent.com/assets/4209637/23100411/d9f2e9b0-f6a5-11e6-9b7b-4df1499a21e2.png)

4) Favicon is not displayed
![favicon](https://cloud.githubusercontent.com/assets/4209637/23100412/d9f7fea0-f6a5-11e6-9479-15a57938e1ec.jpg)

All these issues are very small I would suggest first timers solving them, I am ready to help if needed.

**Comment by harshit98** [comment]
@BhaveshSGupta I can try to fix them. 1st and 2nd seems to be easy. How should I solve 3 and 4 ?

**Comment by BhaveshSGupta** [comment]
@harshit98 For 3rd one we need moderator's input as I would suggest to hide that for now from mobile devices.
and 4th one I need to check myself..

I would suggest pick any one and submit the PR and if anyone else wants to take issue the can. Still moderator's would be best to comment on this issue

**Comment by harshit98** [comment]
@BhaveshSGupta I have fixed 3rd one also. 4th is left. I have no idea about it.

**Comment by nikhilrayaprolu** [comment]
@harshit98 let the Floater be present only on index page and not on the results page.once user searches something , the floater should be removed or hided

**Comment by harshit98** [comment]
@nikhilrayaprolu done! what about the 4th one?

**Comment by Marauderer97** [comment]
@harshit98 Try doing the following.. rename susper.ico to favicon.ico, delete favicon.ico and similarly update the code to favicon.ico wherever susper.ico has been used, this should solve the problem
