### ISSUE TITLE
Implement Yaydoc docs generation in susper.com

### ISSUE THREAD

**Issue by imujjwal96** [fossasia/susper.com#832]
Yaydoc is FOSSASIA's own automatic documentation generation and deployment project. At the crux of it, Yaydoc generates a documentation website using the markdown present in a project's repository and keeps the website in sync with the changes made in project's documentation.

The project requires a .yaydoc.yml configuration file at the project's root directory. Adding necessary information in the configuration file and registering the project at https://yaydoc.herokuapp.com/ will be enough to generate the documentation website.

Objective: Create the .yaydoc.yml file in the susper.com repository and show preview Documentation website generated from the Yaydoc website.

Expected Outcome: Submit a pull request creating .yaydoc.yml file and a link to the preview page

Links: http://dev.yaydoc.org/user_manual/yaydoc_configuration.html

**Comment by marvin08** [comment]
@imujjwal96 I want to work on this issue.

**Comment by marvin08** [comment]
@imujjwal96 I think this issue was already resolved in #810. @harshit98 Your views?

**Comment by 0x48piraj** [comment]
Can I work on this ?

**Comment by imujjwal96** [comment]
Oh! I must have missed that. Thanks @marvin08 for notifying.  Closing this.
