### ISSUE TITLE
[GCI Task]: Code Formatting.

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#834]
**OBJECTIVE:**

Many parts of code in different files of the project is not properly indented. Your task is to properly indent code in any one file of the codebase. Also you have to remove extra lines, create a blank line between functions and overall make the code look neat and tidy.

**REQUIREMENTS:**

Indentation, Code formatting.

**OUTCOME:**

A pull request with a properly formatted and neat version of code of any one file of the codebase.

**LINK:**

- Checkout here: https://github.com/fossasia/susper.com
- If you have any doubts or face any difficulty then please reach out to our gitter channel: https://gitter.im/fossasia/fossasia
- Time period: 5 days.
- Type: Code.
- Code formatting and indentation related task.

**Comment by STEdirisuriya** [comment]
https://github.com/fossasia/susper.com/pull/838
