### ISSUE TITLE
[GCI Task]: Refactor the UI of the Footer and making it responsive

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#836]
**OBJECTIVE:**

Present footer in Susper is responsive but some of the features on click are not working. Refactor the code, to make it working.

**REQUIREMENTS:**

HTML, CSS, Bootstrap and Git knowledge.

**OUTCOME:**

A pull request with all the features in the footer working on desktop and mobile.

**LINK:**

Time period: 5 days.
Type: Code, Advanced Task.

**Comment by duttaditya18** [comment]
What exactly is not working?

**Comment by YashKumarVerma** [comment]
@harshit98 
the ui is already responsive 👍 
![screenshot 190](https://user-images.githubusercontent.com/14032427/34069051-6df2bd7a-e26e-11e7-8d96-1fc87bbbb997.png)
![screenshot 191](https://user-images.githubusercontent.com/14032427/34069052-6e50210e-e26e-11e7-9c92-c5d418f5cae8.png)
![screenshot 192](https://user-images.githubusercontent.com/14032427/34069053-6e9617ae-e26e-11e7-896b-08be80b5b6ba.png)
![screenshot 193](https://user-images.githubusercontent.com/14032427/34069054-6ee7004c-e26e-11e7-97f9-803e68cd88b0.png)
![screenshot 194](https://user-images.githubusercontent.com/14032427/34069055-6f4344c4-e26e-11e7-8cfd-610b430850aa.png)

**Comment by harshit98** [comment]
@duttaditya18 @YashKumarVerma The actual goal of this task is to fix this issue: https://github.com/fossasia/susper.com/issues/709

**Comment by harshit98** [comment]
Basically @duttaditya18 @YashKumarVerma , if you will observe on mobile phone screen size: the `Settings` option is not working. Hence, it may require refactoring the whole footer UI.

**Comment by abishekvashok** [comment]
@harshit98 can I work on it?

**Comment by abishekvashok** [comment]
@harshit98 done in #890 pls review, thank you.
