### ISSUE TITLE
At least, there is not anything about SUSPER on SUSPER

### ISSUE THREAD

**Issue by STEdirisuriya** [fossasia/susper.com#837]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

At least, there is not anything about SUSPER on SUSPER!

**Expected behavior:**
Please improve it.

**Screenshots of the issue:**

![issue](https://user-images.githubusercontent.com/33794760/33937346-1b4cc5da-e029-11e7-94d8-e89603e007c7.JPG)

**Comment by harshit98** [comment]
@STEdirisuriya This is not an issue related to Susper. The results are being loaded from server. Please close this issue. You can open an issue regarding any feature which is not working properly. : )
