### ISSUE TITLE
Adding feature of Gmail login to get more traffic

### ISSUE THREAD

**Issue by hardy1334** [fossasia/susper.com#844]
It will be great if Gmail login feature is added ,because from user's point of view it will be great if that user is getting queries or results based on his/her search history @Orbiter @mariobehling

**Comment by tushar-nitave** [comment]
Can you elaborate this. I mean where it should be added. Can I work on this?

**Comment by mariobehling** [comment]
@hardy1334 This feature is out of scope for the time to come.
