### ISSUE TITLE
Store the Preference of theme

### ISSUE THREAD

**Issue by agentcap** [fossasia/susper.com#853]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

The **Customization** feature provides a way to choose between the available themes, but it does not store's the selected theme, and so the user have to manually switch to the preferred theme always.

**Expected behavior:**

The theme selected by the user in **Customization** modal should be stored and made the default theme for him.

**Screenshots of the issue:**

NA

**Would you like to work on this issue?**
Yes

**Comment by agentcap** [comment]
@harshit98 can I work on this?

**Comment by harshit98** [comment]
Yes @agentcap you can work on this. 

Although I have reviewed your pull request. Good work so far! Keep it up! 🎉
