### ISSUE TITLE
Integrate Twitter API to Susper.com, Search Engine Optimization

### ISSUE THREAD

**Issue by 0x48piraj** [fossasia/susper.com#858]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

No any integration for twitter.

![image](https://user-images.githubusercontent.com/5800726/34588638-0ddd56dc-f1d4-11e7-95c9-3b82e9ed05bd.png)

**Expected behavior:**

**Complete Twitter integration for** _**susper.com**_ :heart_decoration: 

Just like I did for fossasia's official website :100: 

![image](https://user-images.githubusercontent.com/5800726/34588677-49e46cf6-f1d4-11e7-91d3-8c17e3a3968e.png)

**Screenshots of the issue:**

![image](https://user-images.githubusercontent.com/5800726/34588577-bc602708-f1d3-11e7-97c7-46be35157ed1.png)

### Will you like to work on this issue ?

**_Oh, Hell yeah!_**

**Comment by harshit98** [comment]
@0x48piraj 
- The idea is great! But what is the purpose of loklak search project?
- How it will benefit Susper?
- How it will differeniate between loklak search and susper?

**Comment by 0x48piraj** [comment]
No, I have added a separate background for it.
I mentioned because, It's being accepted in other Projects.
You can check the files :100:

**Comment by 0x48piraj** [comment]
Sir, What happened?
Please elaborate so that I can improve from next point
