### ISSUE TITLE
Resizing the logo at top-right side. 

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#86]
We should resize the susper logo - it should be little more big in size. And there is too much area between the logo and the search bar. It should also be reduced. It should have similar design just like Google have! Here are the screenshots - 

![selection_002](https://cloud.githubusercontent.com/assets/22245418/23143854/b28ef3ec-f7e9-11e6-9890-215d6ff0565c.png)

![selection_001](https://cloud.githubusercontent.com/assets/22245418/23143867/ce4e9f56-f7e9-11e6-9ee9-8e4bd8e912fb.png)

**Comment by harshit98** [comment]
@nikhilrayaprolu - Fixing the search bar- disturbs it's position on the homepage. Below are the screenshots. I made changes in `search-bar.component.css` file - under `#nav-group` Any suggestions? :)

![screenshot from 2017-02-23 21-35-51](https://cloud.githubusercontent.com/assets/22245418/23267272/429e1080-fa10-11e6-84c7-70bec68031fe.png)

![screenshot from 2017-02-23 21-36-41](https://cloud.githubusercontent.com/assets/22245418/23267289/483b96f2-fa10-11e6-9d0f-89c323c2558c.png)

**Comment by nikhilrayaprolu** [comment]
@harshit98 you could fix it in index.component.ts by changing it's position ,similarly change the positions everywhere search bar component is used.

**Comment by Marauderer97** [comment]
What is the status of the issue @harshit98 ?

**Comment by harshit98** [comment]
@Marauderer97 My Mid terms are going on. I'll be back on work from 11th March. I have stopped this work in between. But if you're interested you can fix this issue :)

**Comment by harshit98** [comment]
This issue has been solved here - #110 . I'm closing this issue.
