### ISSUE TITLE
Adding Selenium Unit Tests 

### ISSUE THREAD

**Issue by 0x48piraj** [fossasia/susper.com#860]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**
There's no **selenium unit tests** for susper.com, for testing purposes :tada: 

**Expected behavior:**
**There should be !**

**Screenshots of the issue:**
Nah! Not needed.

Ping @harshit98 @Orbiter @Remorax :100:

**Comment by harshit98** [comment]
@0x48piraj Why do we need selenium tests for Susper? We're already having unit tests.

**Comment by 0x48piraj** [comment]
Oh. I was unaware of this fact. Thanks!
