### ISSUE TITLE
Fix the broken eventyay icon

### ISSUE THREAD

**Issue by 0x48piraj** [fossasia/susper.com#861]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

Broken **eventyay** icon in menu. (Also, in wrong dimensions. Should be in `48x48`)

**Expected behavior:**
Should display and can navigate to eventyay

---
**Screenshots of the issue:**

![image](https://user-images.githubusercontent.com/5800726/34640130-13e9c4c6-f313-11e7-9a9e-435f0ba62bf5.png)

**Comment by ValentinBercaru** [comment]
Hello! Is this bug fixed?

**Comment by 0x48piraj** [comment]
See this for reference - https://github.com/fossasia/susper.com/pull/863
