### ISSUE TITLE
Fix the same navigating icons/links

### ISSUE THREAD

**Issue by 0x48piraj** [fossasia/susper.com#862]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
Same navigation to many of the icons. It distorts the UI.

**Expected behavior:**
Crystal clear navigation.

**Demo of the issue:**
![susper_bug](https://user-images.githubusercontent.com/5800726/34640206-496b9da8-f314-11e7-8ef0-ebbe2d767677.gif)

**Comment by harshit98** [comment]
@0x48piraj I didn't understood the issue well. Can you elaborate more?

**Comment by 0x48piraj** [comment]
@harshit98 Both the icons point at the same URL.

**Comment by ValentinBercaru** [comment]
Hello @0x48piraj ! I see that this issue is not resolved on susper.com. Can I make a pull request for this?

**Comment by 0x48piraj** [comment]
When @harshit98 will approve the change, I will complete it in 5 minutes, as it's a very small bug.
Also have a ref commit : https://github.com/0x48piraj/susper.com/commit/2b3a092af0d9a7af0994b1d461be9f3318d5707d 👍

**Comment by praveenojha33** [comment]
@0x48piraj Please close this issue.

**Comment by 0x48piraj** [comment]
@praveenojha33 Why ?

**Comment by 0x48piraj** [comment]
The bug is still there, so will be the issue. :+1:

**Comment by praveenojha33** [comment]
Yes I understand your concern but it was done intentionally to increase contribution. Read the conversation of devs here https://github.com/fossasia/susper.com/pull/955

**Comment by 0x48piraj** [comment]
I guess you guys are mistaken somewhere. 
First of all, there are two icons directing to same URLs, what's the intention ?
Just to fix. We can leave the Github link as it is but what about the other ?
I saw his changes, he didn't understood the issue.

**Comment by praveenojha33** [comment]
Actually there is no need of one icon. Make a PR removing one icon.
