### ISSUE TITLE
using font awesome icons and changing navbar inverse for better ui

### ISSUE THREAD

**Issue by aniket223** [fossasia/susper.com#872]
![screenshot-2018-1-9 susper](https://user-images.githubusercontent.com/21195423/34735715-6498f560-f596-11e7-9790-1c2c7d65052a.jpg)

**Comment by harshit98** [comment]
@aniket223 Kindly follow the template and give details of the issue. It is not easy to understand what you're trying to do here.

**Comment by aniket223** [comment]
@harshit98  what i have done here is added a navbar-invere so it looks better and then added then added font awesome icons to the age so it looks better.
