### ISSUE TITLE
Feature request for interactive buttons and a search button on home page.

### ISSUE THREAD

**Issue by praveenojha33** [fossasia/susper.com#873]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**
Currently the home page of search engine do not have any interactive buttons and looks vacant.The Search Results are shown on pressing Enter button.
**Suggested Modification:**
A search button can be introduced on home page of the Search Engine further an extra button can be introduced which will be link to a page having widgets like Weather,News,Today's History etc.

**Comment by harshit98** [comment]
> Currently the home page of search engine do not have any interactive buttons and looks vacant.The Search Results are shown on pressing Enter button.

The idea behind it was to follow the market leader. If you check Susper on Google Chrome browser, the search icon is hidden but if you check on Firefox, it appears to be there. This is basically a feature.

> A search button can be introduced on home page of the Search Engine further an extra button can be introduced which will be link to a page having widgets like Weather,News,Today's History etc.

Currently the topic of widgets like weather, news etc is out of scope at present.

@praveenojha33 You can close this issue.
