### ISSUE TITLE
The SUSPER image 

### ISSUE THREAD

**Issue by samyakbvs** [fossasia/susper.com#876]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

The  SUSPER is blank currently
**Expected behavior:**

The  SUSPER image should lead to about.html
**Screenshots of the issue:**

**Comment by ValentinBercaru** [comment]
Do you refeer to Susper logo from the main page?
![3f1823b6-3294-48e5-be1d-19d0fcfc78a5](https://user-images.githubusercontent.com/33882273/36396688-156d0a2e-15c8-11e8-8598-b153261ce7c2.png)

**Comment by tushar-nitave** [comment]
Can I work on it?
