### ISSUE TITLE
Add more sister projects

### ISSUE THREAD

**Issue by arjunpandey2003** [fossasia/susper.com#879]
**I'm submitting a ...**
- [ ] bug report
- [X] feature request

**Current behavior:**

less projects
**Expected behavior:**

more added
**Screenshots of the issue:**

**Comment by harshit98** [comment]
Your pull request is not acceptable. @arjunpandey2003 go through the readme file to check how to get deployment link. I have already integrated the Travis CI of the Susper with surge. So whenever Travis passes, deployment link is generated.

**Comment by samyakbvs** [comment]
I am also adding one sister project
