### ISSUE TITLE
rxJS Module calls incorrect

### ISSUE THREAD

**Issue by saarthakchats** [fossasia/susper.com#885]
**I'm submitting a ...**
- [ ] bug report

**Current behavior:**

While running `ng serve` to install Susper locally, terminal throws 'Cannot find module' errors for rxJS modules, one of the required modules for Susper (refer to screenshots below). This is due to incorrect calls of the modules. For example, there are multiple calls to `rxjs/operators/tap` inside the folder node-modules/rxjs, even though the tap file does not exist. Another example is calling operators/map
**Expected behavior:**

There are no 'Cannot find module' errors and the installation process runs smoothly
**Screenshots of the issue:**

<img width="672" alt="screen shot 2018-01-12 at 11 39 45 pm" src="https://user-images.githubusercontent.com/24372680/34889137-f19b571a-f7f2-11e7-8c05-600006924e2b.png">
<img width="670" alt="screen shot 2018-01-12 at 11 36 43 pm" src="https://user-images.githubusercontent.com/24372680/34889142-f84a7406-f7f2-11e7-9f2c-58b7e1bc11c1.png">

**Comment by abishekvashok** [comment]
Fixed in #890 @saarthakchats

**Comment by praveenojha33** [comment]
@mariobehling This issue should be closed now.
