### ISSUE TITLE
Advanced Search feature not working

### ISSUE THREAD

**Issue by saarthakchats** [fossasia/susper.com#886]
**I'm submitting a ...**
- [ ] bug report

**Current behavior:**

The Advanced Search feature is not working as there is no action upon clicking the 'Advanced Search' button even after filling out all the fields.

**Expected behavior:**

Advanced Search button works and performs a search with the queries specified.

***Reference link***
[Advanced Search Page](https://susper.com/advancedsearch)

**Comment by Tanuj9043** [comment]
@saarthakchats This functionality hasn't been added yet. You can see a "newadvancedsearch" component is used instead of "advancedsearch". I think it's functionality is yet to be written.

**Comment by praveenojha33** [comment]
Parent issue #126 . This feature has not been yet implemented. All information can be found in the parent issue.
