### ISSUE TITLE
Clicking "Sort by Date" keeps appending /date to search

### ISSUE THREAD

**Issue by jajodiaraghav** [fossasia/susper.com#892]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

Clicking "Sort by Date" keeps appending /date to search

**Expected behavior:**

/date should only be appended once to search

**Screenshots of the issue:**

![capture](https://user-images.githubusercontent.com/18749480/34941403-90874de8-fa19-11e7-98d0-ba979370b5e4.PNG)

**Comment by jajodiaraghav** [comment]
Claiming this issue

**Comment by ValentinBercaru** [comment]
I see this bug is still unsolved. I tried to solve it and now it works fine. Please assign me to it and check my changes.
