### ISSUE TITLE
Change the color of links under Top Providers douring converting to dark theme

### ISSUE THREAD

**Issue by S2606** [fossasia/susper.com#897]
**I'm submitting a ...**
- [ ] bug report
- [X] feature request

**Current behavior:**
![image](https://user-images.githubusercontent.com/18497513/35018623-7cfe13b2-fb48-11e7-9342-f80e2d4a45c6.png)

**Expected behavior:**
Change the color to white from blue

**Comment by praveenojha33** [comment]
@harshit98 I am taking this issue.

**Comment by harshit98** [comment]
Okay @praveenojha33 please go ahead. 👍
