### ISSUE TITLE
Increase Lighthouse Performance of Susper

### ISSUE THREAD

**Issue by ParthS007** [fossasia/susper.com#898]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

![image](https://user-images.githubusercontent.com/24358501/35036206-9c450572-fb99-11e7-8c9a-9d1e5a36245b.png)

**Current behavior:**
- Progressive web app
  - [x] The App does not provide fallback content when Javascript is not available.
  - [x] User is not prompted to install the Web App ( prompt for adding to home screen)
  - [x] Adding manifest.
  - [x] Address bar does not match brand colors
- Performance
  - [ ]  Does not Reduce Render-blocking script.
  - [ ]  Does not Reduce Render-blocking stylesheets.
- Accessibility
  - [ ]  Image elements do not have [alt] attributes.
  - [ ]  Form elements do not have labels.
- Best Practices
  - [ ]  Does not Opens External Anchors Using rel="noopener" .

**Expected behavior:**
All the Issue mentioned above should be resolved.

I am working on these Issue. I have made a checklist, will resolve each issue one by one 👍 
Please give suggestions @mariobehling  @harshit98 @nikhilrayaprolu

**Comment by ajayns** [comment]
@ParthS007 User will not be prompted to install webapp? Should it actually be there? User should be prompted right? Is it a typo there?
