### ISSUE TITLE
query isn't displaying in the navigation bar search

### ISSUE THREAD

**Issue by nikhilrayaprolu** [fossasia/susper.com#9]
when user searches for something ,the search bar in the results page is empty, query could be parsed  and displayed there
![image](https://cloud.githubusercontent.com/assets/15216503/22183345/0721280e-e0e2-11e6-92e4-1d2f8e9cbcd8.png)

**Comment by vishalburri** [comment]
I would like to work on this issue

**Comment by nikhilrayaprolu** [comment]
@vishalburri you can proceed on this.
