### ISSUE TITLE
Adding images in the side card in search

### ISSUE THREAD

**Issue by GingerDragon7** [fossasia/susper.com#904]
**I'm submitting a ...**
- [ ] bug report
- [X] feature request

**Current behavior:**
![screenshot from 2018-01-29 23-14-29](https://user-images.githubusercontent.com/17198965/35525409-627cebec-054a-11e8-92fb-d78073aa6a30.png)

**Expected behavior:**
![screenshot from 2018-01-29 23-14-48](https://user-images.githubusercontent.com/17198965/35525429-713c9e5c-054a-11e8-883b-4d4e41bcb90e.png)

I am working on these Issue. 
Please give suggestions @mariobehling @harshit98 @nikhilrayaprolu

**Comment by sathiraumesh** [comment]
Can i work on this issue

**Comment by tushar-nitave** [comment]
Anybody working on this?

**Comment by praveenojha33** [comment]
@GingerDragon7 What is the status of this issue. Share it ASAP.
