### ISSUE TITLE
Add a black theme as well.

### ISSUE THREAD

**Issue by STEdirisuriya** [fossasia/susper.com#914]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

No Themes

**Expected behavior:**

Add more themes

**Screenshots of the issue:**

**Comment by ValentinBercaru** [comment]
Are you referring to dark interface? If so, I'm working on this feature. I will submit a pull request these days.

**Comment by praveenojha33** [comment]
@mariobehling @ValentinBercaru This issue should be closed now.
