### ISSUE TITLE
Redesigning the site using MaterializeCSS framework.

### ISSUE THREAD

**Issue by harshit98** [fossasia/susper.com#92]
As mentioned in issue no #37 , the style of susper.com looks a bit dull. It should be attractive and eye-catching in terms of styling. Here are the screenshots - 

![selection_008](https://cloud.githubusercontent.com/assets/22245418/23391107/75af87d4-fd98-11e6-931b-5a15038ab5b5.png)

It should be styled similar to loklak.net. Also, we can add a tag-line between susper logo and search bar. We can discuss about it though if we need it. 

![selection_007](https://cloud.githubusercontent.com/assets/22245418/23391120/9829331e-fd98-11e6-82f3-4287258cafb1.png)

Result Page - 

![selection_009](https://cloud.githubusercontent.com/assets/22245418/23391132/afc99d1a-fd98-11e6-949e-0a541eefc24d.png)

![selection_010](https://cloud.githubusercontent.com/assets/22245418/23391136/b6806030-fd98-11e6-8fd7-d309a240cb3b.png)

**Comment by nikhilrayaprolu** [comment]
basically frameworks are not much preferred when data gets loaded dynamically, sometimes required functionalities may not get activated.
Also MaterializeCSS is now in beta , and doesn't have much support for frameworks which load data dynamically . I would prefer 'Angular Material' but there are a lot syntactical changes we have to do for it.
Bootstrap has a good support when comes to dynamic loading.
If you feel you could improve design of susper, start working on those changes using bootstrap.

**Comment by harshit98** [comment]
@nikhilrayaprolu I would like to work on this.

**Comment by nikhilrayaprolu** [comment]
@harshit98 you can proceed and discuss all issues regarding design changes on issue #37
