### ISSUE TITLE
Background images in the about tab page and contact tab page are not properly responsive

### ISSUE THREAD

**Issue by sathiraumesh** [fossasia/susper.com#924]
**I'm submitting a ...**
- [X] bug report
- [ ] feature request

**Current behavior:**

The background images in the contact page and about page doesn't fit to all the devices properly 

**Expected behavior:**

The background images in the contact page and about page should fit to all the devices properly 

**Screenshots of the issue:**

In mobile view
<img width="1440" alt="screen shot 2018-03-04 at 7 32 30 pm" src="https://user-images.githubusercontent.com/28914919/36946427-f4b37456-1fe2-11e8-98f1-f40ac6c6315b.png">

in laptop view
<img width="1440" alt="screen shot 2018-03-04 at 7 34 25 pm" src="https://user-images.githubusercontent.com/28914919/36946439-1ce63116-1fe3-11e8-9a59-e996a60f2786.png">

in mobile view
<img width="1440" alt="screen shot 2018-03-04 at 7 35 12 pm" src="https://user-images.githubusercontent.com/28914919/36946448-37258a40-1fe3-11e8-8664-4e450edc2904.png">

in laptop view
<img width="1440" alt="screen shot 2018-03-04 at 7 35 58 pm" src="https://user-images.githubusercontent.com/28914919/36946455-481980d6-1fe3-11e8-8467-01bb148681ae.png">

**Comment by 94151** [comment]
Can i work on this problem?

**Comment by tushar-nitave** [comment]
Has anyone started working on this?

**Comment by 94151** [comment]
@tushar-nitave I think this issue gets closed.

**Comment by tushar-nitave** [comment]
@94151 Yeah. No reply from anyone.

**Comment by sathiraumesh** [comment]
hi  @94151  a pr for the issue has already being created

**Comment by praveenojha33** [comment]
@sathiraumesh Please close this issue if it is done.
