### ISSUE TITLE
/date gets appended to the search query when clicked sort by date under tools tab

### ISSUE THREAD

**Issue by sathiraumesh** [fossasia/susper.com#926]
**I'm submitting a ...**
- [X] bug report
- [ ] feature request

**Current behavior:**

When clicked the sort by date option under tools tab it  appends /date to the search query
**Expected behavior:**

/date not should not be appended to the search query  when clicked sort by date option under tools tab

**Screenshots of the issue:**

<img width="1440" alt="screen shot 2018-03-08 at 12 14 00 am" src="https://user-images.githubusercontent.com/28914919/37112305-0467b808-2268-11e8-9d7e-146c44cd3979.png">

**Comment by rkpattnaik780** [comment]
I would like to work on this issue.

**Comment by praveenojha33** [comment]
@rkpattnaik780 Sure I am assigning it to you.

**Comment by shaharyar-shamshi** [comment]
@rkpattnaik780  are you working on this I am willing to open the pr

**Comment by rkpattnaik780** [comment]
@shaharyar-shamshi my PR is still open needs to be reviewed.
