### ISSUE TITLE
Susper is not responsive tested on chrome

### ISSUE THREAD

**Issue by 94151** [fossasia/susper.com#931]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

Settings are not working for mobile chrome. Crowl Jobs is not working on desktop chrome.  
**Expected behavior:**

All the elements of a website should work fine like settings crawl jobs. Super should responsive on all devices and browsers.
**Screenshots of the issue:**

![capture](https://user-images.githubusercontent.com/17044000/37245144-e4a605d4-24b9-11e8-8099-3499d69c1bbf.PNG)
![screenshot_20180310-214227](https://user-images.githubusercontent.com/17044000/37245145-e4e8cf4a-24b9-11e8-9e12-91092e3b761e.png)

**Comment by sathiraumesh** [comment]
yep nice work need to fix some of the css styles in the pages

**Comment by sathiraumesh** [comment]
can i work on this issue

**Comment by 94151** [comment]
@sathiraumesh  I am working on it.
