### ISSUE TITLE
Pagination bar moving

### ISSUE THREAD

**Issue by lonnieOST** [fossasia/susper.com#936]
I'm submitting what I think is a bug for the Pagination bar shifting after you cycle to the second, and beyond pages after getting some results.

I have noticed something strange with the pagination on the http://susper.com website. I do a test query of "solar panels" and then I get back a list of URL which the pagination showing on the first page of results. Then, if I select Page-2, for example, then the whole pagination bar shifts over to the right to make room for the word "Previous". 

I would think that the whole pagination should not move over at all as it is really distracting and this does not happen on Google or Bing in their layout. 

I took some screenshots of the action and will try to drag them over to see if they get added for you to see. 

Before
![screenshot from 2018-03-12 15-19-28](https://user-images.githubusercontent.com/24719646/37394205-a4674ad6-2749-11e8-9074-326dd2bd78e1.png)

After
![screenshot from 2018-03-12 15-20-31](https://user-images.githubusercontent.com/24719646/37394253-af591c62-2749-11e8-9338-4fd958e8ef2e.png)

Any ideas on a solution since I have this same action when I Git Clone the repository and run it locally?
Thanks in advance and have a good day

**Comment by akalanka95** [comment]
Is any one working on this ?
