### ISSUE TITLE
Some contexts the bottom of the page are not visible as the footer overlaps them in ters and policy page

### ISSUE THREAD

**Issue by sathiraumesh** [fossasia/susper.com#938]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

The contents at the bottom of the page goes under the  footer
**Expected behavior:**

The contents should be visible to the user
**Screenshots of the issue:**

<img width="1440" alt="screen shot 2018-03-14 at 8 15 31 pm" src="https://user-images.githubusercontent.com/28914919/37409654-d73119ee-27c4-11e8-86d4-a796628235ec.png">
<img width="1440" alt="screen shot 2018-03-14 at 8 15 21 pm" src="https://user-images.githubusercontent.com/28914919/37409663-da388dd4-27c4-11e8-9e3b-f9afb1f52dba.png">

**Comment by tushar-nitave** [comment]
Can I take this?

**Comment by sathiraumesh** [comment]
Already finished
