### ISSUE TITLE
Implementing Internationalization Feature in SUSPER.

### ISSUE THREAD

**Issue by praveenojha33** [fossasia/susper.com#944]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Expected behavior:**
The idea is to implement internationalization feature using Angular's ngx-translate.

**Comment by praveenojha33** [comment]
@mariobehling @nikhilrayaprolu @harshit98 @Marauderer97 Can we discuss about having i18n feature in SUSPER search.

**Comment by mariobehling** [comment]
Low priority. Please focus on implementing things like news, proper picture search and connecting with Yacy-Grid.
