### ISSUE TITLE
Searched content get lost when editing the searched word/phrase.

### ISSUE THREAD

**Issue by akalanka95** [fossasia/susper.com#950]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

If I type a letter/space bar after the searched word/phrase, then  lost the searched result content.

**Expected behavior:**

The result content should be present until user searched for a new word/phrase .And search bar should give list of suggested searches.

**Screenshots of the issue:**

- When searched for word

![screenshot 35](https://user-images.githubusercontent.com/23623253/37619993-0ca71fc2-2be1-11e8-867d-712bf56802ad.png)

- When making changes to that searched word (pressing spacebar/ adding more words) the content will  get lost .

![screenshot 39](https://user-images.githubusercontent.com/23623253/37620172-7b6c7b6e-2be1-11e8-99c8-56ad6ef07a28.png)

- Solution 

![screenshot 40](https://user-images.githubusercontent.com/23623253/37620272-b274b676-2be1-11e8-8784-00192cb7a244.png)

**Comment by praveenojha33** [comment]
I am claiming this issue.

**Comment by ValentinBercaru** [comment]
Sorry @praveenojha33 but I did not see your comment and I implemented it before you mentioned you'd claim it.

**Comment by praveenojha33** [comment]
Ok no problem @ValentinBercaru
