### ISSUE TITLE
Related Search section overlapping with analytics section

### ISSUE THREAD

**Issue by Dipesh-Budhiraja** [fossasia/susper.com#954]
**I'm submitting a ...**
- [x] bug report

**Current behaviour:**

Related Searches are overlapping with the Analytics Section as shown in the screenshot.

**Screenshots of the issue:**

![screen shot 2018-03-20 at 2 16 46 pm](https://user-images.githubusercontent.com/29384452/37683438-d710b6e8-2c49-11e8-8e9f-491758f86be8.png)

Can I work on solving this issue?

**Comment by ValentinBercaru** [comment]
Hello @Dipesh-Budhiraja ! Yes, you can work on this issue. All you have to do is to check if the result is longer than N characters. If so, substr it and concatenate with '...'. :smile:

**Comment by harshit98** [comment]
Looks like @Dipesh-Budhiraja is no longer active. @ValentinBercaru can you solve this issue? ✨

**Comment by ValentinBercaru** [comment]
@harshit98 sure! I will solve it today. :smile:
