### ISSUE TITLE
Contents for help section in search settings

### ISSUE THREAD

**Issue by tushar-nitave** [fossasia/susper.com#956]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

The help section in settings -> search settings, re-directs to home page.
**Expected behavior:**

We need to design help page which will help users to troubleshoot frequent problems.
**Screenshots of the issue:**

Can I work on this? Any suggestions?

**Comment by harshit98** [comment]
@tushar-nitave You can work on the issue. But the issue details is still not clear. Can you elaborate? Cheers. ✨

**Comment by praveenojha33** [comment]
@tushar-nitave what is the status of your progress?
