### ISSUE TITLE
Problems with pagination bar

### ISSUE THREAD

**Issue by Marauderer97** [fossasia/susper.com#96]
When we navigate from one page of images, to the next and then click on the all tab, we get results from the 10th page(since a 100 images are displayed each time).
![image](https://cloud.githubusercontent.com/assets/20185076/23576211/fcaf558c-00c4-11e7-9965-d85ff91c6b7d.png)

This may confuse the user, we have two possible solutions
1. Separate pagination bar for each view type(image, all etc)
2. Set page to 1, every time a new view type is clicked on
(Note: Google implements the second suggestion)

**Comment by Marauderer97** [comment]
@nikhilrayaprolu Should I go ahead and rectify it (implementing suggestion 2), I realise this can be a part of #53 , but for refactoring a lot of design decisions have to be made first (PS : sorry for my delay on that, have been busy with a personal emergency).

**Comment by sandeepm96** [comment]
Yeah this is the problem that is occurring after I made the search bar responsive. As the same search bar code is being used in the navbar also, so it appears in the middle. I am working on it now and it will be fixed soon .

**Comment by sandeepm96** [comment]
@Marauderer97 You can go ahead and fix the pagination bar. :)

**Comment by Marauderer97** [comment]
@sandeepm96 I know. :) Just waiting for @nikhilrayaprolu 's opinion

**Comment by harshit98** [comment]
@Marauderer97 It seems to be that search bar has also been shifted from it's position. I think this bug problem came from last commit in which responsive issue has been solved.

**Comment by nikhilrayaprolu** [comment]
@Marauderer97 you can proceed by implementing in the second way(as google does).
@sandeepm96 looks like you have changed element ids which broke the code, try not to change ids since many functionalities are interlinked with ids. any way you have done good work on making the page responsive

**Comment by isuruAb** [comment]
If we are going to implement similar styles like google here we have to change images listing.because google has no any pagination in image search.
