### ISSUE TITLE
The links in the analytics box keeps appending to the the search query when clicked

### ISSUE THREAD

**Issue by sathiraumesh** [fossasia/susper.com#967]
**I'm submitting a ...**
- [X] bug report
- [ ] feature request

**Current behavior:**

When clicked a link in the analytics box it gets appended to the query string.Even going further It keeps itself appending again and agin

**Expected behavior:**

It should not get appended to the query strting

**Screenshots of the issue:**

- when clicked once
<img width="1440" alt="screen shot 2018-03-29 at 9 19 44 pm" src="https://user-images.githubusercontent.com/28914919/38099106-6378d7a6-3397-11e8-8a0e-986054771d48.png">

- when clicked twice
<img width="1440" alt="screen shot 2018-03-29 at 9 21 48 pm" src="https://user-images.githubusercontent.com/28914919/38099074-4ac4f500-3397-11e8-9b2a-490ad0819a41.png">

**Comment by praveenojha33** [comment]
Shall I fix it?

**Comment by sathiraumesh** [comment]
Have you fixed it
