### ISSUE TITLE
About Page link not working

### ISSUE THREAD

**Issue by Marauderer97** [fossasia/susper.com#97]
Clicking on About page gives a 404 Page not found error.
![image](https://cloud.githubusercontent.com/assets/20185076/23576248/34149144-00c6-11e7-8df2-7c7b5db085e8.png)
![image](https://cloud.githubusercontent.com/assets/20185076/23576249/3c842b14-00c6-11e7-891f-476e9922beef.png)
This bug was fixed earlier, but has funnily enough risen again. We can redirect the user to yacysearch about page, but from what we decided earlier, I think a new About page needs to be added for susper.

**Comment by Marauderer97** [comment]
@nikhilrayaprolu @mariobehling What should our about page contain?
I am thinking of the following sub topics
1. A brief description of susper( a search engine, with a yacy backend, etc.)
2. A link to our Github repository susper.com(Encouraging bugs to be reported and allowing newcomers to know where to contribute) 
3. A list of our contributors? (This can be edited, and each newcomer can write his name here, like a credits page, flappy-svg has something like this)

**Comment by harshit98** [comment]
@Marauderer97 
- Can we also add a social media section? In that section we can give details about FOSSASIA being on Facebook, LinkedIn, Twitter and some more details about FOSSASIA?
- A list of project maintainers/mentors? (this is somewhat different from contributors)

**Comment by nikhilrayaprolu** [comment]
@Marauderer97 you can proceed adding 1 and 2 .
but for the 3rd I would suggest you to take input from @mariobehling

**Comment by harshit98** [comment]
@Marauderer97 any updates regarding this issue?

**Comment by mariobehling** [comment]
Please keep it simple and implement the same design as on loklak: http://loklak.net/about

The content is not so important to discuss now. Simply making the style the same is sufficient. So, we can go back to the actual features.

**Comment by mariobehling** [comment]
@haritha28 Regarding your comments here https://github.com/fossasia/susper.com/issues/97#issuecomment-284142042

Please keep all this really simple now. List of maintainers etc. is really not necessary. GitHub already keeps that information. Please focus on the actual features of susper, instead of building a "homepage".

**Comment by mariobehling** [comment]
However, totally agree to follow style of loklak.net. Please go ahead. Thanks for considering the details!
