### ISSUE TITLE
Found a small unterminated css style statement

### ISSUE THREAD

**Issue by sathiraumesh** [fossasia/susper.com#970]
**I'm submitting a ...**
- [X] bug report
- [ ] feature request

**Screenshots of the issue:**
<img width="1440" alt="screen shot 2018-04-02 at 7 31 12 pm" src="https://user-images.githubusercontent.com/28914919/38199015-a6590498-36ac-11e8-9d06-e178602e34b2.png">

**Comment by praveenojha33** [comment]
@sathiraumesh Please close this issue as it is solved.
