### ISSUE TITLE
found some unfinished css style rules

### ISSUE THREAD

**Issue by sathiraumesh** [fossasia/susper.com#975]
**I'm submitting a ...**
- [X] bug report
- [ ] feature request

**Current behavior:**

**Expected behavior:**

**Screenshots of the issue:**

<img width="1440" alt="screen shot 2018-04-04 at 9 05 08 pm" src="https://user-images.githubusercontent.com/28914919/38318049-1c0a2780-384c-11e8-8edf-8bbd2b34827d.png">

<img width="1440" alt="screen shot 2018-04-04 at 9 03 55 pm" src="https://user-images.githubusercontent.com/28914919/38318055-1e2d6da6-384c-11e8-97f2-1458c3c27325.png">

**Comment by praveenojha33** [comment]
@sathiraumesh Close this issue as it is solved.
