### ISSUE TITLE
Advanced search  filter gets appended twice when selected a an option for filter

### ISSUE THREAD

**Issue by sathiraumesh** [fossasia/susper.com#977]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

The filter gets appended  for the search query twice when clicked

**Expected behavior:**

The filter should get appended once

**Screenshots of the issue:**

<img width="1440" alt="screen shot 2018-04-05 at 6 47 36 pm" src="https://user-images.githubusercontent.com/28914919/38368110-0b6b5578-3902-11e8-9c23-f5d0ad0b54fb.png">

<img width="1440" alt="screen shot 2018-04-05 at 6 50 03 pm" src="https://user-images.githubusercontent.com/28914919/38368615-5dc30766-3903-11e8-83f5-015e4e80911c.png">

**Comment by praveenojha33** [comment]
Hello @sathiraumesh Please refer to the issue properly in PR. So that it can be figured out that a PR for the issue has been made.

**Comment by praveenojha33** [comment]
@sathiraumesh Please close this issue it has been solved.
