### ISSUE TITLE
Search bar position inconsistent

### ISSUE THREAD

**Issue by Marauderer97** [fossasia/susper.com#98]
The Search bar seems to be in the right position only in the home page, 
![image](https://cloud.githubusercontent.com/assets/20185076/23576294/b1e09928-00c7-11e7-934c-31c8aadfbb1f.png)
but it is in the middle of the navbar in the results page( inconsistent with the google design we are trying to replicate):
![image](https://cloud.githubusercontent.com/assets/20185076/23576301/d0d4f004-00c7-11e7-9044-087502f18c66.png)

![image](https://cloud.githubusercontent.com/assets/20185076/23576309/146321f6-00c8-11e7-811b-fd4dd1dfd3b4.png)

and pushed to a corner in the 404 error page:
![image](https://cloud.githubusercontent.com/assets/20185076/23576307/eee9193a-00c7-11e7-9e5d-9e93c691ece4.png)

**Comment by sandeepm96** [comment]
I am making it responsive for all pages. Till now only home page is done. Working on it. :)

**Comment by sandeepm96** [comment]
@Marauderer97 Could you reopen the issue #84 and reference this issue under it.
