### ISSUE TITLE
Found unterminated css style rule in contact com

### ISSUE THREAD

**Issue by sathiraumesh** [fossasia/susper.com#985]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Screenshots of the issue:**
<img width="1440" alt="screen shot 2018-04-21 at 9 44 14 pm" src="https://user-images.githubusercontent.com/28914919/39086349-a869d7ac-45ad-11e8-8382-9a0e45f8c6ad.png">

**Comment by praveenojha33** [comment]
Hello @sathiraumesh try closing some issues which are alike this issue.As you have merged all the PRs a single issue is sufficient for it. You can refer all closed issues in comments. :sparkle:

**Comment by harshit98** [comment]
This issue can be closed. @mariobehling

**Comment by praveenojha33** [comment]
@sathiraumesh Close this issue as it is solved now.
