### ISSUE TITLE
Commits not getting reflected to susper.com

### ISSUE THREAD

**Issue by praveenojha33** [fossasia/susper.com#988]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

All the latest merged commits are not shown on susper.com . However everything works fine locally and also code for the same commits are present on master branch of the project.

**Expected behavior:**
 
Merged Commits should be reflected on susper.com .

**Screenshots of the issue:**

![local](https://user-images.githubusercontent.com/25537606/39455246-126c0354-4cfd-11e8-866a-12b1cb5a6669.png) 
Locally everything works fine( here is a latest commit showing a new theme)
![not_working](https://user-images.githubusercontent.com/25537606/39455388-bffd296c-4cfd-11e8-8961-8271f573e676.png)
Same commit does not appear on susper.com

**Comment by praveenojha33** [comment]
https://github.com/fossasia/susper.com/pull/979
https://github.com/fossasia/susper.com/pull/978
https://github.com/fossasia/susper.com/pull/968
https://github.com/fossasia/susper.com/pull/949
https://github.com/fossasia/susper.com/pull/935
https://github.com/fossasia/susper.com/pull/929
https://github.com/fossasia/susper.com/pull/943
It is the list of all PRs which are commited but their changes do not appear on susper.com

**Comment by harshit98** [comment]
Hi @praveenojha33 I can suggest you some solutions to solve the issue:

- Update all the dependencies.
- Do the latest version bump of Angular.
- Update RxJS.

**Comment by praveenojha33** [comment]
Last commit whose change are shown own susper.com is https://github.com/fossasia/susper.com/commit/f0a6f5c2a7632b6e1d8b834c29880605d703402e

**Comment by praveenojha33** [comment]
This issue is caused due to an error with Travis CI Clean Deploy on `gh pages`.This causes error in generated builds on server.It can be seen on console on susper.com.
