### ISSUE TITLE
Advanced search does not work 

### ISSUE THREAD

**Issue by Marauderer97** [fossasia/susper.com#99]
The Advanced Search option seems to be broken. Clicking on it does nothing.
![image](https://cloud.githubusercontent.com/assets/20185076/23576365/4738042e-00c9-11e7-93ec-b88339b3cc61.png)

**Comment by Marauderer97** [comment]
@nikhilrayaprolu The advanced search was working perfectly before, perhaps a css fix, or a change in class name in one of the PRs broke it? We perhaps need to have tests in place to prevent this from happening next time

**Comment by harshit98** [comment]
@Marauderer97 I think, while fixing HTML lint errors- maybe I have changed a class name or id name. I'm working on the test issue though. My PR is still open. You can suggest me more test to be written. :)
