### ISSUE TITLE
Implementing a documents tab in SUSPER 

### ISSUE THREAD

**Issue by praveenojha33** [fossasia/susper.com#991]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Expected behavior:**
This feature can be easily achieved by creating a Documents Tab in the UI 
and using filter query (fq) parameter and ‘url_file_ext_s’ and filtering the files 
with extensions pdf,doc,ppt etc. 
More about fq parameter and ‘url_file_ext_s’ can be found here: 
https://wiki.apache.org/solr/CommonQueryParameters 

.One more way to achieve this feature is by using advanced parameters of 
YaCy like ‘filetype’ by which we can easily filter files of any extension. 
One drawback of this way can be unable to filter files based on more than one 
file type.

**Comment by praveenojha33** [comment]
@mariobehling @harshit98 @sathiraumesh Please suggest your views. I am working on it.

**Comment by mariobehling** [comment]
Please implement this as a filter in advanced search.

**Comment by praveenojha33** [comment]
I have opened a separate issue for that so I am closing it.
