### ISSUE TITLE
Revert changes made by Devs to check the New Theme on susper.com

### ISSUE THREAD

**Issue by praveenojha33** [fossasia/susper.com#995]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

There are some inert changes which were made by @ValentinBercaru in this commit https://github.com/fossasia/susper.com/pull/983 to check whether it is shown on susper.com in reference to this issue #988 . Like `testTerminal` button in customization option, Also make `night` button to `Night`. 

**Expected behavior:**

It should not be there.

**Screenshots of the issue:**

![image](https://user-images.githubusercontent.com/25537606/40324154-4cb5e58a-5d55-11e8-93d9-c05829c1e8f5.png)

**Comment by ValentinBercaru** [comment]
Hello @praveenojha33 ! Sorry, but I didn't have enough time to revert the changes. Thank you for repairing it! :D
