### ISSUE TITLE
Adding Yarn as a Dependency Manager along with NPM.

### ISSUE THREAD

**Issue by praveenojha33** [fossasia/susper.com#997]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Expected behavior:**
Yarn is a dependency manager introduced by facebook . It is faster than npm and it can install dependencies even when the machine is offline. More about Yarn can be found here https://yarnpkg.com/en/

**Comment by praveenojha33** [comment]
@simsausaurabh Please suggest your views.

**Comment by simsausaurabh** [comment]
@praveenojha33 go ahead :+1:
